### ISSUE TITLE
image upload

### ISSUE THREAD

**Issue by visr** [Deltares/Ribasim#1]
Uploading images here won't work anymore for displaying them in our docs, due to GitHub changes, see https://github.blog/changelog/2023-05-09-more-secure-private-attachments/

Using HTML `img` tags like this still works:

```html
<img alt="Cascading polders" src="https://github.com/Deltares/Ribasim/assets/4471859/6dba5af2-14fb-47a5-bdfe-69c2c41f761d" class="img-fluid">
```

![bar](https://user-images.githubusercontent.com/4471859/179259174-0caccd4a-c51b-449e-873c-17d48cfc8870.png)

![timeseries](https://user-images.githubusercontent.com/4471859/179259333-070dfe18-8f43-4ac4-bb38-013b252e2e4b.png)

![Hupselse Beek](https://user-images.githubusercontent.com/4471859/185932183-62c305e6-bc14-4f3c-a74c-437f831c9145.png)

**Comment by AmyWilcox1** [comment]
<img width="544" alt="Mozart_comparison_Hupsel" src="https://user-images.githubusercontent.com/103200724/186892574-eacf646d-3ae0-483e-9dae-81ec32f78428.PNG">
<img width="585" alt="Mozart_comparison_Hupsel_2" src="https://user-images.githubusercontent.com/103200724/186892581-557e2a0a-7b17-47cc-b65c-a2f7e3e30b66.PNG">
<img width="612" alt="Mozart_comparison_Tol" src="https://user-images.githubusercontent.com/103200724/186892605-db217b55-13d6-48bb-a78e-3bbf4acc70c1.PNG">
<img width="589" alt="Mozart_comparison_Tol_2" src="https://user-images.githubusercontent.com/103200724/186892628-7cb0d3cd-9439-46cb-b6b8-9908d9c7e09a.PNG">

**Comment by AmyWilcox1** [comment]
[](url
![multi_user_plot](https://user-images.githubusercontent.com/103200724/187085506-0ee79dd0-8023-42e8-9b05-4b9f433ae73e.jpg)
)

**Comment by AmyWilcox1** [comment]
![Hupsel_series](https://user-images.githubusercontent.com/103200724/187200598-edae91ad-8140-466a-b06e-3289babeee27.png)

**Comment by Huite** [comment]
![Hupsel-primary-secondary](https://user-images.githubusercontent.com/13662783/187623520-65155d3f-3dd9-457f-9868-04e8e3199a5b.PNG)

**Comment by Huite** [comment]
![Hupsel-primary](https://user-images.githubusercontent.com/13662783/187625163-d0a81bb6-7f55-4ad1-83e2-90ec1ee79740.PNG)
![Hupsel-secondary](https://user-images.githubusercontent.com/13662783/187625170-1acdfb41-7077-443f-b140-ae18cbf21e53.PNG)
![Hupsel-tertiary](https://user-images.githubusercontent.com/13662783/187625174-3eec28b5-ddbb-4870-94c3-d9e9a43f8eb4.PNG)

**Comment by Huite** [comment]
![VolumeDepth](https://user-images.githubusercontent.com/13662783/187665858-d01fd60f-f3c2-4662-af82-cf8acfbe169b.PNG)

**Comment by visr** [comment]
![Deltares_logo_D-blauw_RGB](https://user-images.githubusercontent.com/4471859/187672447-adb9cb11-16ca-488b-bef9-08e059fe6d55.svg)
![NHI_outs](https://user-images.githubusercontent.com/4471859/187672456-874b344a-9ad3-42b5-af6a-93517f7fbbe8.png)

**Comment by Huite** [comment]
![Hupsel-level-grid](https://user-images.githubusercontent.com/13662783/187672663-99b9efd3-5e09-4d6f-bd3a-4180ff5b2ce4.PNG)
![Hupsel-volume-grid](https://user-images.githubusercontent.com/13662783/187672671-20d22031-3b50-474a-9ee1-4408c25a4f30.PNG)

**Comment by Huite** [comment]
![hupsel-steady-state](https://user-images.githubusercontent.com/13662783/187715341-fd99dc06-2eda-4b84-a201-650dc7220574.png)
![hupsel-steady-state-volume0](https://user-images.githubusercontent.com/13662783/187715349-9eee8830-9b03-4a88-b7c9-b16004c694f6.png)

**Comment by Huite** [comment]
![tol-steady-state](https://user-images.githubusercontent.com/13662783/187720891-798f1f24-8664-492d-a21f-365ed1085ed8.png)

**Comment by visr** [comment]
![image](https://user-images.githubusercontent.com/4471859/224939069-9aae77ea-898f-442f-83b5-f2671c114956.png)
![image](https://user-images.githubusercontent.com/4471859/224939080-7fec5db2-4417-4f7b-8e45-034d4cf4fd75.png)
![image](https://user-images.githubusercontent.com/4471859/224939101-228e068a-875b-4df2-98bb-6ee6a3830ddd.png)
![image](https://user-images.githubusercontent.com/4471859/224939126-b38f0eed-2e89-4120-b541-5b8c31798c09.png)
![image](https://user-images.githubusercontent.com/4471859/224939143-19e9931e-da4b-4717-ba28-67a0f141dd40.png)
![image](https://user-images.githubusercontent.com/4471859/224939165-45807f16-2d3a-41b3-92a2-7fe0e86ae72b.png)
![image](https://user-images.githubusercontent.com/4471859/224939182-3486ff0b-842b-4f98-a37e-ecd04f29aa7f.png)
![image](https://user-images.githubusercontent.com/4471859/224939204-2aa2ead2-a028-4673-b747-abeadd821ec8.png)
![image](https://user-images.githubusercontent.com/4471859/224939223-66e232c0-748c-46f0-ba1b-8751a965f114.png)
![image](https://user-images.githubusercontent.com/4471859/224939237-67c1150b-15ec-4044-a02a-26a82f81da05.png)
![image](https://user-images.githubusercontent.com/4471859/224939257-ae8e4105-910b-4d0c-b22f-51faff9ea492.png)
![image](https://user-images.githubusercontent.com/4471859/224939276-ca8f856d-3325-49a7-b457-78b09b81ac5e.png)
![image](https://user-images.githubusercontent.com/4471859/224939287-a8b9f351-9aea-4e3a-8417-3867cd40cda5.png)
![image](https://user-images.githubusercontent.com/4471859/224939297-4b0ca812-9618-4d25-ab7a-518bf1ca63e1.png)
![image](https://user-images.githubusercontent.com/4471859/224939328-8359272a-30bb-4eb1-ab6c-968318ac3997.png)
![image](https://user-images.githubusercontent.com/4471859/224939342-c6939331-a60d-4526-a350-3cddb122c62d.png)
![image](https://user-images.githubusercontent.com/4471859/224939354-523cac79-dcd5-4c43-ab5a-db7672fb743e.png)
![image](https://user-images.githubusercontent.com/4471859/224939363-88716d43-0536-499d-adb8-2fb4223c0f87.png)
![image](https://user-images.githubusercontent.com/4471859/224939378-a026aec7-419d-4e6e-8b20-df80aa415659.png)
![image](https://user-images.githubusercontent.com/4471859/224939389-17add58d-6701-49c5-a23a-ce367572d9cd.png)
![image](https://user-images.githubusercontent.com/4471859/224939408-5c291840-90a4-4efa-a2f0-4fb5986b8779.png)
![image](https://user-images.githubusercontent.com/4471859/224939424-ec4c77ff-3d6b-4635-b407-ef18376587e9.png)
![image](https://user-images.githubusercontent.com/4471859/224939436-a9643b68-dff0-49c3-899d-6ba13d9a6d52.png)
![image](https://user-images.githubusercontent.com/4471859/224939450-e369791d-3229-4621-87b0-7e1d34d0514d.png)
![image](https://user-images.githubusercontent.com/4471859/224939471-85a23936-6eb6-4a80-a5b7-8c9a55ddc7f7.png)

**Comment by visr** [comment]
<img width="837" alt="hws" src="https://github.com/Deltares/Ribasim/assets/4471859/0079d221-0f0b-424f-98cc-2cbcc1b4d17d">

**Comment by evetion** [comment]
<img width="462" alt="Screenshot 2024-08-27 at 14 18 03" src="https://github.com/user-attachments/assets/bee6af6f-7623-4d1e-98ed-edc26c524377">
<img width="361" alt="Screenshot 2024-08-27 at 14 17 28" src="https://github.com/user-attachments/assets/048d342d-dd2b-4e67-b8a0-7bbb8fe3f243">
<img width="434" alt="Screenshot 2024-08-27 at 14 10 21" src="https://github.com/user-attachments/assets/6e811bb9-1817-4505-b8a4-a96ced5b6c26">

**Comment by Jingru923** [comment]
![image](https://github.com/user-attachments/assets/467e71da-def4-4723-91de-f76bf78758fe)
![image](https://github.com/user-attachments/assets/e7c4e14c-07ca-416a-877f-9ea0459bdf3d)
![image](https://github.com/user-attachments/assets/3a6b05d9-c535-4054-be92-c593a0c03d93)
![image](https://github.com/user-attachments/assets/14799746-3b4d-4d4c-9b8a-37fbe1d88081)
![image](https://github.com/user-attachments/assets/c3bfceb8-6da0-46d3-9ded-e7a039d874ec)
![image](https://github.com/user-attachments/assets/1e039b16-1db9-4bb1-bd85-9e3b6692d771)
![image](https://github.com/user-attachments/assets/37c99ecf-dfd1-47e0-8be7-61ec885da232)
![image](https://github.com/user-attachments/assets/64fa750c-d7b9-4f5c-9a24-2f95e2b8bba8)
![image](https://github.com/user-attachments/assets/6241d388-5373-4f6c-b1f6-ff1a1a34d0e6)
![image](https://github.com/user-attachments/assets/cce87cfb-9a7b-4025-812a-e2c35fa932a9)
![image](https://github.com/user-attachments/assets/2a27ab07-a4c5-4906-bdcd-45491f868042)
![image](https://github.com/user-attachments/assets/e87f75d3-c721-41f5-92c3-768a42ffd92e)
![image](https://github.com/user-attachments/assets/b4563cbd-4919-4422-9cb8-70deebf98094)
![image](https://github.com/user-attachments/assets/615f6d93-bdb9-4a38-a308-c5c0929930b5)
![image](https://github.com/user-attachments/assets/545b6ce0-1a87-4f3b-b87e-79d7382beac2)
![image](https://github.com/user-attachments/assets/937a4868-87d1-4b5f-b37d-ab865428740d)
![image](https://github.com/user-attachments/assets/16fce006-5e8b-4657-9b80-f26d1489ca99)

**Comment by Huite** [comment]
What do you mean? If you're worried that it's private, just open an incognito tab in your browser  and put the URL there.
Edge even has a "Open link in InPrivate window" if you right-click the image.

By the way, it might be worthwhile to experiment with exporting matplotlib figures as SVG instead. They'll be nice and crisp then.

QGIS also has an export to SVG option: https://docs.qgis.org/3.34/en/docs/user_manual/print_composer/create_output.html#export-as-svg

**Comment by Jingru923** [comment]
@Huite Thanks! But if the picture's url starts with private-user-image, then our document will not able to find it and display it. That's why I was asking

**Comment by evetion** [comment]
If you edit your post you should be able to see non-private image urls.
