### ISSUE TITLE
definition subgrid using "level" instead of "basin_level"

### ISSUE THREAD

**Issue by harm-nomden-sweco** [Deltares/Ribasim#1008]
Subgrid is defined by table with columns: "subgrid_id", "node_id", "basin_level", "subgrid_level". 
I would suggest to use "level" instead of "basin_level" or use "basin_node_id" instead of "node_id".

**Comment by visr** [comment]
I see the inconsistency here, though my feeling is that clarity and being explicit is more important here. Without context `basin.subgrid.level` cannot be interpreted as belonging to the basin or the subgrid. And `node_id` is consistent with what we use in other tables as well.

**Comment by harm-nomden-sweco** [comment]
ok, clear. explicit is indeed (more) important. It was the first time I used this.

**Comment by visr** [comment]
Ok. I'll close this then. Appreciate the suggestions though.
