### ISSUE TITLE
Add priority to level control

### ISSUE THREAD

**Issue by SnippenE** [Deltares/Ribasim#1018]
**What**
Common situation in IWRM studies is to supply a downstream demand to maintain a basin-specific level. For this, we want to be able to define a specific priority to a user "level control" as global setting for a whole (sub)netwerk and specific basins.

**Why**
More natural way of modelling that closer to the logic of operations

**How**
[ ] Make level control as user available in allocation
[ ] ....

**Additional context**

**Comment by gijsber** [comment]
zie ook #564

**Comment by visr** [comment]
Closing a favor of #564, which already mentions user provided priorities are required.
