### ISSUE TITLE
Better GUI integration attributes QGIS-plugin

### ISSUE THREAD

**Issue by gijsber** [Deltares/Ribasim#102]
Currently, the GUI access to attributes is pretty unhandy.
Improved accessibility for attribute editing is desired

**Comment by visr** [comment]
This isn't great yet, but not terrible either. I'd say let's close, we can always open more specific issues later.

![image](https://github.com/Deltares/Ribasim/assets/4471859/6257bc31-b0da-4fd6-8946-0ce09ee81ea7)
![image](https://github.com/Deltares/Ribasim/assets/4471859/b9314b4c-78bb-4109-9278-273ff705bdfe)
