### ISSUE TITLE
distribute ribasim executables

### ISSUE THREAD

**Issue by visr** [Deltares/Ribasim#105]
Currently we build nightly executables of the `ribasim` command line tool on TeamCity. It would be nice if we could make these artifacts public, or to automatically upload builds to a public place. This way users can quickly test out fixes.

**Comment by gijsber** [comment]
Delft-FEWS never pushed automatically from Teamcity to external FTP site.

Candidatee route to investigate:
Teamcity-artifact --> \\dfs-trusted.directory.intra\dfs\repository\ --> outside FTP

**Comment by gijsber** [comment]
Under discussion by Dimitri Tzoumas and Floris Langeraert

**Comment by visr** [comment]
Thanks, I also asked Edward about if this would be possible with download.deltares.nl.

**Comment by evetion** [comment]
We're now automatically pushing the Teamcity artefacts to s3, which are publicly available. I'm working on getting a nightly link to work as well.

**Comment by gijsber** [comment]
No news from Dimitri.
For a centralized Deltares solution one is looking into:
https://www.sonatype.com/products/nexus-repository

@evetion : can you provide the link so we can communicate this coming Tuesday to the partners

**Comment by visr** [comment]
Here is the link of a recent build, build number is in the link:

https://ribasim.s3.eu-west-3.amazonaws.com/teamcity/Ribasim_Ribasim/BuildRibasimCliWindows/2304861/ribasim_cli.zip

We should also put that in the docs.

**Comment by evetion** [comment]
Now live: [ribasim.s3.eu-west-3.amazonaws.com/teamcity/Ribasim_Ribasim/BuildRibasimCliWindows/latest/ribasim_cli.zip](https://ribasim.s3.eu-west-3.amazonaws.com/teamcity/Ribasim_Ribasim/BuildRibasimCliWindows/latest/ribasim_cli.zip) 🎉
