### ISSUE TITLE
Re-evaluate code-generation in Ribasim Python

### ISSUE THREAD

**Issue by Hofer-Julian** [Deltares/Ribasim#1077]
**What**
We currently generate code from Julia core for Ribasim Python.

**Why**
The code-generation in Ribasim Python is convenient for developers, but complicated to understand.
We also see problems that we can trace back to it.

**How**
We should take a closer look and see if we can improve/simplify it.
There are two angles to it:
- generate pandera models directly instead of going via pydantic
- remove code generation

**Comment by Hofer-Julian** [comment]
Summary of discussions:

With @deltamarnix:
There are two good options to generate Python files with Pandera classes:
- From within Julia with [OteraEnginge.jl](https://github.com/MommaWatasu/OteraEngine.jl)
- Keeping the JSON Schema, and generating with Python and Jinja

With @visr:
- Removing JSON Schema generating might simplify code quite a bit (still to investigate)
- On the other hand, if we keep the JSON Schema we could generate Table docs within Quarto&Python instead of writing them by hand as we do now

**Comment by deltamarnix** [comment]
I have rewritten the code generator, we now have complete control of the code that is being generated via OteraEngine. This will also give us the opportunity to retrieve other data from Julia, like the sorting order. #1096
