### ISSUE TITLE
Create a (cumulative) integrated boundary flux in Ribasim and expose it via BMI

### ISSUE THREAD

**Issue by HendrikKok** [Deltares/Ribasim#1084]
For the coupling to MODFLOW 6 we need to know how much of a requested infiltration flux could be realized by Ribasim over a given timespan. If Ribasim does a cumulative integration of its boundary fluxes, we can extract a realized volume per timestep by computing the difference over any given timespan.

**Comment by gijsber** [comment]
linked to #935

**Comment by visr** [comment]
Fixed by #1300
