### ISSUE TITLE
Update 'Adding node types' documentation page

### ISSUE THREAD

**Issue by SouthEndMusic** [Deltares/Ribasim#1085]
**What**
Reflect all changes to Ribasim python and the Julia core on the node adding page of the contribution docs.

**How**
Reflect these changes:
- The change of the schema format in the schema format in `ribasim_qgis/core/nodes.py`;
- Deleting the scripts in the folder `python/ribasim/ribasim/node_types`;

and more, see https://github.com/Deltares/Ribasim/pull/1082 which is the most recent addition of a node type.

**Comment by SouthEndMusic** [comment]
Quite some work has already been done in this PR: https://github.com/Deltares/Ribasim/pull/1188

**Comment by visr** [comment]
Closing this. It's not complete yet, but useful and sometimes being updated.
