### ISSUE TITLE
Qgis.AttributeFormSuppression.Default does not work on older QGIS versions?

### ISSUE THREAD

**Issue by Huite** [Deltares/Ribasim#1090]
Currently getting this error when trying to start the QGIS plugin:

```
  File "C:\Users/bootsma/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ribasim_qgis\widgets\ribasim_widget.py", line 178, in add_layer
    else Qgis.AttributeFormSuppression.Default
AttributeError: type object 'Qgis' has no attribute 'AttributeFormSuppression'
```

I reckon this enum wasn't introduced before?

Both on:
QGIS version 3.28.12-Firenze and 3.30.1-'s-Hertogenbosch

**Comment by Huite** [comment]
Problem is this change:
[ribasim_qgis/widgets/ribasim_widget.py](https://github.com/Deltares/Ribasim/pull/1065/files#diff-e9cd6c2909d47bede9262ee9ff6b73692da721fcad97ddec7d5b8c22b76736d6)

in: ribasim_qgis/widgets/ribasim_widget.py

**Comment by visr** [comment]
We should revert 8a22fc0630f343069fd3c285ae46e9fde0c71a32 for now. We can type ignore the mypy issue for now such that #1078 will not break on this and add a reminder issue that we have to redo this when bumping the least supported QGIS version.
