### ISSUE TITLE
Log a warning if an unknown config entry is present

### ISSUE THREAD

**Issue by Hofer-Julian** [Deltares/Ribasim#1094]
It's quite easy to run into situations of invalid log entries, like https://github.com/Deltares/Ribasim/issues/1093.

Logging a warning, when an unknown config entry is present, would be useful for both users and developers.

**Comment by visr** [comment]
Right now this is an entry in the core:
```
ERROR: InvalidKeyError: invalid key my_extra_key, possible keys are: starttime, endtime, input_dir, results_dir, database, allocation, solver, logging... please check documentation for other valid keys
```

But silently added/ignored in Ribasim Python:
```python
import ribasim

solver = ribasim.Solver(my_extra_key=2)
assert solver.my_extra_key == 2

model = ribasim.Model(filepath="ribasim.toml")
assert model.my_extra_key == 3
```

Probably the best would be to just give an error here?

**Comment by Hofer-Julian** [comment]
> Right now this is an entry in the core:
> 
> ```
> ERROR: InvalidKeyError: invalid key my_extra_key, possible keys are: starttime, endtime, input_dir, results_dir, database, allocation, solver, logging... please check documentation for other valid keys
> ```
> 

Interesting, then why did we never notice the extra key mentioned in https://github.com/Deltares/Ribasim/issues/1093

**Comment by visr** [comment]
I don't think that key was written to any of our test model TOML files.

**Comment by Hofer-Julian** [comment]
> I don't think that key was written to any of our test model TOML files.

Hah, that's weird 😅

**Comment by Hofer-Julian** [comment]
Will close the issue for now. Logging a warning within Ribasim Core is good enough for now IMO
