### ISSUE TITLE
Add `user.realized` and expose via BMI

### ISSUE THREAD

**Issue by SouthEndMusic** [Deltares/Ribasim#1098]
**What**
https://github.com/Deltares/Ribasim/pull/1081 exposes a flat user demand vector via the BMI. As mentioned in https://github.com/Deltares/Ribasim/issues/893, a realized average abstraction from the users is also needed in the BMI for coupling.

**How**
Add a field `user.realized::Vector{Float64}` with the realized flow per user over the required timestep (?). To keep it general, return flow should be taken into account, so that the realized flow should be the average of the difference between the abstraction and the return flow.

**Comment by visr** [comment]
We should be able to use the same method as the one required for #935.
