### ISSUE TITLE
Distinguish between evaporation/different flows in output flows

### ISSUE THREAD

**Issue by evetion** [Deltares/Ribasim#1112]
To correctly calculate (salt) concentrations with Delwaq (#649), one simply "forgets" to forward the evaporation flow to Delwaq, causing a water imbalance, that correctly increases the concentration.

We therefore need to save at least the evaporation flows, so it can be subtracted from the total flows at each timestep. We can also split them all.

**Comment by visr** [comment]
See also #661.
