### ISSUE TITLE
order of discrete control settings gets mixed while writing model to toml

### ISSUE THREAD

**Issue by JvanHouwelingen** [Deltares/Ribasim#1117]
I load and update a model within python. Before writing the updated model to the toml, the settings of the discrete control are in the right order. When saving the model, the order of the settings of one control node is reversed. This gives an error when running the model:

Error: Control state specified for neither FFT nor FFT for DiscreteControl node #...

Why is/How could be the order of the settings for one node reversed?

**Comment by visr** [comment]
Before writing a model with Ribasim-Python, all tables are sorted following the sort order mentioned in the restrictions column on this page: https://deltares.github.io/Ribasim/core/usage.html#sec-discrete-control

In most cases this sorting does not have any effect on model results, but for truth states like FFT there is an assumption that the order of the letters FFT correspond to the final sorting of the condition table. So the solution is to take that into account and arrange the letters in that order.

I do feel that this is a weak spot in the design though, that we can hopefully improve upon in the future.

**Comment by JvanHouwelingen** [comment]
Strange thing is that it happens just with one discrete control node. There are multiple discrete control nodes within my schematization with the same setup (just different greater_than levels).

**Comment by visr** [comment]
The greater_than values are also sorted.

**Comment by JvanHouwelingen** [comment]
yes true. the order is reversed (for just one node) in both dataframes. But exactly on that particular node, the run gives an error.

**Comment by visr** [comment]
In #1197 the documentation on this is clarified. It is still not that intuitive, but with this suggestions it should be possible to rewrite your truth states in the correct sorted order that matches the order in which the files are saved.
