### ISSUE TITLE
Add supply/demands for basins in allocation to `allocation.arrow` output

### ISSUE THREAD

**Issue by SouthEndMusic** [Deltares/Ribasim#1122]
**What**
The supply/demand of basins is computed (since https://github.com/Deltares/Ribasim/pull/1082) but never stored. I propose to store this information in the `allocation.arrow` output file. It fits in there quite well, apart from that the column name `user_node_id` must be generalized to something that encompasses all nodes that have a demand.

For testing, expand on  `@testitem "Allocation level control"`. Also add a test for stage 5 of the graph in https://github.com/Deltares/Ribasim/pull/1082#issuecomment-1943469944.

**Comment by visr** [comment]
> It fits in there quite well, apart from that the column name user_node_id must be generalized to something that encompasses all nodes that have a demand.

Sounds like the combination of `node_type` and `node_id` will do, in light of #1113.
