### ISSUE TITLE
Create substance/concentration input tables

### ISSUE THREAD

**Issue by evetion** [Deltares/Ribasim#1123]
For the boundaries, and set a similar table for the state of a basin (given it also has boundaries).

After a long discussion with Martijn, we ended up with a separate table type that has
`id, time, substance, concentration` columns. In #1111 I'm still using a concentration field on the existing static/time tables for the boundary nodes.

This data is all used for Delwaq input when coupling, but could also be used in the future for our own tracer/salt calculations.

**Comment by Huite** [comment]
Conceptually, how would you make a distinction between drainage/infiltration concentrations versus precipitation? Or evaporation, which shouldn't subtract solutes (in general).

For what it's worth in terms of inspiration: MODFLOW 6 has a flow model and a transport model.
The flow model has a boundary, e.g. recharge: https://modflow6.readthedocs.io/en/latest/_mf6io/gwf-rch.html
In case of a linked transport model, the flow boundary has an auxiliary array defined with the concentration.
(A specific source can also be added separately, which does not add flow but does add solute.)

From the perspective of the user, solute concentrations are conceptually part of the boundary condition just as much as the flow. In imod-python, we've chosen to add the concentration as an optional argument to the flow boundaries: https://deltares.github.io/imod-python/api/generated/mf6/imod.mf6.Recharge.html
This also makes it less likely that you forget to define concentrations for a boundary.

**Comment by evetion** [comment]
Done in #1267
