### ISSUE TITLE
Documentation: clarify that Ribasim uses "long" tables almost everywhere

### ISSUE THREAD

**Issue by Huite** [Deltares/Ribasim#1151]
**What**
I linked some of the Ribasim docs to @JaccoHoogewoud. He mentioned that the current examples are not maximally clear, in particular:

```python
profile = pd.DataFrame(
    data={
        "node_id": [1, 1, 3, 3, 6, 6, 9, 9],
        "area": [0.01, 1000.0] * 4,
        "level": [0.0, 1.0] * 4,
    }
)
``` 

What many people might find confusing here is why the node IDs are repeated so often.
I also notice that the documentation (in Usage) doesn't mention what these values are, namely the the points for a piecewise linear function. I'll open a separate issue.

I've searched the docs, and it doesn't seem to be explained.

**Why**
It should be clear what the fundamental tabular input form is for Ribasim, since we use it almost everywhere.

**How**
I would suggest adding a section at the start, maybe here: 
https://deltares.github.io/Ribasim/core/usage.html#sec-geopackage

Explaining what long tables are versus wide tables. See e.g.: https://stackoverflow.com/questions/16026226/mysql-long-table-vs-wide-table
Or just google it to find a number of articles.

**Comment by SnippenE** [comment]
Solved by https://github.com/Deltares/Ribasim/pull/1110
