### ISSUE TITLE
Documentation: clarify that Ribasim uses piecewise linear interpolation in many places

### ISSUE THREAD

**Issue by Huite** [Deltares/Ribasim#1152]
**What**

Similarly to #1151, the example shows this table:

```python
profile = pd.DataFrame(
    data={
        "node_id": [1, 1, 3, 3, 6, 6, 9, 9],
        "area": [0.01, 1000.0] * 4,
        "level": [0.0, 1.0] * 4,
    }
)
```

It is not clear that the area and level values form a piecewise linear function. Nor it is explained what happens when values go beyond the first or last value. 

**Why**
It should be clear what the input means.

**How**
Similar to #1151, I would suggest adding a general bit of documentation clarifying the use of piecewise linear functions and how they are represented in tabular form.

Ideally including a picture, e.g. something like this:

![image](https://github.com/Deltares/Ribasim/assets/13662783/bb28caf2-2bdc-42e6-bfb1-3ae8016ea318)

Linked to #1623

**Comment by SouthEndMusic** [comment]
The scope of this issue isn't entirely clear. One thing to mention is that @Fati-Mon is working on guidance documentation in which she includes an elaborate description of basin profiles. But of course we have linear interpolation in many places in the code, and edge cases are not treated the same everywhere. To me it would indeed make sense to have a central place about interpolation in the docs, as it is quite an important part of the core. We could reference from both the node reference docs and the examples to the new interpolation documentation page.

It might make sense to migrate the basin description from @Fati-Mon  to there as well at some point, but let's keep these things separate for now.
