### ISSUE TITLE
installing ribasim (long paths)

### ISSUE THREAD

**Issue by JaccoHoogewoud** [Deltares/Ribasim#1153]
installing ribasim gives this complain:

![image](https://github.com/Deltares/Ribasim/assets/57228568/4f95e0b3-8825-45a0-a1cb-582fa14045bf)

not everybody can install in the root, maybe something can be done about this...?
regards!

**Comment by visr** [comment]
Hi @JaccoHoogewoud!

This is indeed not great. The full path is `ribasim_cli\share\julia\artifacts\fdff308295487f361ef6e8dc2d27f5abe8a6eee9\mingw64\lib\gcc\x86_64-w64-mingw32\8.1.0\include\c++\ext\pb_ds\detail\bin_search_tree_\constructors_destructor_fn_imps.hpp`

I wonder why `mingw64` gets included in the artifacts. I think this wasn't there before. It is 400 MB, the largest artifact together with MKL. If I remove it manually my simulations still run.

So I think it is safe to press "Skip", but we have to check why this is there and how we can remove it best.

**Comment by JaccoHoogewoud** [comment]
Thx @visr!
