### ISSUE TITLE
example model (created in python) does not work...

### ISSUE THREAD

**Issue by JaccoHoogewoud** [Deltares/Ribasim#1154]
Hi!

I made the example model.
the model.plot() of the steady state model looked the same and did run (I guess, don't know where to find the output, but no errors in the result/logfile)

- it would be nice to have some idea of where ribasim stores it's results and what output to expect in the results-dir.
- I had a look at the TOML's but found no reference to the database.gpkg.... meaning I can not have two models/versions in the same dir?
But perhaps I overlooked something :)

Kind regards!

**Comment by visr** [comment]
> it would be nice to have some idea of where ribasim stores it's results and what output to expect in the results-dir.

The TOML has a required keyword `results_dir = "results"`. This is the directory where all results are stored. Did you find the logfile there but no .arrow files?

> I had a look at the TOML's but found no reference to the database.gpkg.... meaning I can not have two models/versions in the same dir?

The filename `database.gpkg` is fixed, but the location is set in the TOML `input_dir = "."`. So you can have two models in the same directory by controlling the `input_dir`. Though I generally prefer to keep 1 model per directory.

https://deltares.github.io/Ribasim/core/usage.html#configuration-file
https://deltares.github.io/Ribasim/core/usage.html#results

**Comment by JaccoHoogewoud** [comment]
I think it would be convenient to have the toml refer toe a name.gpkg instead of a directory, it would make the toml more self explaining as well. One can see more clearly what goes in the model. But I cannot oversee all consequences and just start with ribasim.... so I'll just take it as it is :)

I took the python example as a "tutorial", and from that perspective I missed some things, like what output to expect. (my steady state model didn't produce an arrow file, but did produce a log file... so at that time i didn't know if this was "right"or "wrong"...

I'm not complaining though, it's just feedback! It's free software and I am just playing with it.

**Comment by visr** [comment]
We appreciate all feedback, first impressions teach us a lot.

> my steady state model didn't produce an arrow file, but did produce a log file

If there are no arrow files then there should be an error in the log file, and also in the terminal. If there isn't, we'd like to see the model to fix that.

> it would be convenient to have the toml refer toe a name.gpkg instead of a directory

This used to be the case, but after a discussion we went for explicit input and result directories and implicit files in those directories. There can be many input and output files, and having to specify them all will be quite verbose.

> python example as a "tutorial", and from that perspective I missed some things

Right now it is really just a Python example. I agree that having a separate tutorial or quick start guide that stands by itself would be valuable. This probably makes sense after this lands: https://github.com/Deltares/Ribasim/pull/1110. Then the Python examples would also be much more self-explanatory.

**Comment by visr** [comment]
Closing this since I think there are no actions left anymore that aren't covered in linked issues.
