### ISSUE TITLE
Ribasim API tests are failing on Linux

### ISSUE THREAD

**Issue by Hofer-Julian** [Deltares/Ribasim#1157]
The Ribasim API Linux tests are failing on TeamCity

Investigate:
- If it fails locally as well
- If the Julia update to 1.10.1 is to blame (https://github.com/Deltares/Ribasim/issues/1144)
- If the move to GitHub Enterprise is to blame

**Comment by visr** [comment]
I guess we can close this for now with #1167 by going back to Julia 1.10.0. We don't know exactly what causes this, so we may run into it again later. But we don't have anything to go on, it is just a segfault.
