### ISSUE TITLE
Create example models using python in core test suite

### ISSUE THREAD

**Issue by visr** [Deltares/Ribasim#116]
Right now https://github.com/Deltares/Ribasim/blob/main/core/test/basin.jl runs pre-prepared models that it downloads in runtests.jl. This creates an extra step when changing things. Preferably we run the python code before running the tests.

**Comment by Hofer-Julian** [comment]
Yeah, that is not correct

**Comment by visr** [comment]
Let's keep this open after #149 so we can look into further improvements later, meaning the PythonCall solution mentioned in https://github.com/Deltares/Ribasim/pull/149#issue-1654524866.

**Comment by visr** [comment]
Closed in favor of #244
