### ISSUE TITLE
Simultaneous condition changes are not handled properly

### ISSUE THREAD

**Issue by SouthEndMusic** [Deltares/Ribasim#1162]
**What**
It has been noticed by modelers that when more than one condition changes at once this leads to wrong control actions, which should be resolved.

**How**
I am not quite sure, it would be nice if we had a MRE here. I don't know whether we can fix this in our code, the root finding and calling of affect functions (with the index if the condition that changed as input) is handled in `SciMLBase`. If the problem occurs because exactly the same condition is in the input multiple times, we should either disallow this or filter it out in the initialization in the Julia core.

**Comment by gijsber** [comment]
[polder_boezem_systeem_3_polders_Dis_control.zip](https://github.com/Deltares/Ribasim/files/14374258/polder_boezem_systeem_3_polders_Dis_control.zip)
Ter aanvulling op wat Sieuwe aangeeft: 

Als de startpeilen in de ‘polders’ 1cm hoger of lager worden gelegd, gaat de sturing over de hele simulatie goed met logische resultaten. Wij kunnen er rekening mee houden, maar het lijkt mij niet logisch om dat als eis te stellen…

Van: Stobbelaar, Sieuwe <[sieuwe.stobbelaar@sweco.nl](mailto:sieuwe.stobbelaar@sweco.nl)> 

Hallo Harm, Martijn, Peter en Bart,

Hierbij het script waar het om gaat. Het startpeil van de basins is gelijk aan het bovenpeil van een van de condities van een outlet. De control truth state die dan wordt laten zien is alsof het startpeil onder het bovenpeil zit. Ik denk dus dat hierdoor in dit voorbeeld het waterpeil stijgt, en dan nooit meer een grens tegenkomt.  Hierdoor blijft de outlet altijd aan staan. 

Groeten,
Sieuwe


________________________________________
Van: Nomden, Harm <[harm.nomden@sweco.nl](mailto:harm.nomden@sweco.nl)>
Verzonden: maandag 19 februari 2024 20:04
Aan: Martijn Visser <[Martijn.Visser@deltares.nl](mailto:Martijn.Visser@deltares.nl)>; Bart de Koning <[bart.dekoning@deltares.nl](mailto:bart.dekoning@deltares.nl)>; Peter Gijsbers <[Peter.Gijsbers@deltares.nl](mailto:Peter.Gijsbers@deltares.nl)>
CC: Stobbelaar, Sieuwe <[sieuwe.stobbelaar@sweco.nl](mailto:sieuwe.stobbelaar@sweco.nl)>
Onderwerp: FW: issue_waterafvoer_wateraanvoer_20231205.pptx 
 
Dag Martijn/Peter/Bart,
 
Sieuwe onze stagiair (cc) had gekeken naar verschillende cases en de benodigde sturing met wateraanvoer/waterafvoer. 
 
Het lijkt erop dat Sieuwe eruit komt (na diverse omwegen), alleen reageert de modelberekening niet zoals verwacht als de startpeilen gelijk zijn aan het bovenpeil of onderpeil.  Enige ervaring hiermee of verklaring hiervoor? 
 
Opschonen van de code voor een testcase kost even tijd, maar kan Sieuwe mogelijk doen. Misschien dat jullie zo direct al weten wat het probleem kan zijn.
 
Groeten, Harm

**Comment by SouthEndMusic** [comment]
This issue is only relevant if we keep supporting condition root finding in stead of checking the conditions at every timestep.

**Comment by visr** [comment]
Closing, since with #455 simultaneous condition changes are what we're all about now.
