### ISSUE TITLE
Add `ribasim_version` to TOML

### ISSUE THREAD

**Issue by visr** [Deltares/Ribasim#1178]
**Why**
Ribasim models are created for a specific Ribasim version. If you receive a model, you don't know what Ribasim version it targets. If you have results then you could take it out of the Arrow metadata using https://github.com/Deltares/Ribasim/pull/1145, but if you only have input there is no way of knowing this.

In the future, we could possibly start using this information to help migrating across breaking changes, but implementing that is out of scope for this issue. Similarly, we could start throwing warnings or even errors in the core if the version of the CLI does not match this `ribasim_version`.

**How**
If a model is written with Ribasim Python we can easily add this information automatically. We could do this as a top level key `ribasim_version = "2024.2.0"`. One open question is whether to make this a required key, making it a breaking change. I'm leaning toward yes, because not knowing this information makes hard to give clear error messages in some cases.

**Comment by Hofer-Julian** [comment]
The idea sounds good to me.

> In the future, we could possibly start using this information to help migrating across breaking changes,

That's a different issue, but I think migrating across breaking changes should be done by Ribasim Python

> we could start throwing warnings or even errors in the core if the version of the CLI does not match this ribasim_version.

I think a warning fits well here

>  One open question is whether to make this a required key, making it a breaking change. I'm leaning toward yes, because not knowing this information makes hard to give clear error messages in some cases.

Agreed

**Comment by Huite** [comment]
Does it make sense to add a metadata label to the geopackage as well? Easiest way to do is via a single row table, I reckon.

The TOML file is just a reference, in which you e.g. control starttime and endtime as well. I wouldn't be surprised that people re-use their geopackage input, but make a TOML copy with e.g. different time domains.

**Comment by visr** [comment]
> Ideally, you'd also label the arrow tables

Already done for the results since #1145.

> Does it make sense to add a metadata label to the geopackage as well?

I think adding it to the TOML makes sense users should be able to easily read it. You receive some model, want to run it, look at the TOML file to find which Ribasim version you need to download, and run it.

We could also automatically add it to the other input files, but then it becomes more complicated. Like what do we do if there are multiple different versions. A single source of truth seems preferable.

**Comment by Huite** [comment]
I agree that user readability is the most important thing, but the initial phrasing didn't mention that so explicitly.

With Arrow I mean the input files as well.

> Like what do we do if there are multiple different versions. A single source of truth seems preferable.

The whole point of these labels is to communicate the truth: if your TOML is version A, your geopackage is version B, and your arrow input is version C, it communicates that they may not be compatible.
I mean, it's not that hard to check whether `toml_version == gpkg_version == arrow_version == expected_version` is true or not and raise a warning if it's not the case.

**Comment by visr** [comment]
Yeah that is true, but I also don't want the GeoPackage and Arrow files to be too special. Programs other than Ribasim Python should be able to easily create these files without having to know about some otherwise invisible metadata.

If having different input files with different versions does turn out to cause real problems, we could always still add it.

**Comment by Huite** [comment]
> Programs other than Ribasim Python should be able to easily create these files

I don't think they need to be invisible? If we include it a spec somewhere, I think it would be fine. We chose common open formats, so at least people don't have to struggle themselves with the binary representation (*cough-IDF-cough*). The majority of work would be making sure all the tables are present, with proper column names, etc. For e.g. arrow, the metadata is a standard feature; a geopackage is a many-tabled thing anyway. 

> If having different input files with different versions does turn out to cause real problems, we could always still add it.

Agreed.
