### ISSUE TITLE
Delete alternative objective functions in allocation

### ISSUE THREAD

**Issue by Jingru923** [Deltares/Ribasim#1191]
**What**
In allocation, solving the optimization problem means finding out the best solution that narrowing the gap between the user demand and the allocated demand. In the optimization problem, there are four type of object functions, we would like to have only linear absolute

**Why**
We would like our code to be simpler and more maintainable. @visr had a discussion with Ailbhe and the conclusion is that we can just keep the linear absolute object functions.

**How**
Disable the option for object function. Delete all the relevant part of the other 3 object function.

**Comment by visr** [comment]
Reopening since #1193 only disabled other options, we still need to delete the code and possibly refactor a bit to simplify code now that we don't support multiple choices.
