### ISSUE TITLE
Link to developer documentation does not work

### ISSUE THREAD

**Issue by Fati-Mon** [Deltares/Ribasim#1195]
**What**
The link to the developers doc ( [https://deltares.github.io/Ribasim/python/developer.html](url) ) mentioned in [https://github.com/Deltares/Ribasim/blob/main/python/ribasim_testmodels/README.md](url) does not seem to work. 

**How**
Might have been adjusted. Do you mean: [https://deltares.github.io/Ribasim/contribute/](url) ?
**Additional context**

![image](https://github.com/Deltares/Ribasim/assets/150450583/718a8dd0-8009-4fa7-88af-010a5c4a9079)

**Comment by visr** [comment]
Thanks for reporting, fixed in e8e72023018b30e2159873670f17b0320f7658a9.
This is the current link: https://deltares.github.io/Ribasim/contribute/
