### ISSUE TITLE
Move objective from `allocation_optim.jl` to `allocation_init.jl` (refactor)

### ISSUE THREAD

**Issue by SouthEndMusic** [Deltares/Ribasim#1196]
Currently the objective function for optimization problems in allocation is generated from scratch each time with the function `set_objective_priority!`. 

https://github.com/Deltares/Ribasim/blob/4c04d05cfabc850a6322fa8cf768a5ef0015d24f/core/src/allocation_optim.jl#L621-L626

As the comment at the function call indicates, this is now only done because the quadratic objective functions do not support modification. As we are getting rid of these, we could move to only initializing the objecting function once and modifying coefficients when needed. This I think makes the code cleaner and maybe for large models also more performant.

**Comment by visr** [comment]
I think this is only still relevant if we decide to go for #1494.

**Comment by SouthEndMusic** [comment]
We cannot do this, because we stick to a quadratic objective function which can not be done in initialization, can only be done every iteration
