### ISSUE TITLE
Create reusable workflow out of pixi update workflow

### ISSUE THREAD

**Issue by Hofer-Julian** [Deltares/Ribasim#1210]
The pixi update workflow is currently duplicated across Ribasim, iMOD Documentation and hydroMT.
Other people seem to be interested as well: https://github.com/prefix-dev/pixi/issues/909 (now https://github.com/prefix-dev/pixi/discussions/910)
It has been brought to my attention, that reusable workflows exist that could avoid that duplication.

**Comment by visr** [comment]
Closing as we are currently using the documented workflow: https://pixi.sh/latest/advanced/updates_github_actions/
