### ISSUE TITLE
Cannot plot model with edge geometries longer than a single line segment

### ISSUE THREAD

**Issue by visr** [Deltares/Ribasim#1218]
We support LineString and MultiLineString geometries for edges. But cannot plot model with edge geometries longer than a single line segment in Ribasim Python.

![image](https://github.com/Deltares/Ribasim/assets/4471859/873e5cb5-1771-4e94-847c-eaaed53c103e)

There are some similar limitations regarding edge geometries described in #352.

**Comment by Huite** [comment]
In this case, we require `index=True` in the shapely.get_coordinates call I think.

Then some indexing trickery to setup a matplotlib LineCollection.
