### ISSUE TITLE
Add support for transient `UserDemand` return factor

### ISSUE THREAD

**Issue by SouthEndMusic** [Deltares/Ribasim#1230]
@Fati-Mon requested for one of her models that we support transient `UserDemand` return flow. 

This is currently not supported, but it is already possible to put it in the `UserDemand \ time` table. https://github.com/Deltares/Ribasim/issues/1229 is for avoiding confusion about this for `time` tables in general.

**Comment by SnippenE** [comment]
from planning session 16-5-2024: check if a flag is implemented in code.

**Comment by Fati-Mon** [comment]
@Jingru923 how do you define the return flow over time?

I have this now:
```python
# DEMAND (irrigation)
model.user_demand.add(
    Node(6, Point(-1.5, 1.0), name='IrrA'),
    [user_demand.Time(
        demand=[0.0, 0.0, 10, 12, 12, 0.0],
        return_factor=[0.0, 0.0, 0.2, 0.5, 0.5, 0.0],
        min_level=0,
        priority=1,
        time=[starttime, "2022-03-31", "2022-04-01", "2022-07-01", "2022-09-30", "2022-10-01"]
        )
    ]
)
```
When it irrigates 10 return 20% and when it irrigates 12 return 50%
But return over time remains zero.

**Comment by Jingru923** [comment]
Hi @Fati-Mon the code looks correct to me. But we will have a look.

**Comment by visr** [comment]
@Fati-Mon which version are you running with, what is the output of `ribasim --version`?
