### ISSUE TITLE
Infer edge type in add API

### ISSUE THREAD

**Issue by visr** [Deltares/Ribasim#1261]
Right now we always need to specify the edge type:

https://github.com/Deltares/Ribasim/blob/b5058d051817f6e0bdd8f07e68ec9a3428a0af4f/python/ribasim_testmodels/ribasim_testmodels/basic.py#L143

But QGIS infers it automatically. If it comes from DiscreteControl or PidControl, it is always a control edge, otherwise a flow edge:

https://github.com/Deltares/Ribasim/blob/b5058d051817f6e0bdd8f07e68ec9a3428a0af4f/ribasim_qgis/core/topology.py#L91-L95

I suppose we could do this in Ribasim Python as well.

**Comment by Hofer-Julian** [comment]
As discussed with @visr, we will remove the `edge_type` parameter altogether.

**Comment by Huite** [comment]
Isn't it needed for visualization?

**Comment by Hofer-Julian** [comment]
> Isn't it needed for visualization?

Shouldn't we be able to infer it then as well?

**Comment by Huite** [comment]
It's more complicated in QGIS. QGIS takes the values of one column. To make it depend on both from_node_type and to_node_type you will probably need to set an expression:

![image](https://github.com/Deltares/Ribasim/assets/13662783/4194e09c-98c2-4b4c-9e8c-75e46b08b65b)

Or create a virtual field:

![image](https://github.com/Deltares/Ribasim/assets/13662783/9f7c63ce-398f-4337-ad24-82054538f593)
