### ISSUE TITLE
Allocation without simulation

### ISSUE THREAD

**Issue by visr** [Deltares/Ribasim#1263]
**What**
We support running a physical simulation without using allocation. But not the other way around.

**Why**
For planning studies having a physical simulation is not always needed. At the same time this physical layers requires many parameters. As long as the allocation timestep is large enough, and the constrains to the optimization problem accurate enough, it may be feasible to use only allocation.

Such a mode would make Ribasim much more comparable to other water resource allocation models, and probably easier to use in scenarios where detailed information is not available or not relevant.

**Comment by SouthEndMusic** [comment]
Interesting, this would mean getting around all the places where allocation requires input from the physical layer.

**Comment by Fati-Mon** [comment]
Is it possible to model a simulation with no storage (no basins)? I am now making a very simplified model with two inflows going straight to a terminal. See figure:
![image](https://github.com/Deltares/Ribasim/assets/150450583/b699c714-ce41-47d2-993a-4336caeaa19e)

However, this doesn't seem to be possible (yet) as Ribasim requires basin(s) in between to be able to run the model. See example of python script below:

```python
import subprocess  # for running the model
import shutil
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from ribasim import Allocation, Model, Node
from ribasim.nodes import (
    flow_boundary,
    terminal
)
from shapely.geometry import Point

base_dir = Path("c:/Ribasim9")
model_dir = base_dir / "Virgin"
flows_path = model_dir / "input/ACTINFLW.csv"

starttime = "2023-01-01"
endtime = "2024-01-01"
model = Model(
    starttime=starttime,
    endtime=endtime,
    crs="EPSG:4326",
)

flows = pd.read_csv(flows_path, sep=";")

model.flow_boundary.add(
    Node(1, Point(0.0, 0.0), name='Main'), 
    [flow_boundary.Time(time=flows.time, flow_rate=flows.main, #name="Main"
    )]
)

model.flow_boundary.add(
    Node(2, Point(-3.0, 0.0), name='Minor'), 
    [flow_boundary.Time(time=flows.time, flow_rate=flows.minor, #name="Main"
    )]
)


model.terminal.add(Node(3, Point(-1.5, -3.0), name="Terminal"))

model.edge.add(model.flow_boundary[1], model.terminal[3])
model.edge.add(model.flow_boundary[2], model.terminal[3])

model.plot()

datadir = base_dir/ "data"
toml_path = datadir / "basic/ribasim.toml"
model.write(toml_path)
rib_path = base_dir / "ribasim_windows/ribasim.exe"

subprocess.run([rib_path, toml_path], check=True)

```
