### ISSUE TITLE
Export Basin, Terminal, PidControl, LevelBoundary, etc. etc.?

### ISSUE THREAD

**Issue by Huite** [Deltares/Ribasim#1280]
I see Node has been added to the exports: https://github.com/Deltares/Ribasim/pull/1237

But this no longer works:
```python
    ribasim_bucket_model.basin = ribasim.Basin(
        static=ribasim_bucket_model.basin.static,
        profile=ribasim_bucket_model.basin.profile,
    )
```

Since now it's found under `ribasim.config.Basin`.

I think it's okay to lift them up by one namespace? Or does it make the tab completion too confusing for the most common use?

**Comment by visr** [comment]
What are you trying to do here? Trying to go around the add API to construct models directly from already assembled dataframes? Will be interesting for the migration path.

For the add API the node types are also neatly stored in separate modules under ribasim.nodes.

**Comment by visr** [comment]
I think we still need to try out this use case a bit to see what is already possible or what modifications may help. But hopefully not maintaining two completely separate APIs.

**Comment by visr** [comment]
Closing, for config it doesn't make too much sense since users wouldn't normally touch them, and for `ribasim.nodes` it feels cleaner to have them separated from the rest.
