### ISSUE TITLE
`LevelBoundary` connected to `ManningResistance` can lead to negative depths

### ISSUE THREAD

**Issue by SouthEndMusic** [Deltares/Ribasim#1299]
In `formulate_flow!` for `ManningResistance` nodes, the depths upstream and downstream of the `ManningResistance` nodes are computed, which is the difference between the local level and bottom. In case one of the connected nodes is a `LevelBoundary` node, no bottom is available, so the bottom from the node on the other side of the `ManningResistance` node is used.

This can lead to negative levels and eventually can give a domain error in computing `R_h^(2 / 3)` which requires a positive input. To resolve this, I suggest to give `LevelBoundary` an optional `bottom` parameter which is validated to be mandatory if connected to a `ManningResistance Node`. It would also be nice if the bottom is validated to be less than or equal to the lowest level in the `LevelBoundary` input.

**Comment by visr** [comment]
@harm-nomden-sweco this seems to be the problem. Perhaps it's best if you use a LinearResistance to connect LevelBoundary instead. @SouthEndMusic I suppose that could be the other solution, to only allow Manning between Basins.

**Comment by SouthEndMusic** [comment]
> @SouthEndMusic I suppose that could be the other solution, to only allow Manning between Basins.

@visr It depends on whether you want to have the schematization freedom to have a `LevelDemand` connected to a `ManningResistance` at the cost of some added complexity, I think you can judge that better.

**Comment by gijsber** [comment]
@SouthEndMusic I assume you mean `LevelBoundary`instead of `LevelDemand`.

I think I agree with @visr , if you go from a `Basin` to a `LevelBoundary` we can allow `LinearResistance` and skip the option with `ManningResistance`.

**Comment by SouthEndMusic** [comment]
> @SouthEndMusic I assume you mean `LevelBoundary`instead of `LevelDemand`.

Ah yes, I caught myself making that mistake several times, this one slipped by :')
