### ISSUE TITLE
Node ID numbering changes mean imod-qgis timeseries plot doesn't fetch the right data

### ISSUE THREAD

**Issue by Huite** [Deltares/Ribasim#1306]
Previously, the node feature ID was equal to the `node_id`. This meant that we could directly use the feature id to locate timeseries in the result dataframes.

Because `node_id` is no identical to the feature ID, the timeseries plot will either not find the results (because the FID doesn't exists as a node_id), or it will show the wrong timeseries.

It only goes well if your model node_id matches the feature ID as before.

**Comment by visr** [comment]
Do you see this going wrong?

I thought the code was already adopted for this:
https://github.com/Deltares/Ribasim/blob/f43010bb1b0521a27fcda9d93f60ac4d364bfb45/ribasim_qgis/widgets/dataset_widget.py#L321-L329

**Comment by Huite** [comment]
I think you're referring to something else.

I mean these lines, essentially:

https://github.com/Deltares/imod-qgis/blob/e5f128c55ccf911289b8189d8bbf3411efa71569/imodqgis/timeseries/timeseries_widget.py#L569

https://github.com/Deltares/imod-qgis/blob/e5f128c55ccf911289b8189d8bbf3411efa71569/imodqgis/timeseries/timeseries_widget.py#L557

I don't think the keys match the feature IDs. I.e. we're creating a mapping of node_id => dataframe. Then we're searching for feature id's, which aren't node ID's.

The reason I mention this is because I was getting weird selections.

**Comment by visr** [comment]
Ok right, so in imod-qgis there are the implicit assumptions that `node_id` == `fid` for basin.arrow and `edge_id` == `fid` for flow.arrow. The latter is currently correct, though see #1310. The former is incorrect.

**Comment by visr** [comment]
Yeah it's quite bad. How about https://github.com/Deltares/Ribasim/pull/1316 as a temporary fix?

**Comment by Huite** [comment]
Fixed by this: https://github.com/Deltares/imod-qgis/pull/79
