### ISSUE TITLE
Allow more configuration re-use with TeamCity templates

### ISSUE THREAD

**Issue by Hofer-Julian** [Deltares/Ribasim#1313]
TeamCity allows to creating templates: https://www.jetbrains.com/help/teamcity/build-configuration-template.html#Creating+build+configuration+template

This is useful in order to share common config between build configurations.
One example of such a template can be found here: https://dpcbuild.deltares.nl/admin/editBuild.html?id=template:Ribasim_GitHubIntegrationTemplate

Ideas where this could be helpful:

- [x] Share agent requirements for all agents that require Linux
- [x] Share agent requirements for all agents that require Windows
- [x] Use the GitHubIntegrationTemplate in all places where it is applicable

**Comment by Hofer-Julian** [comment]
For Linux it would be good to specify the environment like this:

![image](https://github.com/Deltares/Ribasim/assets/30049909/57538ab8-bba2-42b0-b1a4-7fb94437aedf)

For Windows I would do it like this:

![image](https://github.com/Deltares/Ribasim/assets/30049909/0afa61b1-7cc8-4dc3-af4d-74584f257a53)

These are the docs for the TeamCity build configuration templates: https://www.jetbrains.com/help/teamcity/build-configuration-template.html

**Comment by Jingru923** [comment]
Fixes #1313

Now there is a template for Linux agents and one for Windows agents. The 4 Linux pipelines, `Make QGIS plugin` and `Make Github Release` are attached to the Linux template and the 4 Windows pipelines are attached to the Windows template.
