### ISSUE TITLE
Simplify Jacobian sparsity construction

### ISSUE THREAD

**Issue by SouthEndMusic** [Deltares/Ribasim#1317]
The `tki_zutphen_berkel` model by @harm-nomden-sweco runs into some convergence issues, which can be partially be solved by setting `sparse = false`. This indicates that there is a problem in `sparsity.jl`. Some investigation of the jacobian from this model might point out where the problem is.

_Edit: simplifying the Jacobian sparsity construction might be the way to go, see [this comment](https://github.com/Deltares/Ribasim/issues/1317#issuecomment-2034058769)._

**Comment by SouthEndMusic** [comment]
I had a look into this. When comparing the basin storages for `sparse = true` and `sparse = false` there are particular basins with notable differences:

![comparse_sparse_dense_Zupthen](https://github.com/Deltares/Ribasim/assets/74617371/7c7992af-76b9-4c00-801e-d70b883c2712)

However, I have not been able to deduce the cause of this.

**Comment by SouthEndMusic** [comment]
One thing that does not solve this problem but might make some models a bit more stable: In `sparsity.jl`, `Outlet` belongs in the category of `LinearResistance` and `ManningResistance`. 

The sparsity structure now is quite highly optimized, which requires maintenance while we might not actually need it. It would make the code much simpler if we just say that any basin depends on itself and the basins it is connected to (possibly via `FractionalFlow`). This introduces some false positives but I don't think the performance drop will be significant. Extra care is still required for continuous control.

**Comment by visr** [comment]
Yeah the simpler approach sounds easier to maintain.
