### ISSUE TITLE
administration of allocation results is incorrect

### ISSUE THREAD

**Issue by JvanHouwelingen** [Deltares/Ribasim#1321]
The administration of the allocation results (demand, allocation and realized) within the allocation.arrow file is incorrect. 
In my model I have multiple UserDemand nodes, with either priority 1 or 2. Within the attached model there is just one UserDemand active with a high demand of priority 1. The other UserDemands have a zero demand with priority 2. 
In the .arrow file the 'demand' of the active UserDemand is 0, while it should be 25. The 'allocation' results seems to be right (value of 25). At 'realized' values of 25 are present for both priority 1 and 2, while this should be just a value 25 at priority 1. I think the administration is a bit mixed up. 
[Maas - Bommelerwaard userdemand - HOUJ2 v2.zip](https://github.com/Deltares/Ribasim/files/14755690/Maas.-.Bommelerwaard.userdemand.-.HOUJ2.v2.zip)

**Comment by SouthEndMusic** [comment]
Hi Josje, I'm looking into this now. One thing I can already mention is that setting the demand to 0.0 for a certain node and priority is equivalent to not specifying this demand at all.
