### ISSUE TITLE
Add main network inlet penalty when collecting subnetwork demands

### ISSUE THREAD

**Issue by SouthEndMusic** [Deltares/Ribasim#1327]
I've noticed that collecting subnetwork demands is not fully deterministic for the subnetwork with ID 7 in the `main_network_with_subnetworks` model. My first guess as to why this is is that because this subnetwork contains a loop, there are multiple ways to obtain the same objective function value, which differ in how much water they require from the main network inlet. To favor the one with the smallest requirement, a small penalty can be added to the objective function for flows coming from the main network. I'm quite sure that as long as the weight of this penalty is smaller than 1, all demands within the subnetwork will still be properly collected.

This makes the optimization more predictable and explainable.

**Comment by gijsber** [comment]
sounds good to me

**Comment by SouthEndMusic** [comment]
Superseded by https://github.com/Deltares/Ribasim/issues/1504.
