### ISSUE TITLE
Control action on downstream flow condition

### ISSUE THREAD

**Issue by gijsber** [Deltares/Ribasim#1340]
**What**
a users wants to specify a control action on some upstream structure based on a outflow condition on a (far away) downstream basin

**Why**
To ensure flushing in some downstream section of a network, 

**How**
List to the outflow of a basin node or an edge flow.
To prevent instability, we might need to have additional validation rules that there should be at least one or more basins between the controlled structure an the monitoring point

**Comment by SouthEndMusic** [comment]
There should be no direct dependency of the listened flow on the controlled node. This means the corresponding edge should not be direct in- or outflow of the controlled node, and also not with a fractional flow node in between (fractional flow always complicates validation like this).

**Comment by gijsber** [comment]
Agree, that's why I think we should have one or multiple basins inbetween and validate the network for that restriction

**Comment by SouthEndMusic** [comment]
Hmm having a basin in between might be effectively what that means yes

**Comment by SouthEndMusic** [comment]
> Agree, that's why I think we should have one or multiple basins inbetween and validate the network for that restriction

From the perspective of the code, it is easier to check that listened edges are not directly (or via fractional flow) connected to affected nodes than to find and check everything that lies between the listened edge and the affected nodes
