### ISSUE TITLE
Add result state file

### ISSUE THREAD

**Issue by visr** [Deltares/Ribasim#1358]
If a user wants to continue a simulation at time t based on the results of a previous simulation that ended at time t, they need to use a `Basin / state` table with the final storages from the previous simulation. We should add an output file `basin_state.arrow` that contains this information.

This can then also be used in Delft-FEWS for this purpose.

If PidControl nodes are also present they should also carry over state, but this could be added later, since we don't support setting this state as input either at the moment.

**Comment by gijsber** [comment]
Hi @visr , if this is implemented we should document it. such that externals (such as Micha (Hydrologic)) can use it
