### ISSUE TITLE
Use a dummy CRS instead of the Dutch CRS in ribasim testmodels

### ISSUE THREAD

**Issue by evetion** [Deltares/Ribasim#1362]
#1339 added setting crs to our models, and made it mandatory to do so. Now all of our testmodels have EPSG:28992 set (the Dutch crs), but points are actually set with local coordinates like point(0,0) (https://github.com/Deltares/Ribasim/blob/main/python/ribasim_testmodels/ribasim_testmodels/allocation.py#L36).

Arguably, we need to set a dummy engineering crs for these models, like:

```python
"""ENGCRS["Dummy CRS for testing",
    EDATUM["Unknown engineering datum"],
    CS[Cartesian,2],
        AXIS["X",unspecified,
            ORDER[1],
            LENGTHUNIT["unknown",0]],
        AXIS["Y",unspecified,
            ORDER[2],
            LENGTHUNIT["unknown",0]]]"""
```

#nitpick

**Comment by visr** [comment]
There is no EPSG for this? I feel like having such a long code in the TOML that is often used as example is worse.
They aren't really unknown either, they are known to be some imaginary cartesian coordinate system.

**Comment by evetion** [comment]
> There is no EPSG for this? I feel like having such a long code in the TOML that is often used as example is worse. They aren't really unknown either, they are known to be some imaginary cartesian coordinate system.

That's the engineering part of the datum, cartesian (x, y) in an imaginery space somewhere. There's no EPSG code for it, apart from some deprecated example ones (EPSG:5806 comes to mind)

I agree it's ugly, but I would prefer it over being wrong 😄. And this is a logical extension from the crs PR, or would you want to limit it to EPSG codes only?

**Comment by visr** [comment]
Let's revisit when a suitable dummy EPSG is added ;)
