### ISSUE TITLE
Inconsistent CRS state in Ribasim Python

### ISSUE THREAD

**Issue by Hofer-Julian** [Deltares/Ribasim#1364]
Even though we require `crs` during `Model` construction, we don't use it immediately.
It is only set when calling `set_crs`, which we do for example during saving:
https://github.com/Deltares/Ribasim/blob/a5ee40fa813674f40d43570e91d078b8c3ef46d4/python/ribasim/ribasim/model.py#L163-L164

We could pass `crs` to all member variables and use it already when adding nodes.

**Comment by visr** [comment]
Fixed by #1810
