### ISSUE TITLE
Run allocation at t = 0

### ISSUE THREAD

**Issue by visr** [Deltares/Ribasim#1389]
Currently allocation doesn't run at t = 0. This is done because flow on the source edges is still unknown. This means that effectively there is a free-for-all situation for the allocation interval. It would be better to special case t = 0, to run the RHS once to get a first estimate for the instantaneous flows at t = 0, and then run allocation with that.

**Comment by SouthEndMusic** [comment]
With https://github.com/Deltares/Ribasim/pull/1427 it is required to set these initial instantaneous flows as the mean flows.
