### ISSUE TITLE
 Allow more configuration re-use with TeamCity templates for iMOD Coupler

### ISSUE THREAD

**Issue by Hofer-Julian** [Deltares/Ribasim#1398]
It is done with Ribasim, now let's do the same with iMOD Coupler

See also https://github.com/Deltares/Ribasim/issues/1313

**Comment by Jingru923** [comment]
After discussed with @rleander , he will first make same templates as the Ribasim ones for coupler, and we will see what happen later. Some vison on what we want in the templates is needed.
