### ISSUE TITLE
Metaissue: Global demand and allocation callback (nested allocation)

### ISSUE THREAD

**Issue by visr** [Deltares/Ribasim#14]
Aggregate the demands of the districts and allocate the available water according to defined priorities.

Define bifurcation mechanisms that don't need explicit tables for each possible split.

Define use cases (including bidirectional flow channels).

**Comment by gijsber** [comment]
try to make a decision layer (on top of the physical-oriented control layer) for the prioritization of abstractions. This layer would assess what abstactions could fit given the physical situation and reduce those abstractions that have lowest priority. then those reduced abstractions are given to the physical/control layer

**Comment by gijsber** [comment]
Per timestep this would result in the following processes:



![Image](https://github.com/Deltares/Ribasim/assets/14976756/06fdf6b1-d3da-43f7-8505-ed12a4bee288)

**Comment by gijsber** [comment]
level control vs abstractions: how to manage priorities:


![Image](https://github.com/Deltares/Ribasim/assets/14976756/107f4c0b-3be6-4832-b444-998e63cab363)

Sldies can also be found on sharepoint: \DEL155 Oppervlaktewatermodule NHI - Documents\0. Deltares only\4_presentaties\achitecture_layer.pptx
