### ISSUE TITLE
Error on large water balance error

### ISSUE THREAD

**Issue by visr** [Deltares/Ribasim#1413]
**What**
If the water balance error exceeds a certain fraction, we want the simulation to stop with a clear error message.

**How**
We should probably add a solver option for this with a reasonable default fraction like 0.01.

**Additional context**
- #1406 is a similar error that we should also throw at runtime.
- #1367 calculated the water balance error for the results, after the simulation finished.
- #452 is relevant for pointing to the problematic nodes in an error message.

**Comment by evetion** [comment]
We could consider implementing a continuity tracer for this (which gives a fraction around 1 per basin?) as well during the run? 

Or did you plan on moving the logic in https://github.com/Deltares/Ribasim/pull/1367 to a callback?

**Comment by visr** [comment]
Yeah the latter.

**Comment by visr** [comment]
Done in #1819, in the function `check_water_balance_error`.
