### ISSUE TITLE
Allocation test failure on main

### ISSUE THREAD

**Issue by visr** [Deltares/Ribasim#1423]
This test failure shows up sometimes. Possibly since #1399.

```
No Captured Logs for test item "Allocation level control" at test\allocation_test.jl:308 on worker 7960
Error in testset "Allocation level control" on worker 7960:
Test Failed at D:\a\Ribasim\Ribasim\core\test\allocation_test.jl:364
  Expression: ≈(storage[stage_5], u_stage_5.(t[stage_5]), rtol = 0.0001)
   Evaluated: [1654.8209307353425, 1611.6209217322994, 1596.0102056697474] ≈ [1654.8209307353425, 1611.6209307353424, 1568.4209307353424] (rtol=0.0001)

Error in testset "Allocation level control" on worker 7960:
Test Failed at D:\a\Ribasim\Ribasim\core\test\allocation_test.jl:[372](https://github.com/Deltares/Ribasim/actions/runs/8802274133/job/24157582821#step:6:373)
  Expression: ≈(storage[stage_6], u_stage_6.(t[stage_6]), rtol = 0.0001)
   Evaluated: [1533.1275614894184, 1499.9856889683385, 1499.9856107363594, 1499.985610656249, 1499.985610653905, 1499.9856106538211, 1499.9856106538184, 1499.9856106538184, 1499.9856106538184, 1499.9856106538184, 1499.9856106538193] ≈ [1533.1275614894184, 1533.1275614894184, 1533.1275614894184, 1533.1275614894184, 1533.1275614894184, 1533.1275614894184, 1533.1275614894184, 1533.1275614894184, 1533.1275614894184, 1533.1275614894184, 1533.1275614894184] (rtol=0.0001)
```

In table form:

| evaluated   | expected    | difference |
| ----------- | ----------- | ---------- |
| 1654.820931 | 1654.820931 | 0          |
| 1611.620922 | 1611.620931 | \-9E-06    |
| 1596.010206 | 1568.420931 | 27.58927   |

and

| evaluated | expected | difference |
| --------- | -------- | ---------- |
| 1533.128  | 1533.128 | 0          |
| 1499.986  | 1533.128 | \-33.1419  |
| 1499.986  | 1533.128 | \-33.142   |
| 1499.986  | 1533.128 | \-33.142   |
| 1499.986  | 1533.128 | \-33.142   |
| 1499.986  | 1533.128 | \-33.142   |
| 1499.986  | 1533.128 | \-33.142   |
| 1499.986  | 1533.128 | \-33.142   |
| 1499.986  | 1533.128 | \-33.142   |
| 1499.986  | 1533.128 | \-33.142   |
| 1499.986  | 1533.128 | \-33.142   |

**Comment by SouthEndMusic** [comment]
This was probably solved with https://github.com/Deltares/Ribasim/commit/e84ae3a180136a394965a2de87ab9728883f868f, let's merge that separately.

**Comment by visr** [comment]
That makes sense, see #1424.
