### ISSUE TITLE
How to handle basins without a level demand in allocation

### ISSUE THREAD

**Issue by SouthEndMusic** [Deltares/Ribasim#1428]
Currently the allocation algorithm only takes local available water of basins (including their forcings) into account when these basins have a level demand. That is because the level demand defines when a basin is in a demand or a supply state. When the basin doesn't have a level demand, there is no reference for this. However, modellers probably still expect for instance that a large amount of precipitation on a basin is taken into account in allocation, even if that basin has no level demand. Should we actually implement something for this, or should we just thoroughly document that this is the behavior of basins in allocation?

@gijsber @visr

**Comment by visr** [comment]
I think the default behavior is ok, to not allow abstractions from Basins unless we know there is surplus water. I can imagine some Basins don't have a demand for low water levels, but can have a surplus. In this case we can attach a LevelDemand node with only a `max_level`.

Perhaps for that it is good to make both `min_level` and `max_level` optional, with defaults `-Inf` and `Inf`?

https://deltares.github.io/Ribasim/core/usage.html#sec-level_demand

**Comment by gijsber** [comment]
Proposal from Martijn is fine to me. If no LevelDemand is set, one can basically utilize all water from a basin in allocation.

**Comment by visr** [comment]
> If no LevelDemand is set, one can basically utilize all water from a basin in allocation.

My proposal was to not allow any use in that case. I feel like that behavior is safer against over abstraction. Modelers need to opt in to Basin sources. Then again, local precipitation should perhaps always be a source. Should any storage increase be a source, but not all storage?

Not sure what most modelers would expect here. I feel like it is quite an important choice.

**Comment by visr** [comment]
We discussed this together, and decided that the current behavior of not allowing Basin storage as a source by default is the conservative thing to do, and easy to explain. If modelers expect a particular Basin's storage to be used, they can attach a LevelDemand to indicate from which level it is considered surplus water. #1430 will help with this as well.
