### ISSUE TITLE
Let the solver integrate our flows

### ISSUE THREAD

**Issue by visr** [Deltares/Ribasim#1431]
We compute mean or total flows in several places, and do this manually in our parameters in for instance #1300.

@SouthEndMusic suggested that perhaps it would be less code and more accurate to add those "integrated flows [m3]" as a state to our solver, such that `du = flow [m3/s]`. We already have two types of state, one for the Basin volume, and the PID error. We can add more.

**Comment by SouthEndMusic** [comment]
Closed in favor of https://github.com/Deltares/Ribasim/issues/1473.
