### ISSUE TITLE
Improve `FractionalFlow` implementation in allocation

### ISSUE THREAD

**Issue by SouthEndMusic** [Deltares/Ribasim#1441]
https://github.com/Deltares/Ribasim/pull/1429 changes the implementation of `FractionalFlow` in allocation by giving every node that has fractional flow outneighbors a buffer for flow that is not directly used. This implementation is however not correct. Using buffers to let allocation stick to the `FractionalFlow` flow distribution can only work if there is a buffer for every `FractionalFlow` node. There is also the additional problem that flow from the buffer should take precedence over other sources, especially when collecting subnetwork demands.

**Comment by gijsber** [comment]
when removing fractionalflow this is not needed
