### ISSUE TITLE
Broken python plotting for models that have no height

### ISSUE THREAD

**Issue by SouthEndMusic** [Deltares/Ribasim#1463]
The plotting for some of our test models that are just a straight horizontal line looks pretty bad, for instance `two_basin`:

![two_basin](https://github.com/Deltares/Ribasim/assets/74617371/6dac4dc9-03a4-4860-881f-d66fb40aafdd)

Maybe the easiest fix is to compute the bounding square and make that the axes range, and maybe add some padding for the legend.

**Comment by visr** [comment]
I'd also be fine with just changing our test models to not be on a line, if that is easier.

**Comment by SouthEndMusic** [comment]
It's not that hard to set bounds on the aspect ratio, or does that not fix it?

**Comment by visr** [comment]
Haven't tried, that would be preferred if it does.
