### ISSUE TITLE
Add production test models to our testbench

### ISSUE THREAD

**Issue by evetion** [Deltares/Ribasim#1471]
Can be larger, external test models. Refine what we're testing in such models. For example, is it performance, backwards compatibility, etc?

**Comment by visr** [comment]
Is this not already covered by #1412 and #462?

**Comment by gijsber** [comment]
[AVG-test_Hydrologic.zip](https://github.com/user-attachments/files/16013843/AVG-test_Hydrologic.zip)


AVG-Model available on deltares.thegood.cloud

**Comment by gijsber** [comment]
report:
- if model code breaks running models
 -impact on results for changes in model code
- impact on performance for changes in model code

**Comment by Jingru923** [comment]
Issue #1412 is about building up a teshbench for one of real-world model. It has some overlap with this issue. So I combined the goal of both issue and merge them into one. The description of #1412 is now updated with the objects of both issues. Therefore, this issue can be closed.
