### ISSUE TITLE
Rethink Ribasim version number updates

### ISSUE THREAD

**Issue by evetion** [Deltares/Ribasim#1480]
> Also, shouldn't we bump the version number to 2024.9.0 directly after tagging 2024.8.0? To clarify it is a pre-release of 2024.9.0.

> The version number now exists in these places: https://github.com/Deltares/Ribasim/pull/1462

_Originally posted by @visr in https://github.com/Deltares/Ribasim/issues/1479#issuecomment-2117494771_

**Comment by visr** [comment]
Let's close this if it goes against the direction of the linked PR. I don't feel strongly about this, just thinking about the options.
