### ISSUE TITLE
Use `pixi update` in pixi v0.23

### ISSUE THREAD

**Issue by visr** [Deltares/Ribasim#1501]
Instead of removing and recreating it in https://github.com/Deltares/Ribasim/blob/72923fe334ab6b1651ac8c5b9e5164845ded1f26/.github/workflows/pixi_auto_update.yml#L23-L24

https://github.com/prefix-dev/pixi/releases/tag/v0.23.0

Needs pixi v0.23 on CI, as of writing this we have v0.22.

**Comment by visr** [comment]
When doing this we can directly make use of this method, also to display the changes in a markdown table in the diff:

https://pixi.sh/dev/advanced/updates_github_actions/

**Comment by Jingru923** [comment]
Since pixi v0.24.2 is released. I have update it and now wait for the rollout of Windows agent.
