### ISSUE TITLE
Ensure Delwaq receives correct network typology

### ISSUE THREAD

**Issue by SnippenE** [Deltares/Ribasim#1506]
see attachment. current status is not representing the Ribasim network correct

![Image](https://github.com/Deltares/Ribasim/assets/78435326/9511fcfa-8486-49c3-bf92-8014514c12b5)

**Comment by evetion** [comment]
Fixed in #1519:
![Image](https://github.com/Deltares/Ribasim/assets/8655030/8ebee185-8239-4abb-9265-6bdf29d7a733)

**Comment by gijsber** [comment]
Oude tijden herleven. dit doet erg aan een DM model schematisatie denken
![image](https://github.com/Deltares/Ribasim/assets/14976756/4e4bb45b-2d82-421c-8667-f361384d6743)

**Comment by visr** [comment]
The original Edge geometries of this model nicely follow the waterways, but in `model.to_xugrid` we currently drop this information and preserve only the topology. We could probably add it to the datamodel under UGrid or Deltares conventions like done for reaches.
