### ISSUE TITLE
Consider licence agreement prompt on command line

### ISSUE THREAD

**Issue by evetion** [Deltares/Ribasim#1527]
Maybe built into the rust wrapper?

I think a prompt with `y/N` that writes a file so your acceptation is remembered and a flag --accept-license that always runs make sense?

More so than foregoing Linux and having a Windows installer?

Doing this would also solve distribution on conda like channels.

@deltamarnix @visr

**Comment by evetion** [comment]
> h'mmm, any need for a click to execute makes life a lot harder if you want to roll out Ribasim in a Fews context **unless** the Rust-wrapper checks for the i_accept_license file. In that case, the Fews-configurator will include this i-accept file in the RibasimBinaries.zip (with the exe etc) as the model software will already be covered via the standard Fews-license for Operatonal systems.

Yes, I meant that once you accept (y in prompt), an `i-accept` file is written that is checked by the rust wrapper next time around, so the prompt (if accepted) should only be a one time thing. For FEWS you could also always run `ribasim --accept-license model.toml`, or add that argument via a FEWS specific `.bat` file.

I'm trying to find the least intrusive/friction way of adding this licence thing to our binaries.

**Comment by Huite** [comment]
`y/n` license prompts are a horrible idea. Where does this requirement come from?

**Comment by deltamarnix** [comment]
Can you elaborate on why they are horrible? At least we could add a `-y` option during install. It is not clear yet what the requirements are, so we need to check with the PMT on how to arrange this properly.

**Comment by evetion** [comment]
This must be my most popular issue to date.

**Comment by evetion** [comment]
It seems we only need a warning on the download page.
