### ISSUE TITLE
DoD, Error Handling

### ISSUE THREAD

**Issue by Jingru923** [Deltares/Ribasim#1535]
In Error Handling,

- [x] Discussion point: will there and should there be a test plan to prove our error logging works?
- [x] Specify if a run can be resume if error occurs in the middle of a run

For more information, see Marnix's comments

**Comment by visr** [comment]
Updated the DoD and https://github.com/Deltares/Ribasim/issues/1350 and https://github.com/Deltares/Ribasim/issues/1358. I think that should cover open questions.

**Comment by visr** [comment]
Yes, I deleted the TODOs, since they are done.
