### ISSUE TITLE
Update release file-references in Docs

### ISSUE THREAD

**Issue by gijsber** [Deltares/Ribasim#1549]
In the release we produce:

- ribasim_linux.zip
- ribasim_windows.zip

On the docs page (https://deltares.github.io/Ribasim/tutorials/index.md)  we reference:

- ribasim_cli_linux.zip
- ribasim_cli_windows.zip

I do not know what filename is preferred, but I do know that it would be good if it is the same :-)

**Comment by visr** [comment]
Yeah the former is preferred, we removed cli from the name when we started bundling libribasim.dll and ribasim.exe.

**Comment by visr** [comment]
Fixed in #1548
