### ISSUE TITLE
Improve first sentence Home page

### ISSUE THREAD

**Issue by gijsber** [Deltares/Ribasim#1556]
Maybe our home page needs a better sentence to start, as I think the current one is outdated:
Current:
Ribasim is a water resources model, designed to be the replacement of the regional surface water modules Mozart and SIMRES in the Netherlands Hydrological Instrument (NHI). 

Proposed new:
Ribasim is a water resources model to simulate the physical behaviour of a managed open water system based on a set of control rules and a prioritized water allocation strategy.

**Comment by visr** [comment]
I agree that's better. Best to just propose this directly as a PR, clicking the ✏️ on docs/index.qmd.
