### ISSUE TITLE
Improve QGIS QgsMarkerLineSymbolLayer in Ribasim-plugin

### ISSUE THREAD

**Issue by DanielTollenaar** [Deltares/Ribasim#1562]
**With multi-vertice LineStrings arrow-symbol becomes unreadible**
Currently Ribasim Plugin places arrow-marker at the center of every line-segment. With multi-vertice Linestrings (river axis in stead of links) direction becomes unreadible:
![image](https://github.com/Deltares/Ribasim/assets/14051252/e8860b64-dcc4-46d5-89b5-1215aa209562)

**Why**
You're placing an arrow at every segment in stead of the centre point 

**How**
Replace `SegmentCenter` by `CentralPoint`. So this https://github.com/Deltares/Ribasim/blob/4e7ea0e87aa65852195208cf8ac2d22d0dd0211a/ribasim_qgis/core/nodes.py#L325 

with: 

```
....
QgsMarkerLineSymbolLayer.create({"placements": "CentralPoint"}),
....
```

**End result**
Simply beautifull :-)
![image](https://github.com/Deltares/Ribasim/assets/14051252/d5c95459-42a6-4ccd-8ffb-17499eea0cd5)

**Comment by visr** [comment]
Ah yes, this would be great to have. If you make a quick PR this can still make it into the release ;)

**Comment by DanielTollenaar** [comment]
> Ah yes, this would be great to have. If you make a quick PR this can still make it into the release ;)

see #1563
