### ISSUE TITLE
Allow salt injection as boundary condition

### ISSUE THREAD

**Issue by gijsber** [Deltares/Ribasim#158]
include salt injection as boundary condition to represent salt influx from the sea

**Comment by evetion** [comment]
This is fully supported by #1524? You can specify concentrations over time on LevelBoundaries that will be used by Delwaq. Or is that not what you meant?

**Comment by gijsber** [comment]
As discussed with @evetion this use case can indeed be handled by the current database structure which allow sepcification of substances on flow or headboundaries
