### ISSUE TITLE
Validate `min_crest_level` (Outlet) and `level` (TabulatedRatingCurve) with upstream `Basin / profile`

### ISSUE THREAD

**Issue by DanielTollenaar** [Deltares/Ribasim#1591]
**What**
When specifying an `Outlet` or `TabulatedRatingCurve` one can specify `min_crest_level` or `level` that is lower than the upstream `Basin / profile`. This is one of the most common causes of model instability/crashes. 

**Why**
Validating the `min_crest_level` and `level` column with the minimum `level`  upstream `Basin / profile` prior to modelling would speed-up model debugging. 

**How**
Compare `min_crest_level` and `level` columns in `Outlet` or `TabulatedRatingCurve` with upstream `Basin / profile` and give a validation error when `min_crest_level` and `level` are lower than the minimum level in the basin-profile

**Comment by DanielTollenaar** [comment]
> Do you see these instabilities / crashes also with default adaptive solvers?

Yes

For the rest, I think we see it the same way. And even if it doesn't/wouldn't serve a numeric purpose, in case of an `Outlet` of `TabulatedRatingCurve` `(min_crest_)level` lower than upstream basin-bottom is (in my view) faulty input that cannot be and therefore should be corrected :-)

**Comment by Jingru923** [comment]
Would it be a good idea to set the `min_crest_level` of Outlet to 0?

**Comment by gijsber** [comment]
Assuming you want to make 0 the default value....
... I don't think that is a good idea. 0 is in my opion an arbitrary choice as you do not know at what elevation your model is  located. If the majority is below mean sea level and your 0-reference is mean sea level your default value makes life complicated as the modeller might not be aware that you apply this default.
