### ISSUE TITLE
Integrated realized volumes per water user, larger than demand 

### ISSUE THREAD

**Issue by HendrikKok** [Deltares/Ribasim#1592]
In the coupling with MetaSWAP we found that the integrated realized values by Ribasim can be larger than the demand. It seems to happen with relatively small demands (around 10 m3/d). The surplus is in de order of 1.2 times the demand. 

1-	This happens with and without allocation active
2-	This happens with or without zeroing the realized-array per timestep. 
 
Expected behavior:
Integrated realized values can’t become larger than the demands (other than precision issues).

**Comment by visr** [comment]
Do you have the model somewhere so this can be checked?

Just to check `user_demand.realized` is cumulative since the start, as documented in https://deltares.github.io/Ribasim/dev/bmi.html#memory-pointers. The BMI driver needs to set it back to zero. Was this done?

**Comment by HendrikKok** [comment]
Yes, The realized is set to zero every timestep. For testing purposes I also check the behavior without zeroing this array (so we compute a diff) and this leads to the same results. 

We do have the coupled model we tested this on, but I don't know if it's easy accessible for you. I could also reverse the question: do you have a model were you tested the behavior of the realized volumes, relative to the demands?

**Comment by SouthEndMusic** [comment]
As @HendrikKok indicated, similar errors in volumes emerge for integrated basin forcings. Both things point to our integration routines being the problem. As a first step we could add an 'equation test', i.e. set some forcing for a basin to a function and check whether the integration matches what we expect analytically. 

If not, we might have to come up with a more accurate integration scheme, say a cubic hermite interpolation based on time derivatives of `water_balance!` obtained with `ForwardDiff`. Or we could give the out of the box integration callback another go.
