### ISSUE TITLE
Work around Julia artifacts permission errors

### ISSUE THREAD

**Issue by visr** [Deltares/Ribasim#1603]
Sometimes we get a [randomly failing build](https://dpcbuild.deltares.nl/buildConfiguration/Ribasim_Windows_TestDelwaqCoupling/4097452), of the form:

> ERROR: IOError: rm("C:\\Users\\svc-teamcity-ansible\\.julia\\artifacts\\jl_wq7J7S\\bin"): directory not empty (ENOTEMPTY)

The upstream issue and workaround is https://github.com/JuliaLang/julia/issues/52272#issuecomment-2093625309.

```ps1
icacls .julia/artifacts /q /c /t /reset
```

Of course it is a lot of work to fix permissions manually on TeamCity agents, so we need something better.

@evetion suggested earlier to make a TeamCity job which can fix this error. Or perhaps we can just try fixing the permissions on each run, to never leave behind a broken agent.

**Comment by evetion** [comment]
I've made a build (and have scheduled it to run on a failing agent) https://dpcbuild.deltares.nl/buildConfiguration/Ribasim_Ribasim_Windows_FixJuliaArtifactPermissions?branch=continuous_control&buildTypeTab=overview&mode=builds

Let's see how often we need to run this, and either detect the failure and run it, or always run it.
