### ISSUE TITLE
Add a page with the usage of the add API

### ISSUE THREAD

**Issue by SouthEndMusic** [Deltares/Ribasim#1608]
@Fati-Mon mentioned that from the documentation it is not clear how to set up a model in Ribasim python for new users. We have the examples, but that is already quite a deep dive without detailed explanation of the add API. 

So I propose adding a new page with how to set up a model, with detailed explanations of every step from initializing the model to writing it to disk. Maybe also add some information about how the input data will end up in the tables.

**Comment by visr** [comment]
This is what I had in mind for #1158 as well.
