### ISSUE TITLE
Listen to substance and concentration for control

### ISSUE THREAD

**Issue by evetion** [Deltares/Ribasim#1610]
Change control to allow also other conditions to listen to (besides level and flow)

**Comment by SouthEndMusic** [comment]
Is this specifically for `Basin / ConcentrationExternal`?

**Comment by gijsber** [comment]
Initially yes, in later stage we also want it to work on the Basin /Concentration table

**Comment by SouthEndMusic** [comment]
Are the tables deliberately written into the geopackage file as `BasinConcentration / external` and `BasinConcentration / state` in stead of `Basin / *`? Could this explain why I cannot retrieve the data in these tables with `load_structvector(db, config, BasinConcentrationExternalV1)` in the core?

**Comment by gijsber** [comment]
@evetion and @visr have been think about this for a while, so I assume it was deliberate.

**Comment by visr** [comment]
Should be `Basin / *`, as added in #1267.
