### ISSUE TITLE
Polish docs

### ISSUE THREAD

**Issue by Jingru923** [Deltares/Ribasim#1623]
#1158 and #1571 are two major doc items we need to address before v1.0. After this I don't think the docs are really v1.0-worthy yet. I cannot now point to concrete chunks, but we probably need some more editing and restructuring.

Tasks:
- [x] #1571
- [x] #590 
- [x] #1365  
- [x] #1651
- [x] #1463 
- [x] #1152
- [ ] Update logos to add D2Hydro and link to NHI (@SnippenE) https://github.com/Deltares/Ribasim/pull/1840

**Comment by SouthEndMusic** [comment]
Automatically detect broken links?

**Comment by Jingru923** [comment]
All tasks are done so this issue can be closed
