### ISSUE TITLE
Get rid of dependency `SmoothInterpolation.jl` in favor of the new `DataInterpolations.jl` release

### ISSUE THREAD

**Issue by SouthEndMusic** [Deltares/Ribasim#1625]
All features of `SmoothInterpolation` and more have been merged and released in `DataInterpolations.jl`:

https://github.com/SciML/DataInterpolations.jl/releases/tag/v5.3.0

Most notably, we can now do integral inversion via `DataInterpolations.jl`.

**Comment by SouthEndMusic** [comment]
I had to pin the `DataInterpolations.jl` version to `5.2.0` in https://github.com/Deltares/Ribasim/pull/1602 as the new version breaks some things.

**Comment by Jingru923** [comment]
Issue #1621 can be addressed
