### ISSUE TITLE
QGIS install docs

### ISSUE THREAD

**Issue by visr** [Deltares/Ribasim#1630]
@Huite mentioned these improvements in #1627

> The current Install docs don't mention QGIS very explicitly: https://deltares.github.io/Ribasim/install.html
Maybe add a section there?
I would also suggest adding a note in the README.md of the repo. There's a link to download the plugin there.

**Comment by gijsber** [comment]
I would suggest to keep it short by adding a QGIS version pre-condition in your download section: e.g.
QGIS plugin (3.34 LTR or higher): ribasim_qgis.zip

**Comment by visr** [comment]
Fixed by #1691
