### ISSUE TITLE
Styling and hiding parts of the network in QGIS

### ISSUE THREAD

**Issue by DanielTollenaar** [Deltares/Ribasim#1633]
**What**
A user wants to be able to toggle the visibility of links showing demand/return_flow on/off so the user doesn't get lost in all edges. 

**Why**
Demand/supply often represent (piped)systems that are not modelled explicitly. They will cross the actual water system that is being modelled explicitly. The user may get lost in a web of edges representing supply and return_flow

![image](https://github.com/user-attachments/assets/5c413cc5-b1a0-4fae-ad5a-c79e3ba595d7)

**How**
Suggest to add a `demand` edge_type, or something similar, that the user can switch off in QGIS, just as the user can toggle control-type links on and off

**Comment by visr** [comment]
The edge_type is primarily something we need to distinguish in the core. Besides this our default style uses this a a categorized symbology to give them a separate color.

It might be worth thinking about nice ways to control visibility by for instance looking at a column in the data model, or adding toggles. Though I think the requirements for this are different per model, and it probably won't be a priority soon. Also these is value to relying on QGIS as much as possible for these kinds of things.

For instance you can switch from a categorized to a rule-based symbology, and look at the `from_node_type` or `to_node_type`:

![image](https://github.com/user-attachments/assets/6615e2dd-01b5-4a52-b731-df6e6a055378)
![image](https://github.com/user-attachments/assets/0e2b4368-bb06-47d0-8104-a98518a430c1)

**Comment by visr** [comment]
With #1713 you can now customize the style in QGIS as you wish, and it will save this in the model database. Let us know if that is sufficient.
