### ISSUE TITLE
DiscreteControl doesn't seem to pass correct control_state to Outlets

### ISSUE THREAD

**Issue by DanielTollenaar** [Deltares/Ribasim#1637]
**What dit we do**
We build a model with DiscreteControl node (node_id 1000002):
- Listening to a FlowBoundary at Monsin (node_id  7011)
- Controlling multiple Outlets, regulating flows trough the Meuse and Belgium/Dutch canal systems

For the remainder we focus on the diversion at Borgharen (node_id = 7764), Julianakanaal (node_id = 7925) and verbindingskanaal (node_id = 7759). We use a steady-state model with bc 450 m3/s at Monsin available via transfer: https://we.tl/t-Ybsly5S9hX

**Expected result**
At 450 m3/s we would be at control_state `Monsin_186` (see DiscreteControl / condition):
![image](https://github.com/user-attachments/assets/2a8999b1-b3ed-4f2a-9d0a-6e9bf2b40060)

That would give us an `min_crest_level` at node_id's 7759, 7764 and 7925 of 44.21 m NAP (see Outlet / static). Thereby we would expect a water-level at the upstream Basin (node_id 7706) of +/- 44.2 m NAP:
![image](https://github.com/user-attachments/assets/6d1add12-a15c-4c5c-baf1-e50aceb88858)
![image](https://github.com/user-attachments/assets/aa493850-6933-4ab6-8bf5-b1d3bfe2acec)
![image](https://github.com/user-attachments/assets/a5f4db22-de9a-4f1f-9199-247c50d07284)

**Actual result**
We see a water-level of > 48.09m NAP at Basin 7706, which is much higher than expected. This level corresponds at the highest control_states in our table, which should apply at discharges > 7100 m3/s at Monsin:
![image](https://github.com/user-attachments/assets/85be3127-c2cf-42cc-ab74-6ea4e850fbb4)

**Additional information**
Our analysis stops here, we suspect the controller some-how got lost. If we could see the actual `crest_level` of `Outlet` during simulation, and `control_state` at `DiscreteControl` we could verify further. Would it be an idea to user-define storage of results for different node-types in a results-section of the toml-file (following SOBEK functionality)?

**Comment by visr** [comment]
Thanks for the report. Good to look into this

> If we could see the actual crest_level of Outlet during simulation, and control_state at DiscreteControl we could verify further.

Have you looked at `control.arrow`? https://deltares.github.io/Ribasim/reference/usage.html#discretecontrol---control.arrow

**Comment by gijsber** [comment]
Hi @visr , is this one to check before pushing out the release ?
