### ISSUE TITLE
Improve subprocess call example

### ISSUE THREAD

**Issue by Fati-Mon** [Deltares/Ribasim#1638]
**What**
In https://deltares.github.io/Ribasim/guide/examples.html#model-with-discrete-control some lines for running the model is shown, but it is not complete:

![image](https://github.com/user-attachments/assets/9f3338c9-0cd6-4529-9312-b80b989d0edd)

Where is cli_path referenced to?

**Why**
We need to make sure the documentation can be understood even by modelers who are not completely familiar with python. Especially beginners need more clarification. 

**How**
Add the cli_path somewhere at the beginning of the code and/or explain which path needs to be addressed here.

**Comment by visr** [comment]
We should also double check if users doing this see errors and stacktraces as they should.
