### ISSUE TITLE
Installation guide

### ISSUE THREAD

**Issue by Fati-Mon** [Deltares/Ribasim#1639]
**What**
After discussing with Peter, we came to the conclusion that it would be best to detail the steps regarding the installation of RIBASIM9. Right now the website (https://deltares.github.io/Ribasim/install.html) is very brief.

We are also dealing with different dependencies and I have encountered many times issues when running and/or building the model after using the model again for a while. 

**Why**
When I use the model again after a while, what I usually do is delete the old version and download the new according to the website or github. However, sometimes the issue was not downloading the new version but rather the outdated versions in my Python, pixi or other dependencies. This can be really confusing for a user, as it is not clear which needs to be updated. 

**How**
Can we describe the installation guide more in details with steps to take? No shortcuts, monkeyproof. 

Preferably, PyPI should identifiy that it needs to delete all old versions of the packages used and put automatically the new ones in.

**Comment by visr** [comment]
Do you have any more concrete actions that we still need to take here, next to #1642?

I know the issues with dependencies that you've had, but these should all be fixed now on the main branch, and not an issue in the upcoming release. One of them, the deleting of old versions, was fixed in Pixi.

Any time you run into similar installation issues it's good to report them such that we can fix them.

**Comment by Fati-Mon** [comment]
Yes, everything looks good. I tested uploading and unpacking the .zip file again, and indeed this time it worked without any issues.

Would it be possible to merge sections 2 and 3? The 'Download' section appears without an introduction, but the first paragraph of Section 3 seems to serve that purpose, as it explains the unpacking process of the zip files.
No further action.

**Comment by visr** [comment]
We also need to mention in the download section that we currently only support and provide binaries for Windows and Linux, for the x86_64 architecture.
