### ISSUE TITLE
For developers: Create `Plots` extension of Ribasim

### ISSUE THREAD

**Issue by SouthEndMusic** [Deltares/Ribasim#1672]
We can create a `RibasimPlotsExt.jl` which contains functionality to easily plot results of a simulation (storages, flows, easily select subsets) in Julia without having the core depend on `Plots`. This is nice when developing on the core and not having to write results to disk first to plot them in Python.

**Comment by visr** [comment]
Yeah this'd be nice, though I'd go with Makie.
