### ISSUE TITLE
Adding nodes in QGIS lets users add the same node_id multiple times

### ISSUE THREAD

**Issue by deltamarnix** [Deltares/Ribasim#1688]
If you add a node, in the feature attributes table you can set the same node_id twice.
This could be detected by QGIS before pressing OK.

See: https://gis.stackexchange.com/questions/339737/populating-text-field-with-predefined-attributes-in-qgis

**Comment by deltamarnix** [comment]
I edited the attribute forms via QGIS, but it is saved in the project file. I am going to guess that editing the TABLE information on creation can be detected by QGIS, but the other way around it doesn't seem to be altered into the geopackage by QGIS.

**Comment by deltamarnix** [comment]
The same issue holds for node_type. The default is NULL and therefore you get white dots instead of basins (or something else).

![image](https://github.com/user-attachments/assets/08d7433a-efa9-4a26-a692-4a2fdc735aaa)

**Comment by visr** [comment]
Just want to add that it is currently the combination of node_id and node_type that needs to be unique. For that combination this issue remains. Name can be duplicated.
