### ISSUE TITLE
Allocation should return same strategy if a model is run twice

### ISSUE THREAD

**Issue by Jingru923** [Deltares/Ribasim#1709]
**What**
When building up benchmark for Ribasim, it has come to attention that if I run a model with allocation twice, I will get different water balance. This is because some optimization problems have unlimited solutions and the solver returns a random one. Therefore the output of allocation model is always different. This should be investigated.

**How**

- [ ] Investigate JuMP and its solvers. Given an optimization problem with non-unique solution, the solver should return the same solution every time.
- [ ] Run model with allocation twice, and see if the output is the same
- [ ] Update the benchmark for allocation models.

**Comment by Jingru923** [comment]
In the regression test, these values should be benchmarked and tested against the benchmark.
```julia 
                # TODO @test all(q -> abs(q) < 12.0, basin.storage - basin_bench.storage)
                # TODO @test all(
                #     q -> abs(q) < 100.0,
                #     basin.storage[(end - 16):end] - basin_bench.storage[(end - 16):end],
                # )
                # TODO @test all(
                #     q -> abs(q) < 2.0,
                #     basin.level[(end - 16):end] - basin_bench.level[(end - 16):end],
                # )
                # TODO @test all(q -> abs(q) < 1e-1, basin.balance_error)
                # TODO @test all(q -> abs(q) < 30.0, basin.relative_error)
```

**Comment by Huite** [comment]
> Given an optimization problem with non-unique solution, the solver should return the same solution every time

Wouldn't it be better to make sure you have a unique solution? I.e. we should make it so that the optimization problem is well defined.

**Comment by SouthEndMusic** [comment]
Yes, that's what upcoming issues for allocation are for, especially optimizing per source individually. Still, it's weird that the optimizer is not deterministic.
