### ISSUE TITLE
Use Pandas Arrow backend

### ISSUE THREAD

**Issue by visr** [Deltares/Ribasim#1721]
Currently we use the Pandas NumPy backend. Nowadays pandera also supports the Pandas [Arrow backend](https://pandas.pydata.org/docs/user_guide/pyarrow.html), as well as [polars](https://pola.rs/), which is also based on Arrow.

Given that we make a lot of use of Arrow, and the documented advantages of these representations, we should consider switching.

I think Polars and especially https://github.com/geopolars/geopolars is a bit too new at this point, and Pandas Arrow is probably a smaller step.

https://pandera.readthedocs.io/en/stable/dtype_validation.html#pyarrow-data-types

**Comment by evetion** [comment]
How's this a v1.0 😅

**Comment by visr** [comment]
I meant mainly to look into it before v1.0. Not sure how breaking this would be, or how much work. We can definitely decide to push it after based on a first investigation.

**Comment by Jingru923** [comment]
I had a look at it, currently only these function can take arguement of `dtype_backend` and specify "pyarrow": 
[read_csv()](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html#pandas.read_csv)
[read_clipboard()](https://pandas.pydata.org/docs/reference/api/pandas.read_clipboard.html#pandas.read_clipboard)
[read_fwf()](https://pandas.pydata.org/docs/reference/api/pandas.read_fwf.html#pandas.read_fwf)
[read_excel()](https://pandas.pydata.org/docs/reference/api/pandas.read_excel.html#pandas.read_excel)
[read_html()](https://pandas.pydata.org/docs/reference/api/pandas.read_html.html#pandas.read_html)
[read_xml()](https://pandas.pydata.org/docs/reference/api/pandas.read_xml.html#pandas.read_xml)
[read_json()](https://pandas.pydata.org/docs/reference/api/pandas.read_json.html#pandas.read_json)
[read_sql()](https://pandas.pydata.org/docs/reference/api/pandas.read_sql.html#pandas.read_sql)
[read_sql_query()](https://pandas.pydata.org/docs/reference/api/pandas.read_sql_query.html#pandas.read_sql_query)
[read_sql_table()](https://pandas.pydata.org/docs/reference/api/pandas.read_sql_table.html#pandas.read_sql_table)
[read_parquet()](https://pandas.pydata.org/docs/reference/api/pandas.read_parquet.html#pandas.read_parquet)
[read_orc()](https://pandas.pydata.org/docs/reference/api/pandas.read_orc.html#pandas.read_orc)
[read_feather()](https://pandas.pydata.org/docs/reference/api/pandas.read_feather.html#pandas.read_feather)
[read_spss()](https://pandas.pydata.org/docs/reference/api/pandas.read_spss.html#pandas.read_spss)
[to_numeric()](https://pandas.pydata.org/docs/reference/api/pandas.to_numeric.html#pandas.to_numeric)
[DataFrame.convert_dtypes()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.convert_dtypes.html#pandas.DataFrame.convert_dtypes)
[Series.convert_dtypes()](https://pandas.pydata.org/docs/reference/api/pandas.Series.convert_dtypes.html#pandas.Series.convert_dtypes)

Which means that to define a dataframe with pyarrow is not possible. We can only read database into and convert a dataframe after it's defined.

```python
import pandas as pd
import pyarrow as pa

# Create a DataFrame with pyarrow backend
df = pd.DataFrame({"A": [1, 2, 3], "B": ["x", "y", "z"]})
pa_df = pa.Table.from_pandas(df)

# Verify the backend
print(df.dtypes)
print(pa_df)
```

**Comment by Jingru923** [comment]
There are only 20 instance in ribasim python that is using `pd.DataFrame`, and 8 out of 20 is definition and the rest is verification. Converting into "pyarrow" backend after each initialization shouldn't be a lot of work. 

So far, I don't see how using "pyarrow" can make big improvement since using "pyarrow" is similar to using numpy. But maybe I am wrong

**Comment by Huite** [comment]
>  and the documented advantages of these representations

These are not obvious to me, is there a nice overview page somewhere?

Specifically for our use case, I have trouble seeing advantages with integers or floats, so it's mostly due to strings? (Since the geometries are in the geopackage.) The downsides are big: it looks like the API is massively different.

Can't even multiply yet?

```python
TypeError                                 Traceback (most recent call last)
Cell In[6], line 1
----> 1 pa_df["A"] * 2.0

TypeError: unsupported operand type(s) for *=: 'pyarrow.lib.ChunkedArray' and 'float'
```

**Comment by visr** [comment]
I put a link in the top post under Arrow backend. Though it's not that extensive.

Your `pa_df` is not a pandas DataFrame with Arrow dtypes though, it is a `pyarrow.Table`, which indeed has a very different and immutable API.

**Comment by evetion** [comment]
From the session, some open questions to answer:
- How does this work with pandera (since there's some support in recent versions)
- How does this work with pyogrio use_arrow=True (can also be done with numpy I assume)
- Is this faster on concat operations (the add API appending a single row each time)
- What happens if we mix/match types in a DataFrame

Polars is out of scope, as replacing pandas would be really breaking for everyone, and there's no mature validation library or geopolars yet.

**Comment by Jingru923** [comment]
Following code was used to test the pyarrow and numpy backend
```python
import pandas as pd
import random
import timeit

number = [random.random() for i in range(1_000_000)]
string = [str(random.random()) for i in range(1_000_000)]


# Print space usage of a data type
def print_mem(type_name, s: pd.Series):
    print(
        type_name,
        str(round(s.memory_usage(deep=True) / 1024**2, 2)).rjust(6, " ") + "MB",
        sep="\t",
    )


pd_np_n = pd.Series(number, dtype="float64")
print_mem("float64", pd_np_n)

pd_ar_n = pd.Series(number, dtype="float64[pyarrow]")
print_mem("float64[pyarrow]", pd_ar_n)

pd_np_str = pd.Series(string, dtype="string")
print_mem("string", pd_np_str)

pd_ar_str = pd.Series(string, dtype="string[pyarrow]")
print_mem("string[pyarrow]", pd_ar_str)

# Print used time for aggregation
%timeit pd_np_n.agg(['min','max','mean','median','std'])
%timeit pd_ar_n.agg(['min','max','mean','median','std'])

# Print used time for looking up
pd_df_np = pd.DataFrame(data={"number": pd_np_n,
                        "string": pd_np_str})
pd_df_ar = pd.DataFrame(data={"number": pd_ar_n,
                        "string": pd_ar_str})
%timeit select_np = pd_df_np[pd_df_np['number']<=0.5]
%timeit select_ar = pd_df_ar[pd_df_ar['number']<=0.5]

# Print used time for reading
%timeit basins_np = pd.read_feather( "basin.arrow")
%timeit basins_ar = pd.read_feather( "basin.arrow",dtype_backend="pyarrow")

# Print used time for writing
basins_np = pd.read_feather( "basin.arrow")
basins_ar = pd.read_feather( "basin.arrow",dtype_backend="pyarrow")

%timeit basins_np.to_csv("basin_np.csv", index=False)
%timeit basins_ar.to_csv("basin_ar.csv", index=False)
```

**Comment by SnippenE** [comment]
Conclusion of discussion Knowledge Sharing Session : no expected breaking changes for user. No urgent issue for v1.0 now.
