### ISSUE TITLE
Time array length mismatch

### ISSUE THREAD

**Issue by Fati-Mon** [Deltares/Ribasim#1725]
**What**
Demand node over time does not support return flow over time. However, if the arrays are not of the same length ```time``` the model does not run. 
![image](https://github.com/user-attachments/assets/130b308f-3add-408a-8f01-43b54cf09835)

Did not test it on ```min _level``` but I should look into it.

**Why**
It gives the impression that the user is able to define the return flow over time. You can define it in the code, but the flow from this return edge will always be zero :
![image](https://github.com/user-attachments/assets/c104cef9-c471-4af9-b174-9194b7cbeb17)

**How**
We could document this under 'reference' and/or limit the possibility for the user to define values that will not be read anyways. 

**Additional context**
See #1724 for full code

**Comment by Jingru923** [comment]
Hi Fatima, this issue #1230 is about adding transient user demand return factor. It should be finished today. Maybe after the PR #1727 is closed, you can try again

**Comment by SouthEndMusic** [comment]
The arrays must be the same length to have a well defined input table, that is not an issue specific to our code.

Having to repeat certain data is the downside of having tables in long format. Maybe it should be documented somewhere that although certain dependencies are technically possible in the input tables, that does not mean the core will actually use it. An example of this is that the `UserDemand` tables allow input that indicates that the `return_flow` depends on `priority`, but the core does not pick that up.
