### ISSUE TITLE
Python: model.write() will append to existing geopackages

### ISSUE THREAD

**Issue by Huite** [Deltares/Ribasim#173]
It looks like geopandas will append layers to an existing geopackage. This is not desirable when calling `model.write`: you're writing the entire model. I think we should check if a file with the given name already exists, then delete it before writing.

**Comment by visr** [comment]
Related: the TODO as mentioned in https://github.com/Deltares/Ribasim/issues/170#issue-1672932751. We only need geopandas for node and edge tables.
