### ISSUE TITLE
Get rid of type piracy on `DataInterpolations` for `SparseConnectivityTracer`

### ISSUE THREAD

**Issue by SouthEndMusic** [Deltares/Ribasim#1733]
https://github.com/Deltares/Ribasim/pull/1606 introduces type piracy on `DataInterpolations` to create a custom overload of interpolation evaluation for `SparseConnectivityTracer`, see also the `Aqua` test. This can be removed when `SparseConnectivityTracer` introduces their own support for `DataInterpolations`, which they will probably do as indicated [here](https://github.com/adrhill/SparseConnectivityTracer.jl/issues/74#issuecomment-2256399578).

**Comment by adrhill** [comment]
We've got some shiny new doc-pages in SCT, including one on [how to add overloads](https://adrianhill.de/SparseConnectivityTracer.jl/dev/dev/adding_overloads/).

Feel free to open a PR with a `SparseConnectivityTracerDataInterpolationsExt`, even if it just implements the minimal set of functions you need. Let me know if things are unclear or if you need some help!

**Comment by SouthEndMusic** [comment]
@adrhill thanks for the heads up!
