### ISSUE TITLE
Custom domain setting gets reset

### ISSUE THREAD

**Issue by visr** [Deltares/Ribasim#1740]
We now use ribasim.org as the domain for our docs here, and ribasim.nl as the domain for https://github.com/Deltares/Ribasim-NL.

In the GitHub setting we specify this like so, under https://github.com/Deltares/Ribasim/settings/pages:
![image](https://github.com/user-attachments/assets/abb51dec-bb58-4e76-bbf0-d1b13cb426d9)

Both @evetion and me have already observed multiple times in the past few days that this custom domain is removed and the field is empty. When this happens we get a 404 on our docs. When filling in the settings again like above, it is back online.

Why does this setting get removed? Could it be a GitHub Enterprise policy or such?

**Comment by evetion** [comment]
It's the CNAME file that's required, when you change the settings, it's actually a commit: https://github.com/Deltares/Ribasim/commit/283c583f73c3e37b7e1a543498b08e3a5157c933. Merging to main triggers a new deployment to gh-pages and removes the CNAME. Made a [fix](https://github.com/Deltares/Ribasim/pull/1742).
