### ISSUE TITLE
MinIO stores too much artifact and it is getting full

### ISSUE THREAD

**Issue by Jingru923** [Deltares/Ribasim#1744]
**What**
In the MinIO bucket, 13,9 GB of the space is used. There should be an option on either TC or MinIO that to auto-delete the artifact. We should look into that so we have enough space on MinIO

**Comment by visr** [comment]
What do we store there?

**Comment by Jingru923** [comment]
It is mainly our built binary. I am going to first monitor the usage and if it keep going up, then I will change the rules of storage.

I just realize that this is not suitable for label 1.0 so I will remove it.

**Comment by SnippenE** [comment]
At the moment no storage issues.
