### ISSUE TITLE
model.edge.add() starts with existing edges starts with edge_id=1, causing unique validation error

### ISSUE THREAD

**Issue by DanielTollenaar** [Deltares/Ribasim#1804]
Below an example on how I add new edges using the add-API in current main (pulled 06-09-2024). Adding edges will add edge_id=1, going up one int every time I edge. Problem is, edge_id 0 till 1956 are already used causing a unique validation error on the edge_id column while writing

![image](https://github.com/user-attachments/assets/af1af229-05e6-410a-a43e-b07bbb87e153)

**Comment by evetion** [comment]
Fixed in #1818
