### ISSUE TITLE
model.basin.add() in model with existing nodes will cause AssertionError next-time model.node_table() is is accessed  

### ISSUE THREAD

**Issue by DanielTollenaar** [Deltares/Ribasim#1806]
While not to explicitly check available node_id in model with existing nodes, I run this code:

```
        geometry = basin_to_point(basin_polygon=basin_polygon, tolerance=10)
        node = Node(
            meta_categorie="bergend",
            geometry=geometry,
        )
        data = [basin.Profile(level=[0, 1], area=[5, 100]), basin.Area(geometry=[basin_polygon])]
        basin_node = model.basin.add(node=node, tables=data)
```

Inspecting the `model.basin.node.df` I notice node_id =1 has been assigned. Does not exist in the basin-table, but does exist as `FlowBoundary`:
![image](https://github.com/user-attachments/assets/427473d8-9539-493c-ab94-336e253c2f10)

Thereby accessing `model.node_table()` will raise an `AssertionError: node_id must be unique`:
![image](https://github.com/user-attachments/assets/19ad2bfe-3922-47a9-ad64-39351a1ac5cc)

**Comment by visr** [comment]
Without checking I'd expect we just don't currently set the max node and edge IDs on reading a model, same for #1804.
