### ISSUE TITLE
Quickstart contains a number of typos

### ISSUE THREAD

**Issue by Huite** [Deltares/Ribasim#1807]
I noticed the Quickstart language isn't fully polished yet: in particular the misspelling of Modual instead of Module had me rather confused.

I would like to stress that LLMs like [Claude](https://claude.ai/new) are very quick and to use to identify these problems. For example, this is what Claude told me.

## Claude

Here's a list of the typos and minor errors I've noticed:

1. In the "Installation" section, step 4:
   - "We use a command line interface (CLI) to install our Ribasim packages." should be "We use a command line interface (CLI) to install our Ribasim package."

2. In the "Data preparation" section:
   - "Additionally, your Python model (.py) and eventually the output files will also be saved in this folder." The word "eventually" seems out of place here. Consider rewording to "Additionally, your Python model (.py) and the output files will also be saved in this folder."

3. In the "Modual 1 - Crystal River Basin" section:
   - "Modual" should be spelled "Module" (this occurs multiple times throughout the document)

4. In the "Step 3: Flow boundary nodes" section:
   - "print('Average inflowQ m3/s:',data['sum'].max)" should be "print('Maximum inflowQ m3/s:',data['sum'].max())"

5. In the "Step 7: Defining edges" section:
   - The numbering starts with "1." but then continues with "2.	Basin to the rating curve;" - the tab should be removed for consistency.

6. In the "Step 1: Setup the model & adjust Import Packages" section:
   - "import shutilfrom" should be "import shutil"
   - "from pathlib" should be "from pathlib import Path"

7. In the "Step 8: Plot and compare the basin results" section:
   - There's an extra blank line between "ax3.set_xlabel('Time')" and "fig.tight_layout()"

8. In the "Modual 2 – Reservoirs and Public Water Supply" section:
   - "Modual" should be "Module"

9. In the "Step 2: Add a demand node" section:
   - The comment "# Total demand in m³/s" is slightly misaligned with the others in the code block.

**Comment by visr** [comment]
Thanks for the list. I still wanted to go over it next week post-merge. Also to remove duplication e.g. keep the installation instructions out of the quick start.
