### ISSUE TITLE
Use storage, not level, for benchmark

### ISSUE THREAD

**Issue by Jingru923** [Deltares/Ribasim#1827]
**What**
In integration test for HWS model, the benchmark variable is the level of basin at the end of simulation (`basin_state.arrow`). If the difference between the simulated level and the benchmark level for every basin is less than 0.06 meter, the integration test can be passed.

Since we start using backtracking, the simulation result is no longer deterministic. I noticed that for basin with different properties, the difference between the result level and benchmark sometimes can be big like 0.06 (meter) and sometimes can be small like 1e-12. Having a tolerance of 0,06 for every basin is not reasonable.

**How**
Investigate if storage can be a good benchmark variable. If so, find out a reasonable tolerance for the difference between benchmark and simulated value.

**Comment by Huite** [comment]
> the simulation result is no longer deterministic

What?(!)

Running the same problem twice with the same solver settings and initial state doesn't result in the same answer?
Or is it different solvers?

Actual non-deterministic behavior would definitely be a bug.

**Comment by visr** [comment]
I just checked locally running HWS on main a few times. The entire content of `results/` is bitwise identical.
I'm not sure yet where the differences come from. I know that for instance results on macOS are slightly different. But as far as I know running the same model on the same hardware twice is deterministic, as long as allocation is not involved (and that will be worked on soon).
