### ISSUE TITLE
Document known issue: (small) negative flows from e.g. Terminals

### ISSUE THREAD

**Issue by visr** [Deltares/Ribasim#1838]
- Add explanation of callback check
- In `usage.qmd`: add explanation of water balance tolerance options (too large error probably indicates error in the code or floating point errors)

_Originally posted by @SouthEndMusic in https://github.com/Deltares/Ribasim/issues/1828#issuecomment-2361129601_

**Comment by evetion** [comment]
Add limitations of current version.

**Comment by evetion** [comment]
#1899 Did not address that users can see (small) negative flows from Terminals.

**Comment by visr** [comment]
Ah right, reopening for that. Unless this becomes fixed altogether with #1897.
