### ISSUE TITLE
Save benchmark results over time in readable/plottable format

### ISSUE THREAD

**Issue by evetion** [Deltares/Ribasim#1879]
Minimum is to fix the current benchmark on teamcity

**Comment by visr** [comment]
Copying from https://github.com/Deltares/Ribasim/issues/1698#issuecomment-2271429789:

In terms of published benchmark tracking, there is https://github.com/SciML/SciMLBenchmarks.jl but comparing commits over time like https://lux.csail.mit.edu/benchmarks/ also looks nice.

**Comment by evetion** [comment]
I'd also consider DVC https://dvc.org/doc/user-guide/experiment-management/comparing-experiments
