### ISSUE TITLE
Docs takes 45 minutes to build

### ISSUE THREAD

**Issue by evetion** [Deltares/Ribasim#1892]
Because the simulation (cell 29/92) in examples.ipynb hangs on 35% for 30+ minutes.

https://github.com/Deltares/Ribasim/actions/runs/11242407247/job/31256016106?pr=1891#step:7:328

**Comment by visr** [comment]
Odd. That is the `level_range` model, https://ribasim.org/guide/examples.html#model-with-discrete-control.
