### ISSUE TITLE
Average flow states

### ISSUE THREAD

**Issue by SouthEndMusic** [Deltares/Ribasim#1906]
Now we define a state like this:

$$
u = \int_{t_0}^t q\text{d}\tilde{t}
$$

which is increasing with time for most node types. So what if instead we define states like this:

$$
u = \frac{1}{t - t_0 + 1}  \int_{t_0}^t q\text{d}\tilde{t}
$$

which is almost the same as the average of the flow rate since the start of the simulation. The $+1$ in the denominator is just there to avoid division problems at the start of the simulation.

The differential equation for a state is then, using that the cumulative flow is given by $(t - t_0 + 1)u$,

$$
\left[(t - t_0 + 1)u\right]' = q,
$$

or in $u'= f(u,p,t)$ form

$$
u'= \frac{q - u}{t - t_0 + 1}.
$$

This might introduce different accuracy problems, but it's worth an experiment. This would be a fix of https://github.com/Deltares/Ribasim/issues/1897, in combination with https://github.com/Deltares/Ribasim/pull/1904.

**Comment by SouthEndMusic** [comment]
In this formulation, the total flow over an edge over the latest timestep is given by

$$
(t_\text{prev} + \Delta t - t_0 + 1)u - (t_\text{prev} - t_0 + 1)u_\text{prev} = (t_\text{prev} - t_0 + 1)(u - u_\text{prev}) + u\Delta t
$$

**Comment by evetion** [comment]
Github mobile has no math support, so this issue was completely unreadable. On desktop though, this seems like an interesting experiment. It's part of the normalization approach, but nice thought to be doing so over time instead of relating it to total flow or similar.

**Comment by visr** [comment]
Seems like a good idea to try out. I guess we'd be able to keep the cumulative BMI variables around and just calculate them on the spot.

**Comment by SouthEndMusic** [comment]
A better formulation of the states might be

$$
u = \frac{1}{t + \tau}\left(\tau q|_{t=0} + \int_0^t q \text{d} \tilde{t}\right),
$$

where $\tau$ is some length of time which we can hardcode at e.g. 1 second, and using that always $t_0 = 0$ in the core. This formulation has the nice properties that:

1. Division by zero is prevented
2. It doesn't introduce as much non-linear behavior at the start of the simulation as the formulation above
3. If a flow is constant over the simulation, this state will always be equal to that constant flow

What it essentially computes is the average flow as if there was a period of length $\tau$ before the start of the simulation with constant flow $q|_{t=0}$ (the flow at $t = 0$).
