### ISSUE TITLE
NetCDF-CF support by Ribasim_python

### ISSUE THREAD

**Issue by gijsber** [Deltares/Ribasim#193]
Ribasim_python should get NetCDF-CF support,

i.e. you provide a netcdf which is converted to arrow or you ask for arrow results in NetCDF

**Comment by visr** [comment]
It's not yet fully clear to me if something is needed inside ribasim-python for that. Internally we use pandas dataframes. So if users can convert their netcdf to dataframes, with xarray for instance, then ribasim-python doesn't need to depend on xarray or [xugrid](https://github.com/Deltares/xugrid), like the example in #183.
