### ISSUE TITLE
Formulating the problem

### ISSUE THREAD

**Issue by SouthEndMusic** [Deltares/Ribasim#195]
Here I want to derive the problem that Ribasim solves (for my own understanding and for the docs). Please check it for correctness and completeness. 

The problem is of the form

$$
\frac{\text{d}\mathbf{u}}{\text{d}t} = f(\mathbf{u},p(t)),\quad t \in [t_0,t_\text{end}],
$$

i.e. a system of coupled first order ordinary differential equations, with initial condition $\mathbf{u}(t_0)= \mathbf{u}_0$.

The model is given by a directed graph, consisting of a set of nodes (or vertices) $V$ and edges $E$. Let $V$ be the set of node id's and let $E$ be the set of ordered tuples $(i,j)$ meaning that node $i$ is connected to node $j$.

We can split the set of nodes into two subsets $V = B \cup N$, where $B$ is the set of basins and $N$ is the set of non-basins. The basins have an associated storage state and the non-basins dictate how water flows to or from basins. Although (I think) it is currently not checked in the code, basins and non-basins should alternate in the graph (with some exceptions), since only then the flow-behavior is defined.

$\mathbf{u}(t)$ is given by all the states of the model, which are (currently) only the storage of the basins. Given a single basin with node id $i \in  B$, the equation that dictates the change of its storage over time is given by

$$
\frac{\text{d}S_i}{\text{d}t} =
\sum_{(i',j') \in E | j' = i} Q_{i',j'} - \sum_{(i',j') \in E | i' = i} Q_{i',j'} + F_i(t).
$$

Here $Q_{i,j}$ is the flow along an edge, where the graph direction dictates positive flow. So the first term denotes flow towards the basin, the second one denotes flow away from the basin, and the third term denotes external forcing. $F_i(t)$ is given by input data, and $Q_{i' ,j'}$ is determined by the type of nodes that connect to that edge.

The non-basin non-boundary nodes conserve water, which for a non-basin node with node id $i$ can be formulated as 

$$
\sum_{(i',j') \in E | j' = i} Q_{i',j'} = \sum_{(i',j') \in E | i' = i} Q_{i',j'},
$$

e.g. the total inflow is equal to the total outflow. We can also look at the global water balance, where change of the volume of water in the entire system is given by forcing and boundary nodes (denoted $\partial V$):

$$
\sum_{i\in B} \frac{\text{d}S_i}{\text{d}t} = \sum_{i \in B} F_i(t) + \sum_{(i',j')\in V | i' \in \partial V} Q_{i',j'} - \sum_{(i',j')\in V | j' \in \partial V} Q_{i',j'}
$$

where the first term is the sum of the forcing terms and the other terms are the inflow and outflow boundaries respectively.

**Comment by Hofer-Julian** [comment]
> That means that forcing is not unique to basins, and not all non-basins conserve water. Those that just regulate flow between basins do, but in the future we will add more consumer node types, that can take out or introduce water into the system. Perhaps it would be good to classify the node types in the code as well at some point.

That sounds like a good idea to me
