### ISSUE TITLE
Classify nodes as (non)-conserving

### ISSUE THREAD

**Issue by SouthEndMusic** [Deltares/Ribasim#199]
As mentioned by @visr in https://github.com/Deltares/Ribasim/issues/195#issuecomment-1539641160

**Comment by visr** [comment]
Thanks for creating the issue. From the documentation it should be clear if nodes conserve water or not. We don't need it yet, but I was thinking such a classification could be useful if it is in the API, to make sure we can for instance ignore conservative nodes when creating water balance overviews and such. Though best to wait with implementing this until we have a clear use case.
