### ISSUE TITLE
Conceptualisation: convert two-step MODFLOW MOZART coupling to one-step coupling

### ISSUE THREAD

**Issue by Huite** [Deltares/Ribasim#2]
Current MODFLOW coupling occurs with two steps: weir area (if available), then a grid cell correction. This can be simplified to just grid cell correction, by creating a 3D array (volume, y, x) with e.g. 10-15 segments for the volume dimensions, to query the stage. This stage can then be instantly set for all river / boundary stages per LSW.

This has the advantage of presenting one single source of truth, which is relatively easy to check and visualize (with some groupby's per LSW or weir area). It also fully eliminates the concept of the weir area, which is known to the coupling only, simplifying it to the Bach concepts (LSW) and MODFLOW concepts (cells).

**Comment by Huite** [comment]
Best to start with a simple integration test. We can rely on the modflow.jll to ease CI for now (rather than imod-coupler).

Specifically, test with a synthetic model, with three circular basins in Bach.

**Comment by gijsber** [comment]
Q1: is the level correction dependent on the actual situation e.g. if the head is above or below the drainage pipes ?

Q2. If so, how do we see this working? Do we have two prepared correction tables where a certain condition determines whether correction 1 or correction 2 is applied ? Or is this something that needs to be computed on the spot ?

Q3. How do we actually create those tables ? With new model schematisations we cannot copy the former Mozart values anymore
