### ISSUE TITLE
Validation network connectivity

### ISSUE THREAD

**Issue by gijsber** [Deltares/Ribasim#200]
We need to define and validate the network connectivity rules.
Basins need some connector nodetypes inbetween, some non-basin nodetypes are not connectors. Could be related to additional characterization needs such as #199 

Some inpiration: a flexible schema definition from the network editor of Ribasim 8:
[NetworkValidationRules.zip](https://github.com/Deltares/Ribasim/files/11432230/NetworkValidationRules.zip)
http://fews.wldelft.nl/schemas/version1.0/topology-editor-schemas/networkValidationRules.xsd

**Comment by visr** [comment]
The place in the code has been reserved :)

https://github.com/Deltares/Ribasim/blob/6a8183d439000c75914113b342a6c07574337af0/core/src/solve.jl#L17-L30

**Comment by evetion** [comment]
- Also include the information network (control)

**Comment by evetion** [comment]
These will be hardcoded rules in Julia, no external file parsing/generation yet.
