### ISSUE TITLE
Compose definition-of-done and put in template

### ISSUE THREAD

**Issue by gijsber** [Deltares/Ribasim#205]
If we agree on this list we can move it to an issue template

Typically new node-types require update of:
- [ ] core\src\create.jl
- [ ] core\src\validation.jl
- [ ] core\src\solve.jl

Updating other jl-files may depend on needs

ribasim_python
- [ ] newnodetype.py with associated implementation in python\ribasim\ribasim\.
- [ ] add/update nodetype to python\ribasim\ribasim\model.py
- [ ] add/update nodetype to python\ribasim\tests\conftest.py
- [ ] add/updae nodetype to python\ribasim_api\tests\conftest.py

documentation
- [ ] update docs\core\equations.qmd
- [ ] update docs\core\usage.qmd
- [ ] update docs\python\examples.ipynb
- [ ] update docs\schema\*.json

QGIS
 - [ ] update qgis\core\nodes.py

**Comment by evetion** [comment]
When a new node type is created, one needs to run
`julia gen_schema.jl` to create new jsonschemas in the docs folder, and ` datamodel-codegen --use-title-as-name --input docs/schema/root.schema.json --output python/ribasim/ribasim/models.py` to generate the Python models from it.

**Comment by visr** [comment]
The `--project=docs` here should activate this environment, which has JSON3: https://github.com/Deltares/Ribasim/blob/main/docs/Project.toml

The reason we use a separate environment is to avoid having to add JSON3 as a dependency for Ribasim itself.

If you haven't done so before, you first need to instantiate your docs environment, you could run `julia --project=docs`, followed by running `instantiate` in the Pkg mode (`]`). Or simply running `up` also does the trick.

https://deltares.github.io/Ribasim/contribute/core.html#run-ribasim-simulations

**Comment by SouthEndMusic** [comment]
Ok, thanks for the clarification.
