### ISSUE TITLE
General model description

### ISSUE THREAD

**Issue by visr** [Deltares/Ribasim#221]
We now have a formal model description: https://deltares.github.io/Ribasim/core/equations.html#formal-model-description
We still need a better informal general description. The closest we have is on the main page: https://deltares.github.io/Ribasim/, but that needs an update.

We need to make it clear what a node is and what an edge is, and the role of the Basin node. This should go well with #207 which also describes an overview of the different node types, a bit like in https://deltares.github.io/Ribasim/python/reference/Model.html#ribasim.Model.

We need to make clear how Basin nodes represent areas, like the blue dots here, and that edges don't represent any area. Images like this, but less obviously drawn in MS Paint.
![image](https://github.com/Deltares/Ribasim/assets/4471859/22303bac-7515-4c61-94f3-72ac2b7d74cd)

**Comment by SouthEndMusic** [comment]
I started a script to make such images:
![Ribasim_simple](https://github.com/Deltares/Ribasim/assets/74617371/cb38d449-53ea-4a69-bbb7-1ffbfd133e80)

If anyone is interested in the script let me know where I should put it.

I think it would be helpful to add in the documentation that:
- The graphs are *not* simply [map graphs](https://en.wikipedia.org/wiki/Map_graph) like [this];(https://ds055uzetaobb.cloudfront.net/brioche/uploads/lRC3MIbnUy-germany_map_2.png?width=1200)
- The basin connections can consist of more than one node.

**Comment by visr** [comment]
Yeah that image captures it well.
Here are some extra points, in Dutch, since I needed to make a slide.

![image](https://github.com/Deltares/Ribasim/assets/4471859/6f52f64f-85f7-4c41-b702-5d0090c31bbb)

**Comment by SnippenE** [comment]
Comment Fatima: Good example for reference is the Ribasim7 manual

**Comment by visr** [comment]
https://deltares.github.io/Ribasim/ has been improved. I don't think we need to keep this open.
