### ISSUE TITLE
CI for QGIS plugin

### ISSUE THREAD

**Issue by visr** [Deltares/Ribasim#231]
Currently there is none. We currently only manually check the plugin, see #202.

We should see if we can test at least a part of the plugin automatically. QGIS is available in Conda so perhaps that can be used, for instance to check if it loads properly.

Also Black and Ruff are only run on the python directory, not the qgis one. (EDIT: fixed)

**Comment by Hofer-Julian** [comment]
> Also Black and Ruff are only run on the python directory, not the qgis one.

That should be easy to fix.

For the GUI tests we could use https://pytest-qt.readthedocs.io/en/latest/_modules/pytestqt/qtbot.html

**Comment by evetion** [comment]
For this sprint, timebox this to 2 hours so we can at least test the plugin is valid.

**Comment by evetion** [comment]
What do you think if we move the plugin to `qgis/Ribasim` and rename the plugin like that as well?
