### ISSUE TITLE
Updating schema definition

### ISSUE THREAD

**Issue by SouthEndMusic** [Deltares/Ribasim#237]
Schema classes are not updated to the new method (see e.g. pump) in  `python/ribasim/ribasim/node_type.py` for node_type = edge, level_boundary, manning_resistance, model, node, terminal.

Also update this in contributing docs (2.1).

**Comment by SouthEndMusic** [comment]
@visr this probably also explains why no tests failed despite not all files being present in `docs/schema`?

**Comment by visr** [comment]
Yeah that must be the reason, since it was with the LevelBoundary, which is in your list above.

To be precise, the JSON file don't have to be present, but they are used to create the code in models.py, which was lacking the schema definitions.
