### ISSUE TITLE
Properly inferring node IDs from node type objects

### ISSUE THREAD

**Issue by SouthEndMusic** [Deltares/Ribasim#260]
I made a wrong assumption when I wrote my model validations. I assumed that every node type class has a mandatory `static` field with all node IDs for that node type appearing at least once in its `node_id` column:

https://github.com/Deltares/Ribasim/blob/a4a3bebb4de86cc513869dbc104d89861488b3aa/python/ribasim/ribasim/model.py#LL191-L197

_Originally posted by @SouthEndMusic in https://github.com/Deltares/Ribasim/pull/259#discussion_r1211930303_

This is not the case; for instance in for `TabulatedRatingCurve` the node IDs are distributed over the `static` and `time` fields, and this was incorrectly corrected in https://github.com/Deltares/Ribasim/pull/259.

**Comment by visr** [comment]
Ah right, good to have this in a separate issue. I just commented this on the other thread: https://github.com/Deltares/Ribasim/pull/259#discussion_r1212135431

I assume the core tests are now broken on main? Would be good to work on this tomorrow.

**Comment by SouthEndMusic** [comment]
Yep a Julia test fails now, I'll fix it.
