### ISSUE TITLE
 Make debugging of ribasim_api easier

### ISSUE THREAD

**Issue by Hofer-Julian** [Deltares/Ribasim#286]
Martijn suggested we could add API to dump model state and extract from Python

**Comment by SnippenE** [comment]
@visr : can you add your ideas to this issue?

**Comment by visr** [comment]
I don't really have many concrete ideas. It really depends on the kind of issues that couplers are running into. If those issues arise we can create concrete issues, and close this.

One issues that will help with this is #1351.
