### ISSUE TITLE
node id’s between connection not in attribute table

### ISSUE THREAD

**Issue by SnippenE** [Deltares/Ribasim#288]
Vraag Noortje Romeijn (Witteveen en Bos): 

Voor TKI NHI ben ik bezig om Ribasim te verkennen. Ik heb hier een paar vragen over:

Ik heb de voorbeelden gevolgd op deltares.github.io/ribasim  en dat lukt. Nu probeer ik zelf een Ribasim model met behulp van de QGIS plugin op te zetten. Bij het maken van edges tussen de nodes komen de node id’s van de nodes waartussen ik een connectie wil hebben niet in de attribute table terecht (terwijl ik zie dat dit bij het voorbeeld model wel het geval is). Als ik het model vervolgens wil runnen, krijg ik een error waarin een verwijzing staat naar simple graphs en missing. Ik denk dat dit met elkaar te maken heeft. Hoe kan ik dit oplossen? 

Is er ergens een overzicht beschikbaar van wat de nodes precies inhouden en welke informatie je minimaal aan de nodes moet meegeven om een werkend model te krijgen? Ik vraag me ook af hoe het zit met beginvoorwaarden. Het lijkt alsof dit nergens wordt meegegeven in het voorbeeld model.

Ik hoor het graag.

Vriendelijke groet,

N. Romeijn (Noortje)
Projectingenieur Watermanagement | Wateroverlast

[noortje.romeijn@witteveenbos.com](mailto:noortje.romeijn@witteveenbos.com) 

Witteveen+Bos

**Comment by SnippenE** [comment]
related to #2

**Comment by SouthEndMusic** [comment]
Over de beginvoorwaarden: je kan de begin storages meegeven met [Basin / state](https://deltares.github.io/Ribasim/core/usage.html#basin-state). Dat is op dit moment geen verplichte input, in de Julia core wordt bij het ontbreken voor alle basins een storage van 1.0 m^3 aangenomen. @visr heeft aangegeven dat het wellicht goed is dat dit verplichte input wordt. Wellicht is het ook intuitiever om begin level aan te geven in plaats van begin storage?

**Comment by SouthEndMusic** [comment]
Over het overzicht van de nodes: [usage](https://deltares.github.io/Ribasim/core/usage.html) geeft aan welke data bij welk node type hoort (het lijkt me inderdaad goed om hierbij aan te geven wat verplicht is en wat niet). [equations](https://deltares.github.io/Ribasim/core/equations.html) geeft een theoretische achtergrond per node type.

**Comment by gijsber** [comment]
begin level is inderdaad vanuit de hydrologische gebruiker gewenst

**Comment by visr** [comment]
> Bij het maken van edges tussen de nodes komen de node id’s van de nodes waartussen ik een connectie wil hebben niet in de attribute table terecht.

Dit is inderdaad een probleem, die horen daar wel te staan. De plugin vult deze waardes zelf in op basis van het begin en eindpunt van de lijnen. Hier een voorbeeld waar ik zojuist een nieuwe edge heb getekend maar nog steeds in edit mode zit, de attributen zijn nog niet ingevuld:

![image](https://github.com/Deltares/Ribasim/assets/4471859/6c0a61b1-e238-4f02-96bd-2b1cd602e00d)

En nadat ik op het potlood heb geklikt om uit edit mode te gaan, zijn ze ingevuld:

![image](https://github.com/Deltares/Ribasim/assets/4471859/2827885c-1712-423b-97b5-77b9654d3f59)

Er is wel een bug nog moet worden opgelost, wat wellicht het probleem was hier. Als je wijzigingen opslaat met het rechtericoon hier, ipv het linker icoon, dan wordt er niets automatisch ingevuld:

![image](https://github.com/Deltares/Ribasim/assets/4471859/481672c8-f06c-4bd9-aed9-739d75782d5b)
