### ISSUE TITLE
Implement externalized validation rules in Python/QGIS

### ISSUE THREAD

**Issue by SnippenE** [Deltares/Ribasim#290]

**Comment by Huite** [comment]
Worth noting that recent QGIS releases seem to have been getting quite rich Python installation: e.g. both geopandas and scipy are available. Since scipy has a collection of sparse graph routines, this might be helpful: https://docs.scipy.org/doc/scipy/reference/sparse.csgraph.html

**Comment by visr** [comment]
Closing in favor of #277.
