### ISSUE TITLE
QGIS: data tables don't appear

### ISSUE THREAD

**Issue by visr** [Deltares/Ribasim#291]
When loading one of the example models, it only loads the Edge and Node layers for me. The data tables that are in the GeoPackage don't show up like they did before. If I click on one of the data tables in the Nodes tab of the Ribasim widget, an empty data table appears. That is expected if the table doesn't exist, but this also happens for tables that do exist, like "Pump / static" in the basic model.

![image](https://github.com/Deltares/Ribasim/assets/4471859/412cbd57-c5f2-4f46-b82b-a3f925c0a908)

This is using QGIS 3.30.3 and current main branch.

**Comment by SouthEndMusic** [comment]
Is this the issue discussed in https://github.com/Deltares/Ribasim/issues/288?
