### ISSUE TITLE
Post-processing MODFLOW model to generate standalone Ribasim run

### ISSUE THREAD

**Issue by Huite** [Deltares/Ribasim#3]
One useful feature is to run Ribasim without coupling to MODFLOW, as a post-processing tool (e.g. as a way to check an existing MODFLOW model). This should generate net water budgets, which are used as drainage and infiltration flows.

**Comment by gijsber** [comment]
Q1. should we accommodate Ribasim stand-alone to run dry (that might create solver issues requiring preismann slots or alike)

**Comment by SnippenE** [comment]
@visr can this issue be closed. If the functionality is available we could close this after adding how to do this in the documentation

**Comment by Huite** [comment]
This question becomes relevant to compare standalone versus MODFLOW runs.

Arguably, such code might better belong in a hydromt repository, using imod functionality to compute zonal water balances (based on ribasim basins), and returning it as transient infiltration / drainage tables for the Ribasim model.

**Comment by visr** [comment]
Yes I agree that such code would fit better in a hydromt repository. The functionality is useful, and I'm sure we need it at some point, though not urgent unless it is needed for testing coupling.
