### ISSUE TITLE
Investigate how to deal with binary dependencies

### ISSUE THREAD

**Issue by Hofer-Julian** [Deltares/Ribasim#30]
Working on Ribasim involves a couple of binary dependencies.
We currently deal with that in different manners:
- images for documentation are stored in issue https://github.com/Deltares/Ribasim.jl/issues/1
- image output of Jupyter notebook https://github.com/Deltares/Ribasim.jl/blob/main/docs/demo.ipynb is created on @visr's PC
- test data is downloaded during test run from https://github.com/visr/ribasim-artifacts/releases/tag/v0.1.0

All of that is hard to keep track of and blocks further automatization.
One of the reasons why that is done that way is to avoid blowing up the repository size.
`git-lfs` should at least solve that problem.
@evetion: Is that a feasible option considering limits within the Deltares GitHub organization?

**Comment by Hofer-Julian** [comment]
My experience with `git-lfs` is similar.

>  I'm even fine with comitting all current data into git and dealing with it at a later stage

For the doc images, I would prefer that too.
They shouldn't be too big, and they will not change frequently.

For the Jupyter notebook, we could leave the images in the output and add a weekly CI job to check if they should be regenerated.
Maybe with a Julia equivalent of https://github.com/computationalmodelling/nbval

For the test data, we could add a git submodule.
Of course, submodules have some of the annoyances of `git-lfs`.

What do you say @visr?

**Comment by evetion** [comment]
I did discuss this before with Martijn, and we would also be fine with a script that just updates all binary files from X. The current problem we had is that we don't have easily have a shared folder somewhere with a public (or even single pass private) link. Might be possible in Azure with our accounts.

But then again, I somewhat prefer the git submodule solution.

**Comment by Hofer-Julian** [comment]
> But then again, I somewhat prefer the git submodule solution.

Me too.
Mostly because it is naturally reproducible.

The data is current in Martijn's personal repo.
I think we should move that to the Deltares namespace first.

**Comment by evetion** [comment]
Like https://github.com/Deltares/Ribasim-artifacts. Besides, the data is on Sharepoint.

**Comment by visr** [comment]
Coming back to the list:

- images for documentation are stored in issue https://github.com/Deltares/Ribasim.jl/issues/1
- image output of Jupyter notebook https://github.com/Deltares/Ribasim.jl/blob/main/docs/demo.ipynb is created on @visr's PC
- test data is downloaded during test run from https://github.com/visr/ribasim-artifacts/releases/tag/v0.1.0

The images are not really an issue, they could be in #1, in another issue, or when we have code to generate them, we can generate them during doc builds, like [here](https://github.com/Deltares/Ribasim/blob/a464bffb48aa21a9a3ae130887d20ace982a0bbf/docs/core/equations.qmd#L110-L147).

The notebook image output is solved, they are now automatically created by the docs job, and not checked in.

We don't use test data anymore, we generate all test models in `ribasim_testmodels`.

For https://github.com/Deltares/Ribasim-NL we will have a similar issue, currently looking at https://deltares.thegood.cloud/, for which it seems we can generate either public or private access links. But that is probably best tackled in that repository, so closing this issue.
