### ISSUE TITLE
Linear continuous control

### ISSUE THREAD

**Issue by SouthEndMusic** [Deltares/Ribasim#310]
The current control implementation is discrete, in the sense that the control can bring the controlled nodes in a finite number of predefined control states. Many use cases however seem to require continuous control, so here is a concept.

## Linear continuous control concept

We introduce a new node type called say `LinearContinuousControl` and call the other control node type `DiscreteControl`. One associated schema to `LinearContinuousControl` is similar to the current `condition` schema for `Control`; it has the following columns:
-  `node_id`: the ID of the `LinearContinuousControl` node
- `listen_node_id`: the ID of the node being listened to
- `variable`: the variable of the node being listened to
- `weight`: a weight for this variable

Based on this, each control node will compute a linear combination given the values of the variables being listened to and their associated weights. Then the question is how we use this value to update one or more parameters of the controlled nodes (specified by the same control edges that are already implemented, or we could make different edge types for different types of control). 

One way this linear combination value can be used is to interpolate between two sets of parameters defined in a nodes `static` table with special control states like "lower" and "upper" (although then the name static does not quite apply anymore). What is nice about this is that we can say that the interpolation value should be in [0,1] and if it is not it gets clipped to the nearest value (either 0 for "lower" or 1 for "upper") so that the controlled variables are bounded. 

The implementation for this is probably simpler than for the discrete control, because this control type is simply applied at every time point so it does not need a callback. A function called at the start of `water_balance!` can handle this.

**Comment by SouthEndMusic** [comment]
If users want to be super fancy we could even allow them to apply an activation function to the linear combination first, although then the relationship is no longer linear.

**Comment by gijsber** [comment]
Looks nice and I think this will work, BUT I doubt about the ability to get proper parameterization in place without too much hassle.
I recommend that we start with a PID-controller (https://nl.wikipedia.org/wiki/PID-regelaar) as this is a very common control concept, well known in the water management world and therefore easier to parameterize with some rule of thumb.

**Comment by SnippenE** [comment]
Paused until PID control is insufficient #329 #320
