### ISSUE TITLE
Python tests reading model results

### ISSUE THREAD

**Issue by SouthEndMusic** [Deltares/Ribasim#311]
I wrote the method `Model.get_control_record` to print a human readable version of the control record, which is an output of the Julia core. Therefore the testing of this method has to happen after a Julia core run, which is tricky. I suppose that this the first python functionality which is post- in stead of pre-processing, which we might want to avoid altogether?

**Comment by Hofer-Julian** [comment]
>  Therefore the testing of this method has to happen after a Julia core run, which is tricky. 

You can do something similar to we do in the [notebook](https://github.com/Deltares/Ribasim/blob/main/docs/python/examples.ipynb):

```python
from subprocess import run

run(
    [
        "julia",
        "--project=../../core",
        "--eval",
        f'using Ribasim; Ribasim.run("{datadir.as_posix()}/control/control.toml")',
    ],
    check=True,
)
```

> I suppose that this the first python functionality which is post- in stead of pre-processing, which we might want to avoid altogether?

I would say it's fine to include post-processing in Ribasim Python

**Comment by SouthEndMusic** [comment]
@Hofer-Julian Yes I wrote a test like that but @evetion had some reservation about that, something about the assumption that Julia is available.

**Comment by Hofer-Julian** [comment]
> @Hofer-Julian Yes I wrote a test like that but @evetion had some reservations about that, something about the assumption that Julia is available.

I guess, that needs more discussion then. Just like we can expect Python for our Julia tests, should it be allowed to expect Julia for our Python tests in my opinion :)
