### ISSUE TITLE
TOML node type sections

### ISSUE THREAD

**Issue by visr** [Deltares/Ribasim#316]
We [probably](https://github.com/Deltares/Ribasim/issues/170) support this in TOML

```toml
[tabulatedratingcurve]
static = "path/to/some/file.arrow"
```

I assumed we had TabulatedRatingCurve (the node type) as a section name, but we use this, extracted from all the schemas:

```julia
julia> Ribasim.nodetypes
10-element Vector{Symbol}:
 :tabulatedratingcurve
 :linearresistance
 :basin
 :fractionalflow
 :control
 :levelboundary
 :pump
 :flowboundary
 :manningresistance
 :terminal
```

I'd like to avoid this spelling since it is hard to read, and use `flow_boundary` for instances, and `FlowBoundary` for the type.

However we cannot use capitals or underscores in the Legolas schema names, so I'm not sure how to fix this. It's hard to automatically go from `flowboundary` to `FlowBoundary` (or `flow_boundary`).

https://github.com/Deltares/Ribasim/blob/15f4499a955378fa82f7c13e8049cb8d62f0b834/core/src/validation.jl#L2

**Comment by Hofer-Julian** [comment]
> However we cannot use capitals or underscores in the Legolas schema names

That is unfortunate, I wonder what made them disallow underscores.
If they allow uppercase letters, it should still be easy to transform names automatically

**Comment by visr** [comment]
I wouldn't say it is that urgent, though it's a breaking change so best not to wait too long either.

**Comment by evetion** [comment]
This could be partially backwards compatible:

```
[tabulatedratingcurve] could be aliased ([TabulatedRatingCurve])
static = "path/to/some/file.arrow"
```

However, should `static` then also be `Static`?

**Comment by visr** [comment]
I don't think it is important to be backwards compatible, since it's not used yet. And `static` can IMO stay lowercase.
