### ISSUE TITLE
Test QGIS plugin

### ISSUE THREAD

**Issue by Hofer-Julian** [Deltares/Ribasim#320]
We have an ever-growing of QGIS issues, and we typically notice them weeks after it broke in the code.
The data loading was broken for three months and nobody noticed: https://github.com/Deltares/Ribasim/issues/291
That is because we don't have any kind of automatic tests for the QGIS plugin at the moment.
This is not only the case because it was never prioritized, but also because it is exceptionally hard to do.
This is the case because of two reasons:
- GUIs are harder to test than CLI applications or libraries
- We don't control the whole stack

To elaborate on the second point: We don't ship QGIS with our plugin, but expect users to install the plugin on top of their existing QGIS application. This means that we are confined by QGIS' API, making testing (and many other things) much harder.

I think this issue needs further discussion, mostly because it is unclear to me if the QGIS plugin is valuable enough to justify that kind of investment. https://github.com/Deltares/Ribasim/issues/321

**Comment by evetion** [comment]
Let's test whether it works now (with QGIS bugs fixed)

**Comment by gijsber** [comment]
Manual checks needed on:
- [ ] adding nodes and edges
- [ ] inspect and change the attributes for the tables
- [ ] visualize the output in timeseries graphs
- [ ] visualize the output in animated maps
