### ISSUE TITLE
Start of P(ID) controller

### ISSUE THREAD

**Issue by SouthEndMusic** [Deltares/Ribasim#323]
As motivated in https://github.com/Deltares/Ribasim/issues/322. First steps:

- [ ] Introduce the PID controller node which for now only supports P
- [ ] Have it control a pump which has associated minimum and maximum flow rates

**Comment by gijsber** [comment]
Example controller settings from Landelijk Sobek model (LSMKRW) 
node: PKN_pop_108SASA
Pump capacity 22.5m3/s
Suction side switch on 6.5mNAP, suction side switch off 6.4mNAP
Setpoint is a time series
![image](https://github.com/Deltares/Ribasim/assets/14976756/d4f01ace-1abe-4cec-8254-6377f0ccafb9)

node ZWLM_27
Pump capacity 4.5m3/s
Suction side switch on 17.25mNAP, suction side switch off 17.15mNAP

![image](https://github.com/Deltares/Ribasim/assets/14976756/30c4b738-51d2-45e5-96a6-217c283d5ede)

**Comment by SouthEndMusic** [comment]
> Example controller settings from Landelijk Sobek model (LSMKRW) node: PKN_pop_108SASA Pump capacity 22.5m3/s Suction side switch on 6.5mNAP, suction side switch off 6.4mNAP Setpoint is a time series
> node ZWLM_27 Pump capacity 4.5m3/s Suction side switch on 17.25mNAP, suction side switch off 17.15mNAP

@gijsber thanks for the data. Do I understand correctly that this is not PID control but discrete control (e.g. the pumps are either on or off), or does the second one interpolate between the values in the table? Does the Sobek model also contain profile data?

At this moment I do not know how to incorporate the deadband (which I assume is the tolerance around the setpoint), I can image that to be a criterion for optimization.

**Comment by gijsber** [comment]
@SouthEndMusic I'll have to ask Geert Prinsen for that, but this were the pump-related control types I could identify. they look discrete indeed. and yes, profile data is available. I could check whether the gate or weir controllers have settings that are more PID like. Maybe @visr has been digging into D-RTC more with some example.

For the deadband: this indeed is the lower/upperbound which indicates when the pump is turned on.

**Comment by gijsber** [comment]
Maybe this one is useful as well: the user manual of D-RTC Tools: https://usermanual.wiki/Pdf/DRTCUserManual.1356732301.pdf

**Comment by gijsber** [comment]
@SouthEndMusic I also have posted a more recent version posted in: n:\Deltabox\Postbox\Gijsbers, Peter\D-Real_Time_Control_User_Manual.pdf (19mb)
Page 71 contains some parameterization including the various K-factors
