### ISSUE TITLE
ManningResistance cannot be connected to a LevelBoundary

### ISSUE THREAD

**Issue by Huite** [Deltares/Ribasim#334]
Connecting a ManningResistance to a LevelBoundary is theoretically sound: there's a level to use. I think the validation doesn't allow it:

```
ERROR: AssertionError: node_id 102 not a Basin
```

Of course, the logic probably doesn't exist either...
But we should at least consider adding it.

**Comment by visr** [comment]
It's because the bottom is missing. I made this PR last week: #330. Though if you know how to actually solve it that may be better.

**Comment by Huite** [comment]
Could we just use the bottom of the associated node instead? I guess we have to special case it in the formulate function?
