### ISSUE TITLE
Automatically close issues when moved to "done"

### ISSUE THREAD

**Issue by Hofer-Julian** [Deltares/Ribasim#340]
If we close issues, we have a workflow to move them to "done" in our Kanban board.
However, the other way around doesn't work yet.

GitHub doesn't provide this functionality out of the box, but there is a GitHub Action we could set up: https://github.com/dessant/issue-states.

**Comment by evetion** [comment]
- [ ] Ask @savente93 about similar behavior in HydroMT.

**Comment by savente93** [comment]
There are built in functionalities in GH that we use for this, though they have to be enabled by and admin. I'd be happy to discuss more of it when we're in the office again,but if you're curious in the mean time see these docs: https://docs.github.com/en/issues/planning-and-tracking-with-projects/automating-your-project/using-the-built-in-automations They are somewhat limited (especially on the free tier) but work nicely for the most common use cases that tended to cause the most problems for us

**Comment by visr** [comment]
We are using some of the default workflows, including moving issues to Done if they are closed. But if we move them to Done in the project they don't get closed automatically. I don't see a built-in way to do that.

![image](https://github.com/Deltares/Ribasim/assets/4471859/6991dd93-3a23-4fe8-a5e0-918dc7d1b16d)

![image](https://github.com/Deltares/Ribasim/assets/4471859/afc7e2ca-aa93-4a8d-ae3b-ac5b038e47c1)

For now we need to remember to close the issue ourselves if it isn't closed automatically by a linked PR, which isn't a big problem.

**Comment by visr** [comment]
The Action from PR #359 didn't work, reverted in #360.
