### ISSUE TITLE
empty dirs in build

### ISSUE THREAD

**Issue by visr** [Deltares/Ribasim#343]
The contents of the latest ribasim_cli.zip from TeamCity has duplicated dirs with a trailing underscore:

```
bin\
bin_\
lib\
lib_\
share\
share_\
LICENSE
README.md
ribasim.cmd
```

The ones with an underscore are empty, and the binary is working fine, but it would be good to delete those empty dirs.

Note: this applies to every dir, also below the root level, e.g:

```
share\julia\artifacts\17c7cf43a62bb170fc0e23af523744809703d7e2_\
```

**Comment by Hofer-Julian** [comment]
I've just unpacked the latest zip with the built-in windows tool as well as 7zip.
Neither of those produced those directories.

Which tool did you use @visr?

**Comment by visr** [comment]
Oh wow. I used Total Commander, but unpacking with 7-zip works fine.

**Comment by Hofer-Julian** [comment]
Yet another reason to not use total commander :P
