### ISSUE TITLE
Add weir object with opposite characteristics of pump

### ISSUE THREAD

**Issue by SnippenE** [Deltares/Ribasim#347]
See #322

A weir object is introduced in the physiscal layer with the same characteristics as the pump (min.capacity, max.capacity, static flow rate(s), transient flow rate, controllable flowrate), but an opposite flow direction (from upstream to downstream following gravity)

**Comment by gijsber** [comment]
Basically this could be a naming discussion. If we rename the current Pump object to something more universal, we do not need a second implementation. 
Let's pause this one for the moment
