### ISSUE TITLE
Add every Julia file in its own module

### ISSUE THREAD

**Issue by Hofer-Julian** [Deltares/Ribasim#372]
Until recently, we had a single module `Ribasim` and included our source files into it.
@evetion introduced a module for `config` in his last PR https://github.com/Deltares/Ribasim/pull/368 since he otherwise would have to deal with name conflicts.

I think we should create a module for every single Julia file.

Advantages:
- less potential for name conflicts
- if we import symbols like [here](https://github.com/Deltares/Ribasim/blob/b23b7b26e0233326956edf6cea2be8c598a82124/core/src/Ribasim.jl#L30) it also makes it clear which part of the module is private to the module and which is supposed to be used by other modules as well.
- It is the expected behavior for people coming from languages like Python

**Comment by evetion** [comment]
I see where you're coming from, but this is not a standard practice in Julia packages. It makes sense to do it for really separate concerns (but normally I would split into another package), or when required due to conflicts (like the config), but not for every file.

**Comment by Hofer-Julian** [comment]
Fair enough.
