### ISSUE TITLE
Prevent oscillations between control states in discrete control

### ISSUE THREAD

**Issue by SouthEndMusic** [Deltares/Ribasim#374]
This issue is a refinement of the following in https://github.com/Deltares/Ribasim/issues/293:

> Make sure no fast oscillations occur between control states by setting minimal times for control states (time keeping already implemented)

The second entry of the values of the `Control.control_state` dictionary in the Julia core is meant for the start time of that control state, which is set in `control_affect!` when a new control state is set, but this start time is not used yet. The idea is that a control state only changes to a different one if the current control state has been active for some `minimal_duration`, which I think not yet part of a schema. 

This is *not* as simple as adding this duration condition when setting a control state, because the minimal time probably ends in between condition changes. So, the minimal time check requires its own conditions in the `VectorContinuousCallback` for discrete control, which have to be part of the control state change logic in `control_affect!`.

**Comment by gijsber** [comment]
Hi @SouthEndMusic ,

I think we should  go for a solution that is closer to hydrological practice. It does need a change of the DiscreteController.

Hydrological practice is as follows:
For a basin we have a target_waterlevel (setpoint) defined as well as a maximum water level and a minimum water level.
Let's assume it is connected to two pumps, one can add water, the other takes water out.

When the minimum water level is reached, the pump is turned on to add water. It stays on until the target water level is reached, the it stops.
What the maximum water level is reached the (other) pump is turned on to take water out. When the target level is reached it stops.

So the controller basically has a start condition (crossing the minimum or maximum water level), an action (pumping) and a stop condition (reaching the target level). Typically the range is such that oscillations are prevented. This is something where the modeller plays a role as it should take care that the volume of the basin and the pump capacity are reasonably balanced.

So in our implementation we would need to define a start and a setpoint/stop condition. And once the start condition initiated a parameterization change, this parameterization is preserved till the stop condition is met. To prevent too many call backs to check the stop condition, we could consider defining a callback interval

**Comment by SouthEndMusic** [comment]
This is nice. So for instance when the level is above the upper bound, a pump starts pumping water away, but there has to be some memory that says 'I was above the the upper bound but I keep pumping until the setpoint even though I'm now not above the upper bound anymore'. I wonder if this can be implemented with a condition on the pump itself:

- If the level is above the upper bound --> pump on
- If the level is below the upper bound but above the setpoint and the pump is on --> pump (stays) on
- If the level is below the setpoint --> pump off

And equivalently for the other pump that handles the other bound
