### ISSUE TITLE
Validate interpolation data

### ISSUE THREAD

**Issue by SouthEndMusic** [Deltares/Ribasim#376]
There have been several problems with models lately that boil down to having invalid data that is interpolated during runtime. These problems can be solved much faster with a validation step with comprehensible error message in the Julia core pre-simulation. The problem is I think always that there is duplication in the independent variable e.g. multiple Q for one h in a Q(h) relationship, or multiple areas for one level in a profile. I think successive zero areas in a profile should also raise an error.

**Comment by visr** [comment]
Closely related to #279 which lists most validation rules. But it's good to have this to separate it from the extrapolation issue.

**Comment by SnippenE** [comment]
Split issue into two:
QH - relation 
Basin geometry (Profile)
