### ISSUE TITLE
rename QGIS plugin

### ISSUE THREAD

**Issue by visr** [Deltares/Ribasim#380]
In https://github.com/Deltares/Ribasim/issues/231#issuecomment-1609661989 @evetion asked

> What do you think about moving the plugin to qgis/Ribasim and rename the plugin like that as well?

I think it makes sense to rename the QGIS plugin to Ribasim, similar to how the Python and Julia packages are both called Ribasim. I doesn't make sense in the QGIS Plugin manager to see so many packages have "QGIS" or "plugin" when they are all that by definition.

Regarding moving the plugin to qgis/Ribasim, what is the benefit of that? If we can avoid an extra layer of nesting I'd prefer that.

Note that the [name](https://github.com/Deltares/Ribasim/blob/ececb052fb3634cdd7cc6398ff1658fbd1f99a8c/qgis/metadata.txt#L7) is Ribasim-QGIS and then the directory / python package name is ribasim_qgis. Not sure, but for the latter it might be wise to avoid clashes with the ribasim python package in case we can somehow depend on it in ribasim_qgis in the future?

**Comment by evetion** [comment]
The renaming is mostly for automation, so tools around QGIS plugins can easily zip + upload, without an odd rename step that's now needed. But we can postpone that untill we make automatic tags/releases later on.
