### ISSUE TITLE
Document coupling with iMOD Coupler

### ISSUE THREAD

**Issue by Hofer-Julian** [Deltares/Ribasim#385]
iMOD Coupler is currently documented at its [own page](https://deltares.github.io/imod_coupler/), but this will be moved to the [iMOD Documentation](https://deltares.github.io/iMOD-Documentation/coupler_index.html)

I think driver documentation like e.g. MetaSWAP - MODFLOW 6 coupling should be moved there too.
At the moment, the coupling documentation for Ribasim lives at the Ribasim [docs](https://deltares.github.io/Ribasim/couple/).
Are we comfortable moving that to the iMOD docs?

**Comment by gijsber** [comment]
i do not see any real objection as long as we link both ways (from Ribasim to iMod and from iMod to Ribasim)
