### ISSUE TITLE
Handling of missing data in tables

### ISSUE THREAD

**Issue by SouthEndMusic** [Deltares/Ribasim#389]
As mentioned [here](https://github.com/Deltares/Ribasim/pull/329#discussion_r1252143537).

**Comment by visr** [comment]
Thanks for creating this issue. This is partially supported right now, e.g. see https://github.com/Deltares/Ribasim/blob/ed4fbefdc23d0c62ca84939a7f9e6b055f5a1f0b/core/src/utils.jl#L198, where we ignore NaN values when updating the forcing.

Both GeoPackage and Arrow have a general concept of missing data, separate from NaN which only exists for floats, and therefore is not an option for optional string fields like `control_state`. In julia NULL is normally encoded as `missing`, so a float that can be missing is `Union{Float64, Missing}`. So probably we should use that for everything that is allowed to be missing, unless there are other downsides compared to using NaN.

**Comment by SouthEndMusic** [comment]
@visr I guess this issue is solved now?

**Comment by visr** [comment]
I don't think so. It's gotten better with your implementation of defaults in the julia core, but we still need testing and a clear story on how we handle optional data across ribasim-python and the core.

**Comment by visr** [comment]
I think this can be closed now. Occasionally we adjust this a bit like in #1493. One thing worth adding is that we should always use NULL / missing rather that NaN in out input data.
