### ISSUE TITLE
PID control graph validation

### ISSUE THREAD

**Issue by SouthEndMusic** [Deltares/Ribasim#395]
The validation of PID control is more strict than just testing what node type is downstream of what other node type. More specifically:

![PID_model](https://github.com/Deltares/Ribasim/assets/74617371/7dbe0b68-feac-4a65-a07b-d170db625c5c)

The controlled pump must be downstream of a basin and a `PidControl` node, but that control node must listen to exactly that basin.

The controlled weir must be upstream of the basin and downstream of a `PidControl` node, but that control node must listen to exactly that basin.

**Comment by gijsber** [comment]
Hi @SouthEndMusic ,
A weir/gate works with gravity so it must be downstream of the basin with the highest water level, i.e. the one for which it controlls the water level. Its lower flow rate limit should be zero or higher.
A pumpstation may, dependent on its capabilities hift the flow direction (ie become negative). A controlled weir cannot do that.

**Comment by SouthEndMusic** [comment]
When I say downstream I mean the direction of the edge, regardless of the levels of the connected basins. Maybe we should introduce clear nomenclature for this.

If you want the 'main flow direction' of the pump and weir to be positive, then a pump should be downstream of the basin (in the edge sense) and the weir upstream of the basin (in the edge sense)

**Comment by gijsber** [comment]
Why do we need that restriction ? 
In the field I can image a situation of a polder where you have boezem B connected under gravity with weir M to polder basin M
- weir M which act as an inlet (from the high boezem basin B to the lower polder basin M) and is tasked to control the level of M (ie the basin downstream of weir M).

Similarly I can image a canalized river system where the weir is tasked to control the level of the upstream basin.

**Comment by gijsber** [comment]
Indeed, if a weir lets the water flow out of the controlled basin and i want that flow to be positive, then the edge connecting the basin and the weir should point to the weir. 
I think we have the same understanding :-)
