### ISSUE TITLE
Allow more nodes to be discretely controlled

### ISSUE THREAD

**Issue by SouthEndMusic** [Deltares/Ribasim#398]
Currently only controlling `Pump` is supported for DiscreteControl. If I am not mistaken, the following node types need the option of being discretely control too.

- [ ] `FractionalFlow` 
- [ ] `LinearResistance`
- [ ] `ManningResistance`

To achieve this in the way it is currently implemented for `Pump`, the following is needed per `AffectNodeType`:
- The `AffectnodeType \ static` table has to have a `control_state` column;
- The node in question has to be allowed downstream of the `DiscreteControl` node in `neighbortypes(::Val{:Control})` in `validation.jl`;
- The `AffectNodeType` struct has to have a `control_mapping` field which has to be constructed in `function AffectNodeType`. Here I propose a separate function to handle this construction as in `function Pump` to reduce boilerplate code.

**Comment by gijsber** [comment]
- [ ] `FractionalFlow` : yes
- [ ] `LevelBoundary`: no, in my opinion we should consider boundary nodes alwasy as externally fixed/forced and not influenced by the model
- [ ] `FlowBoundary`: no, see LevelBoundary
- [ ] `LinearResistance`: maybe, to be discussed/decided
- [ ] `ManningResistance`: maybe, to be discussed/decided

LinearResistance and ManningResistance should be able to change over time to represent vegetaion differences in summer/winter.
We also should be able to open and close a connection via control, but I would think that Resistance connectors is not the type of connection to use at that moment.

I am missing:
- [ ] `TabulatedRatingCurve` which is being addressed in #348

**Comment by visr** [comment]
Controlling FractionalFlow needs to be done first.
