### ISSUE TITLE
Create simple test for the bucket model

### ISSUE THREAD

**Issue by Hofer-Julian** [Deltares/Ribasim#401]
We test if the bucket model runs to completion, but not if the output is reasonable.
Let's add a test for that.

**Comment by visr** [comment]
Would be good. If the bucket is not coupled we expect nothing to happen, so a constant storage.

https://github.com/Deltares/Ribasim/blob/main/python/ribasim_testmodels/ribasim_testmodels/bucket.py
https://github.com/Deltares/Ribasim/blob/26bcac0ddfc290707ece717b5ecbee39927047b4/core/test/run_models.jl#L15-L21
