### ISSUE TITLE
Monitor development ModelingToolkit

### ISSUE THREAD

**Issue by SnippenE** [Deltares/Ribasim#403]
Outcome of Q3 -2023 & retro 10-7

**Comment by visr** [comment]
Closing this. The scaling issue stops us from using MTK at the scale we need for the Netherlands, with O(10.000) nodes. There is https://help.juliahub.com/juliasimcompiler/dev/, but it is proprietary, so we cannot rely on that.

I still like MTK a lot. It would make sense to use it as a library for very custom problems for which Ribasim as an application is not flexible enough.
