### ISSUE TITLE
Unreasonably high manning flows

### ISSUE THREAD

**Issue by SouthEndMusic** [Deltares/Ribasim#405]
Looking at the flow result of the basic model, the problems with the Manning resistance node have not been resolved yet. Could it be due to a unit mismatch?

![image](https://github.com/Deltares/Ribasim/assets/74617371/4da840ff-712d-4e80-b570-ef243fee7401)

Currently in  `equations.py` the Manning resistance model uses a way to large `manning_n` to get reasonable behavior for testing.

**Comment by SouthEndMusic** [comment]
This may well reveal the cause of the problems with the Manning resistance node:

https://www.desmos.com/calculator/ms3nmwcp8y

As the level difference between the connected basins tends to 0, the corresponding terms in the Jacobian tend to $\pm \infty$. At $\Delta h = 0$ the Jacobian is not defined at all, but this is exactly the state the `basic` models start in. 

I'm quite sure that the root of the problem is with the function

$$
f(x)=\text{sign}(x)\sqrt{|x|}
$$

having the problems described above at $x=0$. There are several approximations of $f$ that do not have this problem, for instance

$$
\begin{align}
g(x) &= \text{sign}(x)\left(\sqrt{|x|+p}-\sqrt{p}\right), \\
h(x) &= \text{sign}(x)\sqrt{\frac{2}{\pi}x\arctan{kx}},
\end{align}
$$

but these have parameters to tune.

With this script you can see how the Manning flow depends on both storages in the `Basic` models (sending a still image doesn't do it justice):

```python
import numpy as np
import matplotlib.pyplot as plt

n = 0.04
L = 900.0
w = 1.0
s = 3

b_a = 0.0
b_b = 0.0

def level(storage):
    return np.sqrt(storage/500)

N = 100
s_a = np.linspace(0,10000,N)
s_b = np.linspace(0,10000,N)

s_a, s_b = np.meshgrid(s_a, s_b)

h_a = level(s_a)
h_b = level(s_b)

d_a = h_a - b_a
d_b = h_b - b_b

d = (d_a + d_b)/2

A_a = w*d + s*d_a**2
A_b = w*d + s*d_b**2
A = (A_a + A_b)/2

P_a = w + 2*d_a * np.sqrt(1 + s**2)
P_b = w + 2*d_b * np.sqrt(1 + s**2)

R_h_a = A_a/P_a
R_h_b = A_b/P_b
R_h = (R_h_a+R_h_b)/2

Dh = h_a - h_b
q_sign = np.sign(Dh)

q = q_sign * A / n * R_h**(2 / 3) * np.sqrt(np.abs(Dh) / L)

fig = plt.figure()

ax = fig.add_subplot(projection = "3d")
ax.set_xlabel("$s_a$")
ax.set_ylabel("$s_b$")
ax.set_zlabel("$q_{manning}$")

ax.plot_surface(s_a, s_b, q, cmap = "coolwarm")
plt.show()

**Comment by Huite** [comment]
Excellent find!

It would explain why we couldn't really find something at fault with e.g. that backwater test, nor with computations done by hand -- since we never look at 0 -- but why the model keeps showing it.

```sqrt``` is somewhat cheaper to compute:

```julia
julia> @btime sqrt.(a);
  1.470 μs (3 allocations: 8.03 KiB)

julia> @btime atan.(a);
  4.186 μs (3 allocations: 8.03 KiB)
```
