### ISSUE TITLE
Poor accuracy of default solver

### ISSUE THREAD

**Issue by SouthEndMusic** [Deltares/Ribasim#408]
When working with `miscellaneous_nodes_model` (in `ribasim_testmodels\equations.py` once it is merged) I found something strange. This model only involves constant flows, so you would expect the simulation to be very accurate, only errors on the floating point rounding level. However, when using the default solver, these errors are actually quite large:

```
# Results default solver (QNDF), no timestep specified:

t = [0.0, 0.0, 29850.445565221708, 59700.891130443415, 139382.86288734875, 470037.34650605114, 2.199536358631379e6, 1.2921064707495343e7, 3.16224e7]
u1 = [1000.0, 1000.0, 1001.2595124711066, 1002.7156576908668, 1006.6845965925411, 1023.2074997232386, 1109.6744306463027, 1645.7430865661054, 2580.8077376231317]
u1_analytical = [1000.0, 1000.0, 1001.492522278261, 1002.9850445565222, 1006.9691431443674, 1023.5018673253026, 1109.9768179315688, 1646.053235374767, 2581.1199999999994]

u1_analytical - u_1 = [0.0, 0.0, 0.2330098071544171, 0.2693868656554059, 0.28454655182633815, 0.2943676020639714, 0.3023872852661498, 0.3101488086615518, 0.3122623768676931]

# Results Euler solver with dt = 4e6:

t = [0.0, 0.0, 4.0e6, 8.0e6, 1.2e7, 1.6e7, 2.0e7, 2.4e7, 2.8e7, 3.16224e7]
u1 = [1000.0, 1000.0, 1200.0, 1400.0, 1600.0, 1800.0, 2000.0, 2200.0, 2400.0, 2581.12]
u1_analytical = [1000.0, 1000.0, 1200.0, 1399.9999999999998, 1599.9999999999998, 1799.9999999999995, 1999.9999999999995, 2199.9999999999995, 2399.9999999999995, 2581.1199999999994]

u1_analytical - u_1 = [0.0, 0.0, 0.0, -2.2737367544323206e-13, -2.2737367544323206e-13, -4.547473508864641e-13, -4.547473508864641e-13, -4.547473508864641e-13, -4.547473508864641e-13, -4.547473508864641e-13]
```

Because of these constant flows you would expect even the Euler algorithm to be near exact (again only rounding errors), and indeed it is, having only errors of order `1e-13`. So the question is why the default algorithm "QNDF" with its self determined timesteps (even the initial one) behaves so poorly.

The constant flows are of order `1e-4`.

**Comment by Hofer-Julian** [comment]
> Could it be that the QNDF initial timestep is so small it creates larger floating point issues?

Yes, that would make sense. It would be good to verify if that is problematic in general.

**Comment by SouthEndMusic** [comment]
I've added the data.

**Comment by SouthEndMusic** [comment]
@Hofer-Julian to answer your question: nope, with a large timestep the large error persists with the QNDF algorithm :/

**Comment by Hofer-Julian** [comment]
@visr what is the reason again that QNDF is the default?

**Comment by visr** [comment]
I've seen it recommended for similar large and stiff systems.

**Comment by visr** [comment]
Closing this, accuracy seems fine. We even increased the tolerance recently because the water balance was good enough. See e.g. https://github.com/Deltares/Ribasim/issues/642#issuecomment-1755654305.
