### ISSUE TITLE
distribute ribasim-python

### ISSUE THREAD

**Issue by visr** [Deltares/Ribasim#418]
The user docs mention installing ribasim-python via PyPI, but it doesn't get frequent releases.

Right now we have nightlies available of the CLI and QGIS plugin, and if people have the repository cloned they could do an editable install like described in the dev docs. But due to breaking changes it's important that they stay synced.

For users that don't need the latest from nightly, last months release on Sharepoint is probably enough. That has the CLI and QGIS plugin, but not ribasim-python. Perhaps we should put a wheel for ribasim-python there as well.

https://pypi.org/project/ribasim/

**Comment by evetion** [comment]
Latest nightly can always be found on https://ribasim.s3.eu-west-3.amazonaws.com/teamcity/Ribasim_Ribasim/BuildRibasimCliWindows/latest/ribasim-0.2.0-py3-none-any.whl

**Comment by evetion** [comment]
Note that this has a hardcoded version in it (as required by wheel naming, pip won't install ribasim.whl), so this is something we should fix and unify everywhere when we start releasing new versions.

Note that 0.2.0 is based on the __version__ in the init.py of the package.
