### ISSUE TITLE
Discrete Control tests based on realistic model

### ISSUE THREAD

**Issue by SouthEndMusic** [Deltares/Ribasim#428]
At the time of writing controlling node types other than `Pump` has been merged (https://github.com/Deltares/Ribasim/pull/424), and making nodes active and inactive is on its way (https://github.com/Deltares/Ribasim/pull/425). These features do not have proper tests yet, but they came about form a discussion about a model of the Netherlands. So, this issue is for

- [ ] Constructing said model;
- [ ] Testing discrete control on non-pump nodes and node activity.
- [ ] #482 

For the details of this model see below.

**Comment by visr** [comment]
![20230717_105250](https://github.com/Deltares/Ribasim/assets/4471859/b43d74b9-a165-4eba-8917-b353509be607)

**Comment by SouthEndMusic** [comment]
@gijsber thanks for the information. I have some questions:
- Are the areas equal to the totalwidth tomes the length?
- What are the parameters of LinearResistance (3, 4, 11), TabulatedRatingCurve (8, 13), PidControl (20), LevelBoundary (16), Pump (14)?

Other points:
- Time dependent flow boundaries are not yet supported: https://github.com/Deltares/Ribasim/issues/439
- See here for the current draft script of the model: https://github.com/Deltares/Ribasim/blob/8c1d126ee9be52bd27b8dd7a7be74c1e0b6fd1a1/python/ribasim_testmodels/ribasim_testmodels/dutch_waterways.py

**Comment by gijsber** [comment]
Are the areas equal to the totalwidth times the length?
yes
Here are some best guesses (actually this is a task for Hydrologic):
LinearResistance: 5000 (assumption)
LevelBoundary: 0 (assumption)
Pump: min 0, max 50, default setpoint 25 (assumption)
PID: Kp: -0.005, Ki:0, Kd: -0.002 (from SBK3 model for gate)
QH: 7.45m Q=418m3/s
elke centimeter stijgt Q met 2.15m3/s

**Comment by SouthEndMusic** [comment]
@gijsber I have distilled the discrete control of nodes 17 and 18 as follows.

**Notation**
- `q`: Flow at edge `(1,2)`, flow of flow boundary with id 1
- `w`: Flow at edge `(6,8)`, used to indicate whether node 8 is active

**Conditions**
1. `q > 250`
2. `q > 750`
3. `q > 800`
4. `w > 0`

**Control states**
- "pump_low":
  - pump (node 9) active
  - pump (node 9) flow rate 15
  - TabulatedRatingCurve (node 8) inactive
- "pump_high":
  - pump (node 9) active
  - pump (node 9) flow rate 25
  - TabulatedRatingCurve (node 8) inactive
- "rating_curve":
  - pump (node 9) inactive
  - TabulatedRatingCurve (node 8) active

**Logic**
To massively reduce the number of logic table entries needed, I want to introduce the wildcard `A`  for any as an addition to `T`  and `F` for true and false respectively.

- `FAAA` -> "pump_low"
- `TFAA` -> "pump_high"
- `ATFF` -> "pump_high"
- `ATFT` -> "rating_curve"
- `AATA` -> "rating_curve"

**Final notes**
- I am aware that using the flow condition on edge `(6,8)` is an ugly thing to do, but the problem is that this 'memory for control' that we discussed for 'being on your way to a setpoint' is a different type of condition than the ones currently supported and fitting in the framework of `VectorContinuousCallback`. 
- This requires an introduction of the wildcard `A` and possibly some validation on the logic data. Note though that not all truth states have to be covered because many are impossible, for instance `FTAA`.

**Comment by gijsber** [comment]
Hi @SouthEndMusic, That looks pretty good. We miss one condition (q>275). If we add that it would become:
Conditions

1.     'q > 250'
2.     'q > 275'
3.     'q > 750'
4.     'q > 800'
5.     'w > 0'

Logic

-     'FAAAA' -> "pump_low"
-     'TFAAT' -> "pump_low"
-     'TFAAF' -> "pump_high"
-     'AATFF' -> "pump_high"
-     'AATFT' -> "rating_curve"
-     'AAATA' -> "rating_curve"

**Comment by SouthEndMusic** [comment]
I realized a potential problem with listening to a flow influenced by a time series as a condition, and that is that such flows are not continuous. This might cause problems in the root finder of `VectorContinuousCallback`. Thoughts @visr?

**Comment by SouthEndMusic** [comment]
What about the option of linear interpolation of the time series? Though that makes integration a bit more complex.

**Comment by visr** [comment]
Yeah I've gone back and forth on that, see https://github.com/Deltares/Ribasim/pull/188 for the reasoning for the current approach. Though the discontinuities in the flow are from the callback, and I think that is allowed to do that there, so perhaps the ContinuousCallback can handle it fine, if it only assumes continuous functions between tstops?

I've looked a bit at similar arguments online but couldn't find much more than https://github.com/SciML/ModelingToolkitStandardLibrary.jl/issues/123#issuecomment-1296212344

**Comment by gijsber** [comment]
From a hydrological perspective, I would think that linear interpolation is acceptable.

**Comment by visr** [comment]
I think it depends, e.g. if you have a non-equidistant precipitation timeseries like

2020-01-01 00:00:00 0.0
2020-02-01 03:02:40 10.0
2020-02-01 03:06:00 0.0

which represents a short intense shower for a few minutes, do you want to gradually go from 0 to 10 over the month of January?

If it is equidistant it might be good enough in general.

**Comment by SouthEndMusic** [comment]
@gijsber in the image you sent of the model edge `(5,7)` to the terminal is invalid, there must be a flow prescribing node in between.

**Comment by gijsber** [comment]
For precipitation timeseries, this assumption is indeed not wise, but I would think that flow series have more continuous behaviour (and indeed you provide them typically as equidistant series)

**Comment by gijsber** [comment]
@SouthEndMusic I would suggest to add a linear resistance as needed

**Comment by SouthEndMusic** [comment]
> @SouthEndMusic I would suggest to add a linear resistance as needed

A `LinearResistance` is not allowed between a `Basin` and a `Terminal` because the `Terminal` has no level. Shall I replace the `Terminal` with a `LevelBoundary` with an assumed level?

**Comment by gijsber** [comment]
using a LevelBoundary is fine to me

**Comment by SouthEndMusic** [comment]
Using https://github.com/Deltares/Ribasim/issues/447 and https://github.com/Deltares/Ribasim/issues/440,

With conditions 

1. q > 250
2. q > 275
3. q > 750
4. q > 800,

I think this logic would work:
- FAAA -> pump low
- UAAA -> pump low
- TAFA -> pump high
- ATAF -> pump high
- AAAD -> rating curve
- AAAT -> rating curve.

The 'pump high' cases have some overlap which should be cleaned up.

**Comment by gijsber** [comment]
Suggested initial levels:
basin 2: 8.31m+NAP
basin 6, basin 5: 7.5m+NAP
basin 10: 7.0m+NAP
basin 12: 6m+NAP
basin 15: 5.5m+NAP

**Comment by SouthEndMusic** [comment]
@gijsber with the above initial levels the simulation now converges but only without the analytical Jacobian. The result doesn't seem very sensible though:

![Dutch_waterways_converged](https://github.com/Deltares/Ribasim/assets/74617371/c60c667e-b847-4c6c-b073-bf214e68858e)

**Comment by SouthEndMusic** [comment]
With much lower resistances (1e-2 instead of 5000) the result already looks better:



![Image](https://github.com/Deltares/Ribasim/assets/74617371/f8ac968b-0008-4f7d-a61e-9a149d3d27db)

**Comment by SouthEndMusic** [comment]
This at least explains why the PID controlled basin doesn't reach its target level: the PID controlled pump can only take out water while the level is generally too low:

![Image](https://github.com/Deltares/Ribasim/assets/74617371/9f4a21c7-2da8-408e-b67c-2d0baec34f45)
