### ISSUE TITLE
Investigate typos pre-commit

### ISSUE THREAD

**Issue by Hofer-Julian** [Deltares/Ribasim#442]
@visr noticed that typos didn't give him feedback when introducing a typo.
Let's check if that is reproducible and if yes, move back to only checking on the CI

**Comment by visr** [comment]
Is the typos pre-commit working at all for others? I could just commit 3 typos.

https://github.com/Deltares/Ribasim/compare/test-typo

**Comment by visr** [comment]
I see pre-commit only runs if I have my conda environment activated, which I don't by default.

If I do that it works, though the message that pre-commit failed is terrible:
![image](https://github.com/Deltares/Ribasim/assets/4471859/4a504754-0938-4b8f-a0e5-026a458c4f70)

Clicking Show command output shows this:

```
> git -c user.useConfigOnly=true commit --quiet --allow-empty-message --file -
check for added large files..............................................Passed
check for case conflicts.................................................Passed
check json...........................................(no files to check)Skipped
check yaml...........................................(no files to check)Skipped
check toml...........................................(no files to check)Skipped
check for merge conflicts................................................Passed
check vcs permalinks.....................................................Passed
fix end of files.........................................................Passed
trim trailing whitespace.................................................Passed
ruff.....................................................................Passed
black....................................................................Passed
black-jupyter............................................................Passed
nbstripout...........................................(no files to check)Skipped
typos....................................................................Failed
- hook id: typos
- files were modified by this hook
```

Which doesn't list the issue. Though in this case typos automatically modifies "moddel" to "model" so you can figure out what was the issue.

**Comment by Hofer-Julian** [comment]
> I see pre-commit only runs if I have my conda environment activated, which I don't by default.

I cannot reproduce that issue. For me, the hooks are executed also without activated conda environment.
Did you run pre-commit install?

I agree that the developer experience with vscode is not amazing, but if it fixes your code, but not stage it, that is fine, right?
It's also the behavior of the other pre-commit hooks.

**Comment by Hofer-Julian** [comment]
Regarding missed typos, `typos` is very much focused on keeping the number of false positives low.
I think that is a good thing for code, but I wouldn't mind adding something stricter for texts.
I have my eye on that one for some time already: https://github.com/reviewdog/action-languagetool

**Comment by visr** [comment]
> if it fixes your code, but not stage it, that is fine, right?

Yeah indeed that is fine. Also I'm fine with minimizing false positives. I indeed ran `pre-commit install` (in my conda env otherwise pre-commit is not on the PATH) I guess the two issues are:

- [ ] why doesn't pre-commit print the typos that it finds just like running `typos` does? Is that something we can enable?
- [ ] why does it not run pre-commit unless I enable a conda environment

**Comment by visr** [comment]
> pre-commit only runs if I have my conda environment activated

Closing, I now always run `open-vscode.bat`, which is needed for full functionality for other reasons as well.
