### ISSUE TITLE
Julia only accepts up to 3 decimals in the seconds in timestamps

### ISSUE THREAD

**Issue by SouthEndMusic** [Deltares/Ribasim#444]
I encountered the following error when trying to use timestamps with nanosecond accuracy:

`Unable to parse date time. Expected directive DatePart(s) at char 21`

After some research @Hofer-Julian found that only millisecond accuracy is supported by our implementation: https://docs.julialang.org/en/v1/stdlib/Dates/#Dates.DateFormat, in the following line.

```julia
nt = merge(nt, (; time = DateTime.(nt.time, dateformat"yyyy-mm-dd HH:MM:SS.s")))
```

Millisecond accuracy for the timestamps is fair enough, but the error should be more informative. I would suggest that having more decimals does not throw an error but these get truncated in the Julia core, and only a warning is shown that this has happened.

**Comment by visr** [comment]
We could truncate the extra decimals with a regex like this, before we do the DateTime parsing. I don't think a warning is really needed, millisecond resolution is definitely fine enough for any application I can think of.

```julia
julia> replace("2020-01-01 00:00:00.1234", r"(\.\d{3})\d+$" => s"\1")
"2020-01-01 00:00:00.123"
```
