### ISSUE TITLE
Conditions on non-continuous parameters

### ISSUE THREAD

**Issue by SouthEndMusic** [Deltares/Ribasim#463]
### Motivation

For https://github.com/Deltares/Ribasim/issues/428 we effectively need a condition on a dynamic flow boundary. The way this is implemented now (see https://github.com/Deltares/Ribasim/pull/446) is that the flow of this flow boundary is given by a timeseries which is interpolated using forward fill, and control listens to the edge out of this flow boundary. This makes the flow over this edge discontinuous in time, which means that the rootfinder for finding changes in conditions cannot detect a crossing (see https://github.com/Deltares/Ribasim/issues/456). In general the forward fill interpolation is desirable because of conservation considerations (see https://github.com/Deltares/Ribasim/pull/188).

### Proposed solution

We keep the forward fill interpolation for the time series for the flow boundary (for conservation purposes), but fool the `VectorContinousCallback` into thinking it is continuous by giving it a linearly interpolated version of the flow boundary value. This brings in a discrepancy between what the model does and what the control responds to, but this discrepancy is probably small in practice.

The condition is changed from a condition on the edge to a condition on the flow boundary node itself. This is because a condition on an arbitrary edge is still problematic, because discontinuities in flow can propagate from further in the model to this edge. 

This proposed solution is only reasonable if conditions on arbitrary edges are not desired (@gijsber?).

**Comment by visr** [comment]
Discussed a way forward with @SouthEndMusic. We can remove listening to flow for now. For the case of listening to Lobith inflow, we can listen to the FlowBoundary. The FlowBoundary time update then needs to support linearly interpolating between data points.

**Comment by SouthEndMusic** [comment]
'Fooling' `VectorContinousCallback` by only presenting a continuous variable to it and nowhere else has not been implemented, the solution proposed by @visr was implemented. 

Conditions on discontinuous parameters will still in general not work with `VectorContinuousCallback`, but could work with `DiscreteCallback` (see https://github.com/Deltares/Ribasim/issues/455) with some loss of accuracy.
