### ISSUE TITLE
Avoid basin areas becoming 0

### ISSUE THREAD

**Issue by SouthEndMusic** [Deltares/Ribasim#472]
Basin areas of 0 (which currently occur when a basin is empty) yield division by 0 in the analytical Jacobian (https://github.com/Deltares/Ribasim/pull/465). To avoid this we need some way to make sure that the basin area never becomes 0.

One way to do this is to add a validation for the input areas always being positive. There might also be some parts of the code that already rely on the area of the basin being 0 on the bottom.

**Comment by visr** [comment]
Let's validate that area starts at > 0, to avoid having to hardcode a minimum such as 1m2 or such.
