### ISSUE TITLE
Tests for PID controlled pump

### ISSUE THREAD

**Issue by SouthEndMusic** [Deltares/Ribasim#482]
New cases for PID control to be tested emerged due to refactoring (https://github.com/Deltares/Ribasim/pull/474, https://github.com/Deltares/Ribasim/pull/465). These test cases are:

- [ ] The PID controlled pump flowing out into `FractionalFlow` nodes;
- [x] The PID controlled basin influencing itself trough being connected to e.g. a `LinearResistance`. This could be added to the equation test by connecting a `LevelBoundary` via `LinearResistance` to the PID controlled basin. This was first trought to be hard to support (https://github.com/Deltares/Ribasim/issues/481) but it seems to be supported now;
- [ ] The PID controlled basin getting in the 'reduction factor regime' (although this is probably quite rare in practice).
- [x] Upstream of the PID controlled weir is a `LevelBoundary` node (done in https://github.com/Deltares/Ribasim/pull/485).

**Comment by SouthEndMusic** [comment]
Regarding the test of the controlled pump flowing out into fractional flow nodes: this possibility is also not covered yet in 

```julia
function update_jac_prototype!(
    jac_prototype::SparseMatrixCSC{Float64, Int64},
    p::Parameters,
    node::PidControl,
)::Nothing
```

**Comment by SouthEndMusic** [comment]
Regarding the following:

> The PID controlled basin influencing itself trough being connected to e.g. a `LinearResistance`

In order to do this, the $\frac{\partial E}{\partial u_i}$ (see `equations.qmd` in https://github.com/Deltares/Ribasim/pull/485) are needed. Most of these are $0$; a nice method has to be found to figure out which aren't.

**Comment by visr** [comment]
Paused this for now, we'll probably work on #152 first. Until then `jac = false` can be used for any models for which the Jacobian is not complete.
