### ISSUE TITLE
Formulating the `du` of a single basin

### ISSUE THREAD

**Issue by SouthEndMusic** [Deltares/Ribasim#487]
There are several internal use cases for computing the `du` of a single basin in the Julia core:
- The `du` of a PID controlled basin is needed for the Jacobian if the derivative term (D) is used*. The Jacobian is computed outside the scope of `water_balance!`, so `water_balance!` is called in `water_balance_jac!` to get this specific `du`, which is needlessly expensive for large models;
- In the context of `DiscreteControl` there is the idea of 'crossing aware' truth states (see https://github.com/Deltares/Ribasim/issues/447) but these (and also the current implementation without this feature) suffers from deceptive crossings of level thresholds (see https://github.com/Deltares/Ribasim/issues/454). The crossing direction after a `DiscreteControl` parameter change could be derived from the sign of the `du` of the basin on which the level condition is set.

`water_balance!` is currently not structured in a way that easily facilitates this. Here is how I envision this to be implemented:
1. Have some function, say `get_basin_dependency_node_ids(basin_node_id::Int, p::Parameters)`, which gives you for a specified basin the ID's of the surrounding nodes that contribute to the `du` of this basin (note in particular the role of `FractionalFlow` nodes) per node type;
2. Figure out some way to use the `formulate!` functions only for this basin and the node ID's given by `get_basin_dependency_node_ids`.

*. That is, the `du` without the contribution of the regulating `Pump`/`Weir`.

**Comment by visr** [comment]
Since this issue is about performance, let's hold off until we see this being a bottleneck in real models.

**Comment by visr** [comment]
No longer needed since we switched to autodiff.
