### ISSUE TITLE
Start making (automatic) releases

### ISSUE THREAD

**Issue by evetion** [Deltares/Ribasim#499]
- Should be automatic
- Version numbers should be clear everywhere

- Do we have a single release version defined somewhere (i.e. how to package all components?)

**Comment by evetion** [comment]
Refinement:
- We make a (manual) release (by tagging), versioned like YYYY.MM.DD. So 2023.08.01.
- It includes all underlying components, not actively versioned.
- Manual releasenotes should be made, and should be placed in the docs
- Teamcity should upload on tag, to a tagged folder on s3, which are/will be linked in the releasedocs
- Github release could also be made automatically?

**Comment by evetion** [comment]
- As mentioned by @Hofer-Julian our Python package is already public on PyPi, so we should consider doing automatic releases there as well.

**Comment by visr** [comment]
A large part of this is now done. Releases are now built and uploaded to S3. We still need developer docs on how to release, starting with:

1. Create a [new release](https://github.com/Deltares/Ribasim/releases/new). Give it a tag like `v2023.08.0`, filling in the current year, month and a sequential "MICRO" number. This follows `vYYYY.0M.MICRO` from [calver](https://calver.org/)
2. Release a new ribasim-python version to PyPI

Example of release binaries, change `v2023.08.0` to `latest` for the nighlies:
https://ribasim.s3.eu-west-3.amazonaws.com/teamcity/Ribasim_Ribasim/BuildRibasimCliWindows/v2023.08.0/ribasim_cli.zip
https://ribasim.s3.eu-west-3.amazonaws.com/teamcity/Ribasim_Ribasim/BuildRibasimCliWindows/v2023.08.0/ribasim-0.3.0-py3-none-any.whl
https://ribasim.s3.eu-west-3.amazonaws.com/teamcity/Ribasim_Ribasim/BuildRibasimCliWindows/v2023.08.0/ribasim_qgis.zip

**Comment by visr** [comment]
All the steps written above are detailed in #668.
I just created these follow up issues: https://github.com/Deltares/Ribasim/issues/666, https://github.com/Deltares/Ribasim/issues/667 and #669.

Or check the CI/CD label: https://github.com/Deltares/Ribasim/issues?q=is%3Aissue+is%3Aopen+label%3ACI%2FCD
