### ISSUE TITLE
FR: Log to file

### ISSUE THREAD

**Issue by evetion** [Deltares/Ribasim#502]
- Config should have an option to log to a file
- Option to disable logging to stdout (i.e. a quiet modus?)
- Option to filter which Modules log

**Comment by evetion** [comment]
- Don't log progressmeter
- Ability to be more verbose in logfile
- Add new loglevel below verbose (lower int)

Please look at Wflow for an implementation. And our previous logging implementation at #504.

**Comment by Hofer-Julian** [comment]
A few implementation notes:
We are currently using https://docs.juliahub.com/TerminalLoggers/gtVHp/0.1.7/ as our logging implementation. For progress bars it recognizes the Progress type from the [ProgressLogging package](https://github.com/JuliaLogging/ProgressLogging.jl). This type is used by [`solve`](https://docs.sciml.ai/DiffEqDocs/stable/basics/common_solver_opts/#CommonSolve.solve-Tuple{SciMLBase.AbstractDEProblem,%20Vararg{Any}}) of differential equations, which we hook into.

**Comment by deltamarnix** [comment]
- [ ] Implement logger in Ribasim.main()
- [ ] Set terminal verbosity to Warning
- [ ] Set file verbosity to whatever is in the config
- [ ] Save ribasim.log to results folder
