### ISSUE TITLE
Unphysical extrapolation of area if decreasing at top of profile

### ISSUE THREAD

**Issue by SouthEndMusic** [Deltares/Ribasim#505]
The area of a profile is extrapolated linearly above the given profile data. This is usually not a problem when the area increases with the level, but in the edge case where the area decreases with the level at the top of the given profile data, then the area is extrapolated until it is negative from some level onward. This eventually yields a square root domain error.

If we do not want to support decreasing area at the top of the profile data we should add a validation for this, otherwise we need to define how this profile should be extrapolated properly.

![Bad_area_extrapolation](https://github.com/Deltares/Ribasim/assets/74617371/b2cbf9d6-ebcb-4068-ba0a-c423da2c520e)

**Comment by visr** [comment]
I think it's fine to disallow a decreasing area at the top. If people want a constant area extrapolation they can just add a higher level with the same area.
