### ISSUE TITLE
Develop Ribasim adapter for FEWS

### ISSUE THREAD

**Issue by SnippenE** [Deltares/Ribasim#509]
Currently, LHM uses 1 adapter for 4 models which makes use and maintenance complexer than needed (Seperation of concerns).

Our proposal is to develop/manage a separate adapter for each model code:
- Modflow6 (structured & unstructured)
- Metaswap
- Metaswap-Wofost
- Ribasim
- iMod
- Possibly Dm/Mozart

These adapters should focus as much as possible on their task of data conversion (if any) and state handling, and as little additional stuff as possible such as creation of run files etc.
Depending on the application, it is up to the Fews configurator and the model builder together to ensure that the various adapter are called in the right combination.
Existing adapter codes could possibly be reused like e.g. the GrowWithTheFlow adapter for iMod

In terms of implementation, we should plan this for Q4 2023/Q1 2024.

**Comment by visr** [comment]
Closing in favor of #441.
