### ISSUE TITLE
Ribamod: store minimum water levels for RIV, DRN

### ISSUE THREAD

**Issue by Huite** [Deltares/Ribasim#511]
We're altering the stages of the MODFLOW 6 rivers and the drainage elevation. This is to reflect higher water levels driving either more infiltration or less drainage. However, the stage should not fall below the bottom. Neither should the drainage elevation fall below an initial level, since that denotes a dry bed.

Also good to note: it's not sufficient to store a copy of the initial values, since the bottom elevations and drainage elevation may change over time.

**Comment by Hofer-Julian** [comment]
I've moved the issue to Ribasim, since this is where all the ribamod issues live at the moment

**Comment by Huite** [comment]
This has long been implemented.
