### ISSUE TITLE
Refactor Python Model

### ISSUE THREAD

**Issue by evetion** [Deltares/Ribasim#512]
There's some technical debt in there, as it mixes all nodetypes and the required config options.

**Comment by visr** [comment]
Came up here: https://github.com/Deltares/Ribasim/pull/504/files#diff-fead0d71e1c1d151d980158562fa952ffed8d39dc82b2207797f10a0214aa780R163-R169

**Comment by evetion** [comment]
This was already started once by @SouthEndMusic. What also came up is to generate a JSONSchema for our TOML config file and use it like we use our nodes.
