### ISSUE TITLE
External data (for DiscreteControl)

### ISSUE THREAD

**Issue by SouthEndMusic** [Deltares/Ribasim#520]
Currently conditions are possible on basin levels and (transient) flow boundary flow rates. We also want to support conditions on variables which are not part of the model at all, but are only given by a time series (first mentioned in https://github.com/Deltares/Ribasim/issues/331). This should also support look ahead (https://github.com/Deltares/Ribasim/pull/516).

This functionality is also usefull for control based on external salinity conditions

**Comment by visr** [comment]
This was discussed a bit in https://github.com/Deltares/Ribasim/issues/1125. We could implement it as a new External node type.
