### ISSUE TITLE
Rename `DiscreteControl` to `IntervalControl`

### ISSUE THREAD

**Issue by SouthEndMusic** [Deltares/Ribasim#531]
The name `DiscreteControl` is misleading since it uses `VectorContinuousCallback`, it sets parameters in a discrete way. Interval control describes wat it does, and leaves 'discrete' to be used by control that uses discrete callbacks.

**Comment by visr** [comment]
#455 still needs to be refined. Possibly we can use the same DiscreteControl node type for both ContinuousCallback and DiscreteCallback. Therefore it's better not to rename yet until we have a design for #455. We can just explain that the Discrete in DiscreteControl refers to the control states, which are discrete.

If we do rename, perhaps ContinuousControl, GreaterThanControl or ThresholdControl are alternative names.
