### ISSUE TITLE
Write geopackage -> option to not delete existing geopackage

### ISSUE THREAD

**Issue by harm-nomden-sweco** [Deltares/Ribasim#563]
Kan het wegschrijven van de geopackage ribasim_model.write() aangepast worden? Of een optie toevoegen.

Nu wordt een eventueel bestaande geopackage verwijderd en opnieuw aangemaakt. 

Probleem: je moet nu kiezen: 
1. je QGIS sluiten en opnieuw openen of 
2. het ingeladen geopackage verwijderen uit je kaart en dan weer toevoegen via de import.

Echter: je kan ook er vanuit gaan dat de geopackage al bestaat en alle tabellen/lagen daarbinnen overschrijven. Dan kan je QGIS gewoon open laten en zie het in QGIS gewoon 'live' aangepast worden. In de praktijk betekent dat je alle tabellen/lagen echt moet overschrijven, Dus als je geen Pumps hebt, moet je alsnog die tabellen overschrijven, alleen dan met lege tabellen.

Dit is qua gebruiksgemak (bij het iteratief genereren) erg fijn...  bij het lumpen blijkt dit erg succesvol.

**Comment by visr** [comment]
Related to #269. Modifying an existing GeoPackage rather than overwriting is an interesting idea to explore, thanks for the suggestion.
