### ISSUE TITLE
add 'name' as optional string field in node type schemas

### ISSUE THREAD

**Issue by gijsber** [Deltares/Ribasim#567]
the name field can be used in communication and visualization. If the impact is low, it would be nice to log both the id (which is unique) and the name

**Comment by evetion** [comment]
- Add QGIS name popup as well.

**Comment by evetion** [comment]
Doesn't it make sense to add a name to the node and edge tables, instead of duplicating everywhere?

**Comment by visr** [comment]
Yes I think that makes more sense.
