### ISSUE TITLE
Water conservation validation

### ISSUE THREAD

**Issue by SouthEndMusic** [Deltares/Ribasim#572]
# Proposal

I propose an addition to the `Parameters` object called `forcing::Float64`. This number denotes the net exchange 'flux' of the environment into the model. It is updated by each call to a `formulate!` method, where special care has to be taken everywhere with connected `LevelBoundary` and `Terminal` nodes. When `du` is fully formulated, its sum must be equal to `forcing`. An error can be thrown when the difference $e_k$ at timestep $t_k$ is too large. $e_k$ is given by

$$
e_k = \sum_{i=1}^n f_i(\mathbf{u}(t_k),p(t_k),t_k) - \sum_{i=1}^n F_i(\mathbf{u}(t_k),p(t_k),t_k),
$$

assuming there are $n$ basins. The first term is the sum of `du` and the second the sum of the forcings, i.e. `forcing`.

It could be nice to introduce a new state, say `water_balance_error`, which is the cumulative (integral) version of $e$. That is, this state denotes how much water was actually introduced/removed erroneously since the start of the simulation. There a several nice uses for this state:

- An intuitive bound can be placed on how large this state is allowed to get;
- The partial derivatives of `forcing` are computed automatically in the Jacobian. These partial derivatives can give an insight in which basin storages are involved in breaking water conservation;
- When the time comes for sensitivity analysis, calculating the derivative of `water_balance_error` with respect to a node parameter can reveal whether the related (non-basin) node is involved in breaking water conservation.

# Implementation considerations

There are several ways to gather the information to calculate $e$ within `water_balance!`. How and where this information is gathered determines what types of errors with water conservation are actually caught. Using the sum of the fully formulated `du` is nice because that's 'as late as possible', i.e. the values that are actually used by the solver.

To gather the forcings, the above method is necessary for basin forcings (evaporation, precipitation etc.). For boundary nodes it could be done differently, outside the `formulate!` calls. A new function `get_boundary_flows!` could be added, with a method for each boundary node, which grabs the forcing flows from the `flow` object. This might be cleaner than the approach above because this way the information which flows are 'boundary flows' is more directly available.

# Final notes

- In the formal model description it must be made clear that the forcing can actually depend on the model state as indicated above (e.g. when a level boundary is connected to a resistance node).
- One thing to work out is how this combines with coupling.
- If this is implemented, it should be decided which parts must be (optional) user input and what the default settings are.

**Comment by gijsber** [comment]
Hi @SouthEndMusic , looks like a good start, but at the basin level we also have (forcing) fluxes: rain, evaporation, drainage, etc.

**Comment by SouthEndMusic** [comment]
@gijsber that is incorporated in this, basin forcing is handled by one of the `formulate!` calls.

**Comment by SnippenE** [comment]
@visr : is this issue still needed?If not, please close

**Comment by visr** [comment]
Closing in favor of #642
