### ISSUE TITLE
Allow extra table columns in Python builder

### ISSUE THREAD

**Issue by evetion** [Deltares/Ribasim#576]
So one can keep their own type of remarks/lineage. Might be hard because we hardcode all columns at the moment.

On hold after discussion with @gijsber en @visr, we wait for a customer request for this.

**Comment by gijsber** [comment]
refinement 24/10: add extra column: 
- userdefined_id
- data_origin

**Comment by evetion** [comment]
## Now
Extra columns get filtered

## Request
Allow extra columns.
Externally only a specific id column is requested, but internally we also see other usages, such as an origin column.

## Solutions
Ordered roughly by complexity/restriction:

- Allow all
- Allow all by opt-in in toml
- Allow all but add prefix
- Add requested column(s) only (add to schema)
- Allow specific columns by opt-in in toml
- Allow metadata in separate (but linked) tables
- Allow metadata in separate (but linked) node/edge tables

## Objections
- Extra columns can be confusing
- Allowing extra columns (noise) is just a bad practice
- Specifying columns in the toml is 
- Metadata in separate tables (especially with foreign keys) introduces a lot of complexity for both users as developers.

## Consensus
There is no clear consensus. We need to allow for something, but ideally restrict it if possible.

## Authors opinion
Much of the discussion is *how* people should model, but it doesn't relate to any Ribasim features. However, some proposals lead to extra complexity of the Ribasim (Python/QGIS) code.
This seems unnecessary, and should not be our focus. I therefore propose:

Allow all extra columns, but prefix columns (like `nr|`) to prevent confusion.

Making things opt-in seems patronizing to me, and given our own creation of this issue and the external request, it should be opt-out if anything.

**Comment by gijsber** [comment]
Yesterday, Edwin and me came up with an alternative solution for traceability how the model was constructed.

Basically you need to specify:
1. a tag to the github script version that was used to generate the model
2. a tag to the file which holds the references to the basedata from which the model was generated.
We could store these tags in the TOML file in a separate section which is neglected by our code (modelconstruction_history).
we could even include other information like the person who created the model, the creation date etc.

**Comment by gijsber** [comment]
I would say any TOML-field below `modelconstruction_history` is open for expansion, so people van also add a link to a document which describes how a model is created (or manully improved)

**Comment by visr** [comment]
Model metadata is also an interesting topic, but it is really a different issue. This is about node metadata. There are generally too many nodes to store the metadata in the TOML.

**Comment by gijsber** [comment]
I don't think you understand what my intention of this proposal is, namely... the TOML contains one or more references to other places which allow tracebility or regeneration of the model/model-history. 
This is not a solution for the request of a userdefined_id column, but it could be a way to addres the request for columns that are used to track model generation from the base data.

**Comment by visr** [comment]
Discussed with @evetion to go with his suggestion to switch to this option: `Allow all but add prefix`. I suggest the column name prefix `meta_`. This can be added to any table. We don't use it, just carry it on, so we don't need to standardize which extra columns to use.
