### ISSUE TITLE
standardize reduction factor

### ISSUE THREAD

**Issue by visr** [Deltares/Ribasim#591]
I made this plot of the smooth reduction factor:

![reduction_factor_plot](https://github.com/Deltares/Ribasim/assets/74617371/07d558b8-9f24-4509-a211-65c04af06275)

~~how can I add it to `equations.qmd`?~~ It has been added now.

_Originally posted by @SouthEndMusic in https://github.com/Deltares/Ribasim/issues/549#issuecomment-1702971144_
            
Bart made a nicer reduction factor. We should probably use this one for all the reduction_factors, which is now generally a linear reduction. Most are hardcoded to work until 10m3, for Manning it is 10cm waterdepth. Let's see if we can share this and/or make it configurable.

**Comment by evetion** [comment]
Probably any [sigmoid](https://en.wikipedia.org/wiki/Sigmoid_function) function will work?

**Comment by visr** [comment]
Probably. Sigmoid looks more expensive than [this](https://github.com/Deltares/Ribasim/pull/549/files#diff-1a9c5513842f47bc486ee02dda3d25283e4821464e69084cd07a3bd78d725ce5R909), and only approaches the right value, so it is not smooth at the threshold.

**Comment by visr** [comment]
Sorry I should've checked #549 better first, it already moves all reduction factors over.
