### ISSUE TITLE
On naming models and files

### ISSUE THREAD

**Issue by visr** [Deltares/Ribasim#638]
On discussing #588 one thing that came up was the model name and how it is used. Right now we require a model name, and it is used as the GeoPackage and TOML file names. Additionally we use the convention to use this model name as the directory name, by using `model.write(datadir / model.modelname)` to specify the directory.

```
path/to/modelname/
    modelname.gpkg
    modelname.toml
    output/
```

- [x] I'd like to propose to not use the model name in the filenames, and default to filenames like the following #690

```
path/to/model/
    database.gpkg
    ribasim.toml
    results/
```

The TOML stays the entry point for a model, from here the path to the GeoPacage and other data can be found. This also raises the point if we need to define a model name at all? It's good to also look at this in line with #47.

**Follow-ups also discussed here, probably best done after #630**
- [x] never use default paths #799
- [x] #800

**Comment by gijsber** [comment]
I never like input and output, as it needs a perspective from which it works. E.g. from the perspective of a shell/GUI around the model, the input (for the model) is actually output (from the shell/GUI) and the output is actually input (to the GUI).

I would prefer:
`ribasim_model.gpkg` or `basemodel.gpkg` or even 'to_ribasim.gpkg' over `input.gpkg`
and `ribasim_results` or `results` or 'from_ribasim' over `output`

the introduction of `base` fits with the idea that you can specify the diffs to the base in a case definition (#47)

**Comment by visr** [comment]
Thanks for the input.
In the proposal above I changed `config.toml` to `ribasim.toml`, to signal more clearly this is a Ribasim model, and that this is the entrypoint. `output` is now `results`, and `input.gpkg` became `database.gpkg`, since it is a database, it contains model data, but is not the entrypoint, and it contains `base` since Arrow tables can override it. Calling the GeoPackage `*model.gpkg` might make people think the whole model is there.

**Comment by Hofer-Julian** [comment]
> Thanks for the input. In the proposal above I changed `config.toml` to `ribasim.toml`, to signal more clearly this is a Ribasim model, and that this is the entrypoint. `output` is now `results`, and `input.gpkg` became `database.gpkg`, since it is a database, it contains model data, but is not the entrypoint, and it contains `base` since Arrow tables can override it. Calling the GeoPackage `*model.gpkg` might make people think the whole model is there.

I like these names a lot. I was never too fond of the idea that we simply expect that people are able to guess what a `gpkg` or `toml` file might be used for.

**Comment by gijsber** [comment]
Sounds good to me

**Comment by evetion** [comment]
I'm all for clarification and naming things correctly, but I'm not sure what we're solving with this proposal.

Because of the proposed unique naming, we can't store multiple models (or different configs with the same database.gpkg) in a single folder. This would also limit the possible designs for the proposed cases features (and if we do changes like these, ideally only once instead of twice). Besides, as we now require separate folders for each model, we implicitly still use the modelname.

Renaming from output to results however seems effect free, so 👍🏻 

> I like these names a lot. I was never too fond of the idea that we simply expect that people are able to guess what a gpkg or toml file might be used for.

I wonder if that's a real use case. If you need to distinguish between them, you are a Ribasim modeller, and you would know. Besides, shapefile (horribly to use it as example 😓) have many files with extensions that I'm not even familiar with and everyone just copies all files that are named the same (the old design), so it keeps working.

**Comment by visr** [comment]
> Because of the proposed unique naming, we can't store multiple models (or different configs with the same database.gpkg) in a single folder.

We can still do that. The proposed names are just convention, nothing hardcoded. These conventions we set in e.g. our test models. I think single model directory is a good convention since it is less confusing, but we can still support the more advanced use case of multiple models in a directory / cases.

**Comment by Hofer-Julian** [comment]
Agreed, it's just a sane default for Ribasim Python, not a hard requirement for Ribasim itself.

**Comment by visr** [comment]
On a related note, right now the `geopackage` key is required, so the path is always explicit. Other paths, such as the results, are optional, with defaults.

Would it make sense to never use default paths? That way it's always explicit which files are related to the model and how. Now, if an external application wants to find the output files from the TOML, it needs the JSON schema of the config to be able to fill in the defaults.

**Comment by Hofer-Julian** [comment]
> Would it make sense to never use default paths?

Sounds good to me.

**Comment by evetion** [comment]
> Would it make sense to never use default paths? That way it's always explicit which files are related to the model and how. Now, if an external application wants to find the output files from the TOML, it needs the JSON schema of the config to be able to fill in the defaults.

Would that imply that all node keys that could point to an arrow file, should instead point to the geopackage? (which is exactly how the python refactor would expose it)

**Comment by visr** [comment]
Hmm that's not what I had in mind. That way the TOML becomes much more verbose, and you have to modify the TOML every time you add a node type.

It's fine if that is how it's implemented, I suppose we could just leave it out of the TOML if it points to the geopackage?

**Comment by evetion** [comment]
Why do you still have to specify "results" here? :)

Shouldn't this just be flow.arrow now?

_Originally posted by @Hofer-Julian in https://github.com/Deltares/Ribasim/pull/798#discussion_r1397344155_


As pointed out above, we should discuss `results_dir` as well. In Julia the `results_dir` is actually set to `.`, and the individual files are like `results/file.arrow`, which should probably be changed.

**Comment by visr** [comment]
Last remaining tasks will be in #799
