### ISSUE TITLE
Start supporting pandas >=2.1

### ISSUE THREAD

**Issue by Hofer-Julian** [Deltares/Ribasim#645]
At the moment, Ribasim Python fails with pandas >= 2.1.
We should adapt our code, so it starts working, and remove the version requirement.

Original issue description: https://github.com/Deltares/Ribasim/pull/586#issuecomment-1714490399
I assumed 2.1.1 would fix it for us: https://github.com/Deltares/Ribasim/pull/643#issuecomment-1745000090

**Comment by visr** [comment]
2.1.1 didn't fix it, since it still contains a regression, but 2.1.2 might: https://github.com/pandas-dev/pandas/pull/55690
