### ISSUE TITLE
test on different python versions

### ISSUE THREAD

**Issue by visr** [Deltares/Ribasim#650]
Our Python tests are set up to run on Python 3.9, 3.10 and 3.11.
https://github.com/Deltares/Ribasim/blob/30d468a5d4b20d8c6393d5862dbffec8e83b01d3/.github/workflows/python_tests.yml#L23-L26

I was wondering with the Python version being fixed to 3.11.5 in the pixi.lock file, how this worked. Looking at the 3 jobs it seems that all three actually test Python 3.11.5:

https://github.com/Deltares/Ribasim/actions/runs/6419269733/job/17428758052#step:5:6
https://github.com/Deltares/Ribasim/actions/runs/6419269733/job/17428758689#step:5:6
https://github.com/Deltares/Ribasim/actions/runs/6419269733/job/17428759035#step:5:6

Also, is it worth it to test every minor Python release, or is the oldest and newest we support enough?

Found while working on https://github.com/Deltares/Ribasim-NL/pull/17. There I'll only test 3.11 for now.

**Comment by Hofer-Julian** [comment]
> I was wondering with the Python version being fixed to 3.11.5 in the pixi.lock file, how this worked. Looking at the 3 jobs it seems that all three actually test Python 3.11.5

This is an oversight from my side. I've set up mamba to test multiple versions, but not for pixi.
Not sure if pixi has something planned to support that, but for now the best way I can think of to get this coverage back is to use an environment.yml and mamba again for Ribasim Python CI tests.

**Comment by visr** [comment]
And how about just running `pixi add python=3.9` on CI before `pixi run install-without-pre-commit`?

**Comment by Hofer-Julian** [comment]
> And how about just running `pixi add python=3.9` on CI before `pixi run install-without-pre-commit`?

Let's try that first. I wonder how fast that works considering there's probably nothing cached
