### ISSUE TITLE
test python 3.12

### ISSUE THREAD

**Issue by visr** [Deltares/Ribasim#654]
It only came out a week or two ago, so our dependencies aren't there yet. pyogrio should have a 3.12 build in the next release after 0.6.0, I'm watching that for releases, then we can try again. We can also directly update our pixi.lock so people use it.

Came up in https://github.com/Deltares/Ribasim/pull/652#issuecomment-1752704778

**Comment by visr** [comment]
#713 addresses a large part of this. To fix this we just need to revert https://github.com/Deltares/Ribasim/pull/713/commits/5d2fb8f0108754f9231defe4683509b46b98e5cf, which we should be able to do when pyarrow 14 is out, see https://pypi.org/project/pyarrow/#history.

**Comment by deltamarnix** [comment]
This issue only requires us to update the test matrix:

https://github.com/Deltares/Ribasim/blob/aa37a01ddf7b4671e6bf771c142b12b5f11e3d8e/.github/workflows/python_tests.yml#L25
