### ISSUE TITLE
Modeller input for allocation

### ISSUE THREAD

**Issue by SouthEndMusic** [Deltares/Ribasim#656]
What should the input look like from the modeler to specify allocation? E.g. how are subnetworks, sources etc. specified?

**Comment by SnippenE** [comment]
Subnetworks have an ID and 1 or more sources where source is an edge. Nodes have an optional reference to a subnetwork ID. We reserve groups for different purposes. 

We call this allocation sub-network

**Comment by SouthEndMusic** [comment]
Priority of sources is at the level of a sub-network.

**Comment by gijsber** [comment]
add optional column to node table called: allocationnetwork_id (long integer)

add optional column to edge table: allocationnetwork_id (long integer)
