### ISSUE TITLE
TeamCity release improvements

### ISSUE THREAD

**Issue by visr** [Deltares/Ribasim#667]
Currently TeamCity builds a newly tagged release at the next 3 AM. I want it to either trigger automatically on a new tag, or a manual button to start the whole release process, because then we can do a release in a single day.

The TeamCity release artifacts are currently uploaded to S3, but I think we can skip this and just upload it with `gh release upload` directly to GitHub release assets. S3 can continue to be used for hosting the nightly builds.

Right now the release process docs mention to generate and upload the test models locally, but it would be nice to directly add this step to TeamCity as well.

- [ ] change TeamCity configuration
- [ ] update release process docs

**Comment by Hofer-Julian** [comment]
This is how the trigger works at the moment:


![Image](https://github.com/Deltares/Ribasim/assets/30049909/4d3cab91-99dd-43e2-a8f8-dd8ac9771599)

As soon as there's a CLI build on a tag starting with "v" it will upload to S3.
That means that you are already able to start the release process manually, simply by triggering CLI build on the release tag.

> The TeamCity release artifacts are currently uploaded to S3, but I think we can skip this and just upload it with gh release upload directly to GitHub release assets.

Agreed. Let's discuss with @evetion what's the best way to expose the GitHub auth token to `gh`. (And check if `gh` is even available on TeamCity)

**Comment by evetion** [comment]
Just set the GITHUB_TOKEN as secret env variable? I can install gh as a module (named github) on the Linux agents.

**Comment by Hofer-Julian** [comment]
> I can install gh as a module (named github) on the Linux agents.

That would be great!

**Comment by Hofer-Julian** [comment]
TeamCity published the latest release, so this can be closed: https://github.com/Deltares/Ribasim/releases/tag/v2024.01.0
