### ISSUE TITLE
Inference of model state between allocation solves

### ISSUE THREAD

**Issue by SouthEndMusic** [Deltares/Ribasim#671]
We currently want not every time integration step to involve an allocation solve. However, to do allocation properly, you then need to infer some things about the model over the time between successive allocation solves (say the allocation timestep). If this timestep is sufficiently small, things like source flows and user demands can assumed to be constant, but that might not work from certain allocation timestep sizes onward. 

For parameters that are given by a timeseries (e.g. transient flowboundaries) this data is readily available, but in general this requires a coarse but accurate enough prediction of these parameters/variables over the allocation timestep interval.

**Comment by SnippenE** [comment]
To be discussed within the RTC tools team

**Comment by gijsber** [comment]
I would recommend to include @Huite in this design session/discussion as the biggest unknown will be the expected exchange with Modflow (drainge/infiltration) and Metaswap (irrigation demand)

**Comment by gijsber** [comment]
from @SouthEndMusic 
#671 is ook nog een interessante. Op dit moment kijkt allocatie alleen naar de staat van het model (en parameters) op de tijdstap dat allocatie plaatsvindt, en doet dus als ware een forward fill van deze waarden totaan de volgende allocatie solve om het allocatie probleem op te lossen. Hoe goed deze benadering is hangt af van hoe veranderlijk het model is en hoe groot de allocatie tijdstap is. Voor sommige variabelen zijn tijdseries beschikbaar dus voor die is een betere benadering makkelijk, maar voor feel parameters is dat lastiger

**Comment by visr** [comment]
To keep this simple, we should require the allocation timestep to be equal to the BMI coupling interval and the `saveat` saving frequency (in practice a day).

Then we can just use the modflow and metaswap provided fluxes for this.
