### ISSUE TITLE
Model lineage

### ISSUE THREAD

**Issue by evetion** [Deltares/Ribasim#700]
[..] namely... the TOML contains one or more references to other places which allow tracebility or regeneration of the model/model-history. 
This is not a solution for the request of a userdefined_id column, but it could be a way to addres the request for columns that are used to track model generation from the base data.

_Originally posted by @gijsber in https://github.com/Deltares/Ribasim/issues/576#issuecomment-1779626899_

**Comment by visr** [comment]
This isn't planned.
