### ISSUE TITLE
Take terminal nodes into account as sinks in allocation

### ISSUE THREAD

**Issue by SouthEndMusic** [Deltares/Ribasim#708]
In allocation networks some water is lost trough flow into terminal nodes, which is currently not taken into account in allocation solves. The flow to the terminal nodes can be used as the sink flow magnitude, but it is not immediately clear to me how this should be taken into account in the allocation problem.

**Comment by gijsber** [comment]
Hi @SouthEndMusic , to 'force' water on a trajectory without being consumed we should introduce some 'instream demand'. From an allocation algorithm perspective could see this as a user that abstracts the instreaf demand and has a 100% returnflow, but we need to discuss with @visr how we envision that being modelled in the ribasim network.

**Comment by SnippenE** [comment]
Discuss with RTC tool team

**Comment by SouthEndMusic** [comment]
For now it is fine to model the terminal node as a user with a single demand with higher priority than all the user demands, and the demand is given by the flow over the edge to the terminal node in the physical layer at the starting time of the allocation optimization.

**Comment by SouthEndMusic** [comment]
Closed because of https://github.com/Deltares/Ribasim/issues/1208#issuecomment-1988404773, @gijsber argued that we do not need the terminal nodes in allocation at all.
