### ISSUE TITLE
Be consistent with naming of subnetwork, allocation network etc.

### ISSUE THREAD

**Issue by SouthEndMusic** [Deltares/Ribasim#709]
In discussions and afterwards in implementation and documentation, the terms `subnetwork`, `allocation network` and `allocation graph` are used rather interchangeably. These terms should get clear definitions, and then be applied accordingly in the code and documentation.

**Comment by gijsber** [comment]
from @SouthEndMusic 
#709 moet voor de volledigheid ook wel een keer opgepakt worden. Mijn idee is nu dat de verzameling nodes die bij elkaar horen volgens de input een subnetwerk heet, en dan is het logischer dat de input `subnetwork_id` heet in plaats van `allocation_network_id`. Allocation network is dan het netwerk afgeleid van een subnetwerk waarop allocatie optimalisatie plaatsvindt
