### ISSUE TITLE
Add control option based on surface area

### ISSUE THREAD

**Issue by SnippenE** [Deltares/Ribasim#721]
Improvement of control options where user can define an outflow area instead of fixed Qh relation to control the outflow through a sluices. Usecases: Driel or Haringvlietsluizen.

**Comment by visr** [comment]
This would need a different node type that implements the structure more directly via some sort of weir formulation. If we have that, we can indeed set gate height from control, rather than set the flow rate as we do with Outlet and Pump.

**Comment by SnippenE** [comment]
@visr and @gijsber can you refine this issue together?

**Comment by deltamarnix** [comment]
@SouthEndMusic Would this issue be clear for you, or would you require more input from @visr ?

**Comment by visr** [comment]
I think we should just close this. This came up once briefly as a hypothetical thing in a discussion with a user, there is no concrete need for this.
