### ISSUE TITLE
Metaissue: 1) sequential coupling Ribasim-Metaswap without allocation in Ribasim

### ISSUE THREAD

**Issue by SnippenE** [Deltares/Ribasim#729]

**Comment by SnippenE** [comment]
Basic idea is to replace DFM by Ribasim in Lumbricus MF6-MS coupling

Start with seq coupling MF and add MS 
Use DFM schema and make work for Ribasim (runoff MS --> Ribasim)
MVP with lumped appraoch based on large polygone-basin. 

Discussion points:
coupling schema diagram, which flux in which kernel
timestep needed for exchange allocation to metaswap
 which MFMS package do we need to use (well / river / api packages)

Define testcases (veenweide / limburg)

**Comment by HendrikKok** [comment]
Possible subtasks:

1 - Create new working feature branch ribametamod.
2 - Check Teamcity? 
3 - Make copy of driver ribamod, and rename to ribametamod
4 - Check if we can run ribametamod without any coupling with Ribasim. (We need this to be able to run all metamod-tests 
     after implementing these functionalities).
5 - Create mapping in ribamod is inconsistence with the one of metamod (maybe a small refactor)
6 - Add metamod-functionality.
7 - Add ponding mapping and exchange -> metaswap.dll update nodig?  
8 - Add combined tests and conserve current tests?

*Check Driver.f90 for coupling with MOZART to see if we miss something?

**Comment by Hofer-Julian** [comment]
Close in favor of more specific issues
