### ISSUE TITLE
Automate tasks with pixi

### ISSUE THREAD

**Issue by Hofer-Julian** [Deltares/Ribasim#747]
- [x] pixi run generate-testmodels # e.g. `pixi run generate-testmodels basic` should generate the basic model
- [x] pixi run ribasim-model # `pixi run ribasim /path/to/ribasim.toml`, implementation might be similar to `using Ribasim; Ribasim.run(ARGS)` (in progress as part of #502)
- [x] pixi run resolve-manifests # run pkg resolve on the checked in manifests (not needed after #740)

Follow up to https://github.com/Deltares/Ribasim/issues/598

**Comment by deltamarnix** [comment]
Fixed with #911
