### ISSUE TITLE
Investigation: manage QGIS with pixi

### ISSUE THREAD

**Issue by Hofer-Julian** [Deltares/Ribasim#748]
Commands to investigate

- [x] pixi run qgis # # should first copy the qgis folder to the plugins
- [x] pixi run update-qgis-plugin # TODO copy the qgis folder to the plugins

Follow up to https://github.com/Deltares/Ribasim/issues/598

**Comment by Hofer-Julian** [comment]
@visr & @deltamarnix I think we can close this issue, no?

**Comment by deltamarnix** [comment]
Yes because we fixed it with #805
