### ISSUE TITLE
Add User node type

### ISSUE THREAD

**Issue by gijsber** [Deltares/Ribasim#76]
data definition
- [ ] requested abstraction [m3/s] (double) dynamic timeseries via file or set at runtime via de Metaswap coupler)
- [ ] actual abstraction [m3/s] (double, updated at runtime by the allocation algorithm) 
- [ ] return percentage [%] (double between 0-100) static

additional input for allocation algorithm [#349]
- [ ] priority [-] integer>0, static, lowest number is most important

default behaviour (without allocation algorithm)
- [ ] extract water from basin, reduce/stop abstraction when the minimum level/volume is approached
- [ ] actual abstraction = requested abstraction, 
- [ ] extract water based on availability/first come, first serve

when allocation algorithm [#349] is activated
- [ ]  allocation algorithm updates (cut back) actual abstraction as needed based on priority such that higher priority users get their water under dry conditions

**Comment by visr** [comment]
I believe this can be closed in favor of #14.

**Comment by gijsber** [comment]
H'mm I do not if this one can be closed. even if we do not run in 'allocation' mode with priorities, we should allow users to abstract water on a first come first serve basis. We need a User node type

**Comment by visr** [comment]
Ok, re-opened and renamed the issue to "add User node type".
I think this node type would be like the FlowBoundary, except that it has a priority, and a possible return flow.

**Comment by SouthEndMusic** [comment]
As mentioned in https://github.com/Deltares/Ribasim/issues/293, the abstraction flow rate of a user should be a `DiscreteControl` condition (listen) variable

**Comment by SouthEndMusic** [comment]
When a user returns water, do they do so over the same edge as the abstraction?

**Comment by gijsber** [comment]
1. a user should have an incoming edge and an outgoing edge. The outgoing edge can go to the same or a different basin.
2. if a modeller wants to return water that did not come from the basin (or a coupled model like Modflow), a `FlowBoundary` node needs to be used
3. best to make it mandatory
4. the Demand should be in the `static` and the `time`table. Priority can be in `static` only

**Comment by gijsber** [comment]
1. let's define this with the user, in the `static` table only untill we realize it should be dynamic
2. yes, immediate. In practice some delay may occur, but generally there will be no information available to parameterize such a delay. Eg, for Industry, you are likely to know an annual or monthly abstraction rate (mostly from the permit or a report) and if you are lucky a daily series of abstractions and return flows.
