### ISSUE TITLE
Accommodate navigation locks as general user with % return flow

### ISSUE THREAD

**Issue by gijsber** [Deltares/Ribasim#77]
Navigation locks are characterized by leakage from one storage to another storage, with possibly a pump installed to compensate for this loss. extra complication is that at the sea outlets (Afsluitdijk, Lauwerszee, Harlingen, IJmuiden),  navigation locks introduce salt intake.

Various concepts could be imagined for the Locks:
1. a Lock model component which allows to specify:
- a leakage flow (series) for water (and concentration) leaving the upstream basin
- a pump compensation flow for water (and concentration) being pumped back
- a salinity intrusion series to inject in the upstream basin

2. extension to the General user component to allow a return flow in another basin:
- abstraction series from upstream basin
- -% return to a downstream basin

For the saltintrusion, the most simple approach would be:
3. a salt intrusion influx component (see #84 )
- a salt load series

Both 1 and 2 can be combined with 3

**Comment by gijsber** [comment]
~2d
separate issue for salt intrusion
30min discussion needed on concept

**Comment by gijsber** [comment]
Extension to general user: Daily average abstraction from one basin with return flow (%) to another basin

Return flow pump (conditional dependent) may be added later, either as a separate pump-object or integrated

**Comment by evetion** [comment]
Extended from #76
