### ISSUE TITLE
Add `FlowDemand` node for instream demand

### ISSUE THREAD

**Issue by gijsber** [Deltares/Ribasim#78]
This node connects to a flow node which is part of an allocation edge, and prescribes a flow demand there. This flow node is then treated as a user with 100% returnflow. 

What came out of discussion with the RTC-Tools team:
- return flow from `UserDemand` and `FlowDemand` should act as a source for later priorities. This means that a source must be introduced for every return flow to which capacity is added when the node has an inflow.

Note that this also changes the behavior of `UserDemand` nodes, and makes https://github.com/Deltares/Ribasim/issues/899 obsolete.

**Comment by SnippenE** [comment]
Discuss how we can take a minimum flow into account in the allocation optimisation step (incl the model specification)

**Comment by gijsber** [comment]
For allocation:
introduce node TargetFlow which is associated with a connector node.
Specify a miniflow_flow_rate and priority.
Include in allocation problem as a flow_rate to preserve

**Comment by SouthEndMusic** [comment]
It is relatively easy to do a naïve implementation of this, that is: add a term to the objective function for the flow trough the specified node. However:
- The way the allocation optimization problems are set up now, the optimizer would only be able to satisfy (part of) the flow demand if the flow can end up somewhere afterwards. Currently that is only at user nodes (and in the future that could also be at terminal nodes), but that would only happen if these users have sufficient demand.
-  Given the problem above, would it be useful to let the flow demand persist in priorities later than its own? Especially given that unlike users, the flow demand does not use up the flow.

**Comment by gijsber** [comment]
Hi @SouthEndMusic,
Than that Terminal node implementation becomes more important
I think there is no objection when we have a FlowDemand with priority 2 that the same FlowDemand is repeated at priority 3
