### ISSUE TITLE
allow specifying "ribasim.toml" and "database.gpkg" paths rather than hardcoding in `model.write("path/to/model")`

### ISSUE THREAD

**Issue by visr** [Deltares/Ribasim#800]
This came up in #638. Since the filename and path of the TOML and database are not special, we should also provide a way to set them explicitly. This can allow for instance putting multiple models in the same directory if a user wants this, or have the two files in different folders.

Not sure what the best API for this is. Perhaps the `database` path needs to be set in the Model, and the only argument to `model.write` then becomes the path to the config file: `model.write(path/to/model/ribasim.toml)`, rather than a directory.

Hardcoded here:
https://github.com/Deltares/Ribasim/blob/0b7b72d32aa155d01f6285ff6dd66afd0705f42b/python/ribasim/ribasim/model.py#L65
https://github.com/Deltares/Ribasim/blob/0b7b72d32aa155d01f6285ff6dd66afd0705f42b/python/ribasim/ribasim/model.py#L200

@evetion what does this do?

https://github.com/Deltares/Ribasim/blob/0b7b72d32aa155d01f6285ff6dd66afd0705f42b/python/ribasim/ribasim/model.py#L79-L81

**Comment by evetion** [comment]
That hardcodes the database name ofcourse. Very much like our Julia code.

**Comment by visr** [comment]
Right, thanks. I'm aware we also hardcode it on the julia side, just wanted to leave some references.

Creating this now because I was working out issues that were mentioned to be picked up after the Python refactor, I didn't expect the refractor to tackle these.

**Comment by visr** [comment]
Folding this into #799
