### ISSUE TITLE
Using Julia debugger in VS Code

### ISSUE THREAD

**Issue by SouthEndMusic** [Deltares/Ribasim#801]
I'm unable to consistently use the Julia debugger in VS Code. Yesterday I got it somewhat working with @deltamarnix where we noticed that `with_logger(logger)` in `bmi.jl` prevents the debugger from stopping at a breakpoint. Today I only got the debugger running on files that are within my local `Ribasim` folder, but now breakpoints are ignored altogether. If the `with_logger(logger)` problem persists this is something that could be fixed in the code, otherwise it is a problem at my side locally. 

I'm using a simple script like this:
```julia
using Ribasim

toml_path = "path/to/Ribasim/generated_testmodels/basic/ribasim.toml"
Ribasim.run(toml_path)
```

**Comment by visr** [comment]
Cannot reproduce. `with_logger` is now only in main, so shouldn't affect your script.
