### ISSUE TITLE
Discuss __repr__ in ribasim Python

### ISSUE THREAD

**Issue by evetion** [Deltares/Ribasim#809]

**Comment by visr** [comment]
See current `__repr__` in #808

**Comment by evetion** [comment]
From refinement, show DataFrame for TableModels, for nodemodels (and thus Model) above, show `Pump(static)` or `Pump(static,time)`, showing only which tables are set/present.

**Comment by Huite** [comment]
Good question! Probably not.

Omitting None makes sense, so it's consistent to omit things only containing None as well.
