### ISSUE TITLE
Create local QGIS unit tests

### ISSUE THREAD

**Issue by deltamarnix** [Deltares/Ribasim#813]
The tests can currently only run in the QGIS environment over docker. It would be easier in the workflow if we could create unit tests that can simply be run and debugged in vs code.

This might already work, but we have no tests proving it.

**Comment by deltamarnix** [comment]
I have posted an issue about the test discovery not being successful now that I have conda installed on my computer.

https://github.com/microsoft/vscode-python/issues/22581

**Comment by Hofer-Julian** [comment]
Ah, good that I am in the process of reviewing that one :P
