### ISSUE TITLE
Discussion for Followup: Do we need to deal with inconsistencies between MODFLOW and Ribasim subgrid levels & bottoms

### ISSUE THREAD

**Issue by Huite** [Deltares/Ribasim#824]
Due to likely different origins of the MODFLOW and Ribasim data, the levels and bed elevations are generally not consistent.

If the MODFLOW bed level (19.16 m NAP) is higher the Ribasim subgrid level (19.03 m NAP), then:

* MODFLOW will not start infiltrating, even if there is a water column of 0.1 m height
* This does not cause real trouble for the Ribasim water balance

Alternatively if the Ribasim subgrid level is higher, then:

* MODFLOW will never stop infiltrating, even if the basin level is at bed level (i.e. basin is empty)
* This does cause trouble, although Ribasim will simply omit the infiltration flow. This creates a water balance gap.

Possible workarounds:

* The best: make bed levels consistent. Arguably the Ribasim bed levels should be taken as leading, and burned into the MODFLOW input.
* Omit the package in MODFLOW, and generate a consistent one before/during coupling preprocessing. Problems here are getting widths, conductances, etc.
* Use the water depth instead. Expose the bed level from within Ribasim, then during coupling compute: `modflow_level = modflow_bottom + (subgrid_level - subgrid_bottom)`. This is not very attractive, since it shifts the hypothetically plausible water levels from the subgrid input by whatever deviation the MODFLOW bottom has.

**Comment by Huite** [comment]
Pragmatic solution: change the bed level of the MODFLOW model while setting up the coupled model input.
For drainage package: change elevation.
For river package: change elevation, stage by (elevation_subgrid - elevation_modflow)

**Comment by Huite** [comment]
Automatically fixing it should maybe be a configuration option imod_coupler preprocessing code.

**Comment by SnippenE** [comment]
Laternative (and at this moment preferred solution) first provide modeller with a warning that there is a inconsistency
