### ISSUE TITLE
Parallel Ribasim core tests fail non-deterministically on MacOS

### ISSUE THREAD

**Issue by SouthEndMusic** [Deltares/Ribasim#825]
Only this failure remains: https://github.com/Deltares/Ribasim/issues/825#issuecomment-1825974616

~~Specifically `@testitem "Allocation solve"` and `@testitem "Expand logic_mapping"`. They pass when running the tests sequentially (`runtests(Ribasim)` in `runtests.jl`) but sometimes fail when running the tests in parallel 
(`runtests(Ribasim; nworkers = min(4, Sys.CPU_THREADS ÷ 2), nworker_threads = 2)
` in `runtests.jl`).~~

https://docs.juliahub.com/General/ReTestItems/stable/autodocs/#ReTestItems.runtests

**Comment by visr** [comment]
Perhaps it is unrelated to parallel after all, since there are also random failures now that we switched to sequential. Or perhaps both issues occur.

Seen locally (now updated to 4.0, see #827):
```
Test Failed at D:\Ribasim\core\test\allocation_test.jl:22
  Expression: F[(NodeID(1), NodeID(2))] ≈ 4.5
   Evaluated: 4.0 ≈ 4.5
```

On main: https://github.com/Deltares/Ribasim/actions/runs/6981404082/job/18998462984?pr=823#step:9:540
```
Test Failed at /home/runner/work/Ribasim/Ribasim/core/test/utils_test.jl:173
  Expression: Ribasim.expand_logic_mapping(logic_mapping)
    Expected: Multiple control states found for DiscreteControl node #1 for truth state `TTF`: foo, bar.
  No exception thrown
```

**Comment by visr** [comment]
In 8ef0361d90471ac99a1507064f4b473588d562cc I temporarily workaround / disable these two tests, and re-enable parallel tests, to get CI functional.

**Comment by visr** [comment]
Here is one non-deterministic issue that still happens sometimes, that is related to the switch to ReTestItems: https://github.com/Deltares/Ribasim/actions/runs/6983243135/job/19004024801#step:9:443

```
ERROR: LoadError: IOError: mkdir("/var/folders/3s"; mode=0o777): permission denied (EACCES)
Stacktrace:
  [1] uv_error
    @ Base ./libuv.jl:100 [inlined]
  [2] mkdir(path::String; mode::UInt16)
    @ Base.Filesystem ./file.jl:185
  [3] mkdir
    @ Base.Filesystem ./file.jl:177 [inlined]
  [4] mkpath(path::String; mode::UInt16)
    @ Base.Filesystem ./file.jl:241
  [5] mkpath(path::String; mode::UInt16) (repeats 3 times)
    @ Base.Filesystem ./file.jl:239
  [6] mkpath
    @ ./file.jl:235 [inlined]
  [7] runtests(shouldrun::typeof(ReTestItems.default_shouldrun), paths::String; nworkers::Int64, nworker_threads::Int64, worker_init_expr::Expr, testitem_timeout::Float64, retries::Int64, memory_threshold::Float64, debug::Int64, name::Nothing, tags::Nothing, report::Bool, logs::Symbol, verbose_results::Bool, test_end_expr::Expr)
    @ ReTestItems ~/.julia/packages/ReTestItems/HZCMZ/src/ReTestItems.jl:234
  [8] runtests(shouldrun::Function, pkg::Module; kw::@Kwargs{nworkers::Int64, nworker_threads::Int64})
    @ ReTestItems ~/.julia/packages/ReTestItems/HZCMZ/src/ReTestItems.jl:196
  [9] runtests
    @ ReTestItems ~/.julia/packages/ReTestItems/HZCMZ/src/ReTestItems.jl:193 [inlined]
 [10] #runtests#38
    @ ReTestItems ~/.julia/packages/ReTestItems/HZCMZ/src/ReTestItems.jl:192 [inlined]
```

This looks like it could be a ReTestItems issue, if it does parallel mkdir and the folder name is "/var/folders/3s", that looks like a recipe for race conditions.

**Comment by Hofer-Julian** [comment]
@visr Now that https://github.com/Deltares/Ribasim/pull/872 has been merged, should we close this issue?

**Comment by SnippenE** [comment]
Can not fix because we couldn't find a solution
