### ISSUE TITLE
PID example result plot need updating

### ISSUE THREAD

**Issue by visr** [Deltares/Ribasim#834]
I think this should be following the dotted line. Either the dotted line is wrong or the model is not working as expected.

![cell-55-output-1](https://github.com/Deltares/Ribasim/assets/4471859/5a8459b8-0819-4ad0-80bd-0f12c326c416)

https://deltares.github.io/Ribasim/python/examples.html#model-with-pid-control

**Comment by SouthEndMusic** [comment]
This has been fixed.
