### ISSUE TITLE
Accommodate all variations of predefined boundary conditions

### ISSUE THREAD

**Issue by gijsber** [Deltares/Ribasim#84]
New node types:

- [x] Level (initial or terminal)
- [ ] Flow (initial or terminal)
- [ ] Terminal (only terminal)

Wait with Outlet with/without Salinity (terminal node) user request shows the need

**Comment by SouthEndMusic** [comment]
@visr and I had a discussion about this. We came to the following conclusions:
1. What is now the `LevelControl` node can be turned into a `Level` node, by removing the `conductance` field and renaming the `target_level` field to `level`. `LevelControl` is then equivalent to the combination of a `LinearResistance` node and a `Level` node.
2. The flow node is essentially a pump with only a single connection, so this could either be added as a new node or be added to the `Pump` node.

A flow node is also equivalent to the current `Pump` node and a `Level` node, but then the role of the `Level` node is a bit vague.

**Comment by gijsber** [comment]
I am not sure about the Pump. In my opinion we currently miss the maximum flow capacity in the pump which tells the controller what its pump range is. However, I can imagine that we have a Flow node (or a SetFlow node) which has an optional maximum flow rate and acts like a SetFlowRate in the model. But the direction of flow being set should be clear and I had the impression the current pump implementation looks at waterlevels to decide in which direction the flow rate has to go.

**Comment by gijsber** [comment]
The Level node definitely has a role as a downstream boundary condition and possibly upstream as well. I have not made my mind up whether it is wise from a modeller's perspective to split LevelControl in two nodes, since level control is so important with Dutch water management. But if it becomes logical within the entire control concept that is under development, I would probably agree. Some face to face discussion with sketch board would help (ie next week :-))

**Comment by visr** [comment]
> But the direction of flow being set should be clear and I had the impression the current pump implementation looks at waterlevels to decide in which direction the flow rate has to go.

The pump looks at the edge direction for the flow direction, a positive flow is along the edge direction.

https://github.com/Deltares/Ribasim/blob/30691e8e065119404dd6b2219b55d51c9131eb10/core/src/solve.jl#L229-L230

Similarly for other directional nodes, like TabulatedRatingCurve. Hence #148, since it is important that users see the direction. Also all flows on edges are defined to be positive in the edge direction.

**Comment by SouthEndMusic** [comment]
After a discussion with @gijsber and @visr we came to the conclusion that we need 3 new node types as adjusted in the first comment above. I won't touch the LevelControl for now.

**Comment by SouthEndMusic** [comment]
Please let me know if this is the right way of thinking about the terminal node (I imagine some of these points also being relevant for #200):

- The terminal node has no state (e.g. storage) or properties (e.g. storage-level relationship)
- As such it can only be connected downstream from a node which prescribes flow without downstream information (pump, fractional flow, tabulated rating curve...)
- At most one terminal node exists in the graph
- The terminal node can only act as a sink, not as a source. How is this enforced?

**Comment by visr** [comment]
Yes, points 1 and 2 are correct. Regarding point 3, I don't see a reason to limit it to a single node, sometime multiple ones can be useful. And regarding point 4, indeed it is only a sink. I don't know how it would be possible to extract water from it, if we implement point 1 and 2.
