### ISSUE TITLE
Test libribasim with xmipy's testbench

### ISSUE THREAD

**Issue by Hofer-Julian** [Deltares/Ribasim#85]
We now build libribasim on TeamCity, but we don't actually test if it is functional.
When iMOD Coupler will be used to couple Ribasim and MODFLOW, we will want to use xmipy for that.
So we will fulfill two tasks in one go by:

- [x] Extend libribasim's API
- [x] Getting the xmipy testbench to work locally with libribasim
- [x] Testing this setup on TeamCity

This should be done as soon as possible, in order to increase confidence in libribasim`s stability

**Comment by gijsber** [comment]
~6d, the earlier the better

**Comment by Hofer-Julian** [comment]
This is mostly fixed by https://github.com/Deltares/Ribasim/pull/156
Let's create follow up issues for the remaining tasks.
