### ISSUE TITLE
Making a diagram of the Ribasim-Modflow-MetaSWAP coupling

### ISSUE THREAD

**Issue by Huite** [Deltares/Ribasim#869]
Like this image:

![image](https://github.com/Deltares/Ribasim/assets/13662783/2615029c-81ee-45b7-8fec-ccea6bb0161c)

Make a mermaid plot (https://quarto.org/docs/authoring/diagrams.html), but also involve the physical meaning.
That is, it should be clear what the saturated zone is, the unsaturated zone, and the surface water.

**Comment by SnippenE** [comment]
Where comes Ribasim in this picture?

**Comment by Hofer-Julian** [comment]
@SnippenE This picture is for the MODFLOW-MetaSWAP coupling. @Huite is suggesting to make a similar one of the Ribasim-MODFLOW-MetaSWAP coupling
