### ISSUE TITLE
Support datamodel-code-generator 0.25+

### ISSUE THREAD

**Issue by SouthEndMusic** [Deltares/Ribasim#887]
**What**
With #897 we use datamodel-code-generator 0.24, but if we use 0.25 we get the following issue when running
```
pixi run codegen
pixi run generate-testmodels
```
the first line introduces problems that become apparent when running the second line. Error when trying to generate `basic_transient` model:
```
Value error, Error while coercing 'BasinTimeSchema' to type <class 'ribasim.models.BasinTime'>: Could not coerce <class 'pandas.core.frame.DataFrame'> data_container into type <class 'ribasim.models.BasinTime'>
      index                                failure_case
0         0  {'time': Timestamp('2020-01-01 00:00:00')}
1         1  {'time': Timestamp('2020-01-01 00:00:00')}
2         2  {'time': Timestamp('2020-01-01 00:00:00')}
3         3  {'time': Timestamp('2020-01-01 00:00:00')}
4         4  {'time': Timestamp('2020-01-02 00:00:00')}
...     ...                                         ...
1463   1463  {'time': Timestamp('2020-12-31 00:00:00')}
1464   1464  {'time': Timestamp('2021-01-01 00:00:00')}
1465   1465  {'time': Timestamp('2021-01-01 00:00:00')}
1466   1466  {'time': Timestamp('2021-01-01 00:00:00')}
1467   1467  {'time': Timestamp('2021-01-01 00:00:00')}

[1468 rows x 2 columns] [type=value_error, input_value=      node_id       time ...
[1468 rows x 7 columns], input_type=DataFrame]
    For further information visit https://errors.pydantic.dev/2.5/v/value_error
```

It is probably due to the fact that in `python/ribasim/ribasim/models.py`, `datetime.datetime` gets replaced by `pydantic.AwareDatetime`.

**Why**
Generating test models should just work.

**How**
Not sure yet. Options are:

- We switch to properly using and testing timezone aware datetimes everywhere, so we can use `pydantic.AwareDatetime`.
- We (automatically) replace `pydantic.AwareDatetime` with `pydantic.NaiveDatetime`
- Contribute such an option upstream if there is demand

https://github.com/koxudaxi/datamodel-code-generator/pull/1735
https://docs.pydantic.dev/latest/api/types/#pydantic.types.AwareDatetime

**Comment by evetion** [comment]
Interesting, wonder what changed.

**Comment by visr** [comment]
#849 did not update pydantic, but did update datamodel-code-generator from 0.24.2 to 0.25.1. This has this as a breaking change: https://github.com/koxudaxi/datamodel-code-generator/releases/tag/0.25.0

**Comment by visr** [comment]
Since we don't do anything with timezones yet, I guess the `NaiveDatetime` makes most sense for us, not `AwareDatetime`.

https://docs.pydantic.dev/latest/api/types/#pydantic.types.AwareDatetime

**Comment by evetion** [comment]
That seems a fair fix (and good to pin the package?). Note that naivedatetime should be phased out though, datetimes need a timezone.

**Comment by visr** [comment]
#897 pins the package. I'll re-use this issue be able to un-pin datamodel-code-generator.

> datetimes need a timezone

That would probably need a separate discussion / design. If we start this then I guess all our datetimes always will need a timezone, or we need to set it in the config.
