### ISSUE TITLE
Variable  ribasim output does not update in Time Series plot QGIS

### ISSUE THREAD

**Issue by jc-hunink** [Deltares/Ribasim#892]
When i switch between Edge and Node in de Time Series tool (iMOD QGIS plugin) the variable does not update. For example, when i switch to Node and select a node in qgis i only can select the variables with are connected tot the Edges and i cannot select level or storage.

![image](https://github.com/Deltares/Ribasim/assets/44274419/b76cdc0f-1e3e-4015-b9df-4bbb0cd554fc)

**Comment by visr** [comment]
Yes, I agree this behavior is not great. I did mention it briefly in [the docs](https://deltares.github.io/Ribasim/qgis/#sec-results):

> Note that before switching between these, you typically have to click “Clear” to clear the selection. 

So if you do that first, you should be able to switch layers and corresponding variables.

To improve this I guess we could automatically clear the selection on switching layers. But I'm not sure why that is needed at all, within QGIS you can keep a selection per layer. Using that would be preferable.

**Comment by visr** [comment]
This was fixed in https://github.com/Deltares/imod-qgis/pull/79, which has been released in imod-qgis v0.5.2.
