### ISSUE TITLE
Evaluate iteration scheme for MF6-MetaSWAP-Ribasim coupling. 

### ISSUE THREAD

**Issue by HendrikKok** [Deltares/Ribasim#894]
In the current MF6-Ribasim and MF6-MetaSWAP-Ribasim coupling, the Ribasim solve is last in line of the update sequence. This means that at the end of timestep = t, MetaSWAP knows what sprinkling demand can be realized. But at this point, MF6-Metaswap are already solved for timestep = t. 

For a proper implementation, the realized sprinkling volume needs to be known before the MF6-MetaSWAP solve. 

In the coupling with DFLOW-FM (Lumbricus), the DFLOW solve also comes before the MF6-Metaswap solve. 
In the coupling with Mozart, the case where sprinkling realised != demand triggers the save state sequence and an update from the realized fractions. This means again that the realized sprinkling is know before the MF-MetaSWAP solve.  

Below the update schemata for both couplings:

![update_schemata](https://github.com/Deltares/Ribasim/assets/59684726/d7741aa5-2332-4877-8862-c4c407cbc3ad)

**Comment by rleander** [comment]
Schematics in markdown, convenient for both of us to edit:
The RibaMetaMod scheme:
```mermaid
sequenceDiagram
    autonumber
    Note over MetaSWAP: sw timestep t
    MetaSWAP->>Ribasim:  sprinkling demand [t]
    MetaSWAP->>Ribasim:  runoff [t]
    Ribasim->>MODFLOW6:  stage [t-1]
    loop MODFLOW6-MetaSWAP iteration:
        Note over MetaSWAP: solve t
        MetaSWAP->>MODFLOW6:  storage & uz-flux
        Note over MODFLOW6: solve t
        MODFLOW6->>MetaSWAP:  storage & uz-flux
    end
    MODFLOW6 ->> Ribasim: q-riv [t]
    Note over Ribasim: solve t
    Ribasim->>MetaSWAP: sprinkling realised [t]
```

<br>
... and the Mozart driver:
<br>
```

```mermaid
sequenceDiagram
    autonumber
    loop Mozart iteration, (twice) to get realized sprinkling for timestep t
    Mozart-->>MetaSWAP:  sprinkling realized [t]
        Note over MetaSWAP: sw timestep t
        Mozart->>MODFLOW6:  stage [t-1]
        loop MODFLOW6-MetaSWAP iteration:
            Note over MetaSWAP: solve t
            MetaSWAP->>MODFLOW6:  storage & uz-flux
            Note over MODFLOW6: solve t
            MODFLOW6->>MetaSWAP:  head
        end
        MetaSWAP->>Mozart:  sprinkling demand [t]
        MetaSWAP ->> Mozart:  runoff [t]
        MODFLOW6 ->> Mozart: q-riv [t]
        Note over MetaSWAP: save state
        Note over MODFLOW6: save state
        Note over Mozart: solve t
        Note over Mozart: initiate save state
    end
```

**Comment by SnippenE** [comment]
Can #7 be closed?

**Comment by HendrikKok** [comment]
closed in favor of [issue 894](https://github.com/Deltares/Ribasim/issues/971)
