### ISSUE TITLE
Ability to merge two Ribasim models in Python

### ISSUE THREAD

**Issue by evetion** [Deltares/Ribasim#912]
@SouthEndMusic 

This would be helpful in writing larger testmodels that don't duplicate code, but can merge smaller test models.

Could be generically implemented as follows:
- *Merge method on the [TableModel](https://github.com/Deltares/Ribasim/blob/836dc7178bf06abd0e60d61029f1be787c04cc3a/python/ribasim/ribasim/input_base.py#L159) class*, that merges the existing table with another TableModel (e.g. PumpStatic) using pandas, taking care of unique ids, after checking the schemas are the same.
- *Merge method on the [NodeModel](https://github.com/Deltares/Ribasim/blob/836dc7178bf06abd0e60d61029f1be787c04cc3a/python/ribasim/ribasim/input_base.py#L384) class*, that takes another NodeModel (e.g. Pump) class and merges with it, by calling the merge method (see above) on all its children that are tablemodels.
- *Merge method on the [Model](https://github.com/Deltares/Ribasim/blob/836dc7178bf06abd0e60d61029f1be787c04cc3a/python/ribasim/ribasim/model.py#L100) class* that merges with another Model. It will call the above merge method for all its children that are Nodes.

The difficulty lies in making sure the renamed node_ids are either known at the Model merge level, and used in other methods, or the renaming of the node_ids follows a fixed schema. So when the Nodes and Edges are renamed, they still are linked to things like Pumps.

**Comment by visr** [comment]
This is probably easier to implement now after #1110. Node IDs only have to be made unique per node type.

**Comment by SouthEndMusic** [comment]
Closed in favor of https://github.com/Deltares/Ribasim/issues/1297.
