### ISSUE TITLE
Build `ribasim_cli` and `libribasim` on Linux

### ISSUE THREAD

**Issue by Hofer-Julian** [Deltares/Ribasim#93]
At some point, people will want to run Ribasim on Linux clusters.
Luckily, all the puzzle pieces to build it on TeamCity are there.
We just need to assemble them.

**Comment by deltamarnix** [comment]
#878 ensures that julia is installed via pixi, so we don't need to rely on the julia version that is installed on the agents.

**Comment by deltamarnix** [comment]
Putting this ticket back to In Progress, as we are waiting for the Teamcity Support Team to make our linux servers larger so we can run `pixi run install` on them. We now get an out-of-disk-space error
