### ISSUE TITLE
Change flow results from instantaneous to average over past timestep

### ISSUE THREAD

**Issue by visr** [Deltares/Ribasim#935]
**What**
Change flow results from instantaneous to average over past timestep.
Right now the flow results at time $t_i$ represent the instantaneous flow sampled at time $t_i$.
This should be changed to the mean flow from $t_{i-1}$ to $t_i$.

**Why**
To calculate the water balance, sampled flows are not very useful. Mean flows allow us to calculate total volumes over time periods. For coupling with Delwaq our flows need to be mean flows.

**How**
The `flow` we store in our metagraph and use extensively in our solver code need to stay instantaneous. The `saved_flow` for our results need to become mean flows over the period since the last save. To calculate the mean flow, we add a `flow_volume` and `flow_prev` vector in our graph next to the `flow`. At every timestop, we add the contribution of the past timestep to the `flow_volume`. We initially calculate this simply by taking the `@. flow_volume += (flow + flow_prev) * 0.5 * (t - tprev)`, after which we `copyto!(flow_prev, flow)`.

Then, at each `saveat`, we calculate the mean flow by dividing `flow_volume` by the time since the last saveat. After this we `fill!(flow_volume, 0.0)`.

This should be plenty for one PR. Follow ups:

- In `BMI.update_until`, check that the `saveat` is equal to the time since last BMI stop. This way we can use the same memory for both saving and BMI, at the cost of less flexibility.
- Add mean flow columns to the non-conservative node type structs
- Implement a more precise interpolation using Gaussian quadrature like described in #642

**Additional context**
I can't think of good reasons to keep the sampled flow output as well, so let's just switch the existing results.

**Comment by evetion** [comment]
Note that Delwaq needs *both* the instantaneous flow, as the averaged flow over the past timestep.

**Comment by Huite** [comment]
Are you sure? Instantaneous flow might literally be a flow that persists for a single second (or even a millisecond!) in the adapative timestepping.

**Comment by evetion** [comment]
Ah, sorry, mixed up my notes, we need the instantaneous volume, and indeed, averaged flow.
