### ISSUE TITLE
Extract doc chapter:  "Ribasim Functionality Demonstration"

### ISSUE THREAD

**Issue by Hofer-Julian** [Deltares/Ribasim#94]
The file `demo.ipynb` is outdated.

We should:

- [ ] Extract useful parts and put it into python-based tutorial (.qmd?)
- [ ] Delete demo.ipynb

**Comment by gijsber** [comment]
~1d

**Comment by visr** [comment]
Fixed in #103. The demo.ipynb is removed, and the ribasim-python based examples.ipynb is created. We might want to add more functionality demonstrations similar to those in demo.ipynb in the future.
