### ISSUE TITLE
Prefix `meta_` is not mentioned in the documentation

### ISSUE THREAD

**Issue by Huite** [Deltares/Ribasim#945]
The `prefix_column` function adds `meta_` to non-standard columns, but this isn't described anywhere in the usage docs.

Since it's quite general functionality, maybe it should be added in section 2 GeoPackage database and Arrow tables?https://deltares.github.io/Ribasim/core/usage.html#geopackage-database-and-arrow-tables

**Comment by visr** [comment]
Yes that sounds like a good spot.
