### ISSUE TITLE
Docs: 3/7 download links are down

### ISSUE THREAD

**Issue by Huite** [Deltares/Ribasim#946]
Maybe this is expected due to changes associated with TeamCity or something?

![image](https://github.com/Deltares/Ribasim/assets/13662783/49f2b072-736e-4f24-a301-516fa0667dce)

But it's confusing, if they don't work they should be temporarily removed.

**Comment by visr** [comment]
@Hofer-Julian do you know why the wheel didn't upload? Or did you remove it on purpose since it is on PyPI and conda-forge? Perhaps it is not needed.

The `ribasim_cli.zip` needs to be duplicated in `ribasim_cli_linux.zip` and `ribasim_cli_windows.zip`.

**Comment by Hofer-Julian** [comment]
> @Hofer-Julian do you know why the wheel didn't upload? Or did you remove it on purpose since it is on PyPI and conda-forge? Perhaps it is not needed.

Yes, I removed it on purpose. I think we discussed that, but I might misremember.

> The ribasim_cli.zip needs to be duplicated in ribasim_cli_linux.zip and ribasim_cli_windows.zip.

Will open a PR
