### ISSUE TITLE
Wiki page of Test models has unwanted text output

### ISSUE THREAD

**Issue by Jingru923** [Deltares/Ribasim#984]
In the page, there were supposed to be only brief introductions and graphs of the test models. Since we updated Pandas, many text messages have been generated.

```
/home/runner/work/Ribasim/Ribasim/.pixi/env/lib/python3.11/site-packages/pandera/backends/pandas/array.py:336: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.
```

As this text is not wanted, we should go to the source (Ribasim Python) where these warning texts are from and fix the problem.

**Comment by visr** [comment]
The warning mentioned in this issue comes from pandera, and there is an open pull request to fix it: https://github.com/unionai-oss/pandera/pull/1464. We could keep an older pandas in our pixi file to clear the docs, but this would not stop users from getting the warning.
