### ISSUE TITLE
Ribamod: priority of forcing and uncoupled basins

### ISSUE THREAD

**Issue by Huite** [Deltares/Ribasim#998]
Maybe two issues, but very strongly related:

## Obliteration of exchange terms

We are currently using the drainage and infiltration processes to couple with MODFLOW. In the coupling, Ribasim sets a step, sets the water levels for MODFLOW. Then MODFLOW runs, and returns drainage / infiltration terms.

However, if any basin.time forcing terms are defined they will result in the exchange terms being overwritten. Currently, this means that no transient forcing may be present (except the first timestep) in the Ribasim simulation (or they should be defined in static).
This seems undesirable: terms such as rainfall and precipitation directly on the basins should proceed via this way. Naturally, you'd fill in values of 0.0 for P and ET, but these then obliterate the values set by the coupling.

## Uncoupled basins

It will be quite common that basins are part of a flow network, but they are not part of the MODFLOW simulation. In this case, the imod_coupler terms should not be used in Ribasim. This is also true for the MetaMod driver, which solves this by reading the original values, and then using the mask array to essentially run: `mask * original_value + (1 - mask) * new_value`

We cannot do this for Ribasim currently (and it's debatable whether it's desirable), since the values are not necessarily stored or be will out-of-date.
One way of solving this is by introducing e.g. NaN values for the uncoupled basins, and letting Ribasim filter them out.

Alternatively, we could introduce drainage and infiltration terms specifically for the coupling which are 0.0 by default and which are never updated by the Ribasim IO. This is arguably the simplest solution, but may result in confusion when people duplicate the coupled and "pure" Ribasim input.

**Comment by Huite** [comment]
To test this, as well as some other issues that came up with setting up a real-life model:

* Use the backwater model
* Create a MODFLOW model that covers only the the inner 2/3rds of the model (so of the 50 basins, the left 10 or so fall outside of the groundwater domain, as well as the the 10 rightmost basins)
* Apart from the backwater surface water, there should be a second surface water, perpendicular on the existing one, falling outside of the basins, essentially. This ensures that there are both MODFLOW entities outside of the coupling, as well as Ribasim entities outside of the coupling.
* A bonus thing: the river bottoms should be higher than 0.0, such that if water levels at 0.0 are set, MODFLOW crashes (and the test fails). Specifically the value of 0.0, since MODFLOW initializes the elevation with 0.0, and if we fetch the values before calling prepare_time_step(), we will receive zeros.

**Comment by Hofer-Julian** [comment]
Closed by @Huite with https://github.com/Deltares/imod_coupler/pull/243
