### ISSUE TITLE
Ribamod: support uncoupled MODFLOW boundaries and Ribasim basins

### ISSUE THREAD

**Issue by Huite** [Deltares/Ribasim#999]
The spatial extents of the MODFLOW and Ribasim model do not necessarily overlap. This means a part MODFLOW boundaries and a part of the Ribasim basins should not be set.

This requires the creation of `mask_` variables, similar to the MetaMod driver, since the value_ptr arrays exposed via bmi/xmi always contain the full set of bounds and basins.

A secondary question is how to "mask" values for Ribasim basins, see #998

**Comment by Hofer-Julian** [comment]
Closed by @Huite with https://github.com/Deltares/imod_coupler/pull/243
